### ISSUE TITLE
Package.json cataloger malformed licences dropping package 

### ISSUE THREAD

**Issue by houdini91** [anchore/syft#1008]
**What happened**:
**Bug**
Packages with unstandard licenses field are dropped.

**Root**
 Package json structure unmarshaling error.

		if err := dec.Decode(&p); err == io.EOF {
			break
		} else if err != nil {
			return nil, nil, fmt.Errorf("failed to parse package.json file: %w", err)
		}
**Suggestion**
Unmarshal licences field in raw bytes and unmarshal it sepritly so that the package still gets added to the resulted sbom.

**Reproduce**: 
Dockerfile
```
FROM alpine
RUN apk add --update nodejs npm curl bash
RUN npm pack imagemagick;tar xvf imagemagick-0.1.3.tgz
```
Run
```
docker build -t imagemagick .
go run cmd/syft/main.go imagemagick:latest -vv
```
**Result**
imagemagick not found in report, warn package.json unmarshaling error. 
```
[0003]  WARN cataloger 'javascript-package-cataloger' failed to parse entries at location=Location<id=2673 RealPath="/package/package.json" VirtualPath="/package/package.json" Layer="sha256:c8dac2360cdcaa27d5916421ed865a06d0dc1af4016e9c2fb0548fdbbfa2f272">: failed to parse package.json file: json: cannot unmarshal string into Go struct field packageJSON.licenses of type javascript.license
```

**Suggestion result**
Imagemagick found in report, warn that licences field was not valid.
```
[0000]  WARN unable to extract licenses from javascript package.json: unmarshal failed

```

**Example package.json**
```
{ "name"        : "imagemagick"
, "description" : "A wrapper around the imagemagick cli"
, "version"     : "0.1.3"
, "author"      : "Rasmus Andersson <http://rsms.me/>"
, "licenses"    : ["MIT"]
, "repository"  : { "type" : "git"
                  , "url"  : "http://github.com/rsms/node-imagemagick.git" }
, "engine"      : ["node >=0.6"]
, "main"        : "imagemagick"
}
```

PR: https://github.com/anchore/syft/pull/1004

**Comment by jonasagx** [comment]
I appreciate the description and steps for reproduction. With [your PR merged](https://github.com/anchore/syft/pull/1004) we can close this issue. Thank you again.
