### ISSUE TITLE
Version is `[not provided]` when encoding to most formats

### ISSUE THREAD

**Issue by ribbybibby** [anchore/syft#1010]
**What happened**:
When using `syft` as a library, the `Descriptor.Version` field is ignored in an`sbom.SBOM` when encoding to the majority of formats. This results in a version of `[not provided]`.

See https://github.com/docker/sbom-cli-plugin/issues/20 for more detailed information.

**What you expected to happen**:
I would expect the resulting SBOM document to respect the version set in the `sbom.SBOM` OR it might be quite nice if the `syft` package was capable of figuring out (to the best of its ability) the version when used as a library.

**How to reproduce it (as minimally and precisely as possible)**:

Here's a snippet that reproduces the issue:
```golang
package main

import (
	"fmt"
	"os"

	"github.com/anchore/syft/syft"
	"github.com/anchore/syft/syft/sbom"
)

func main() {
	result := sbom.SBOM{
		Descriptor: sbom.Descriptor{
			Name:    "syft",
			Version: "foobar",
		},
	}

	bom, err := syft.Encode(result, syft.FormatByName(syft.CycloneDxJSONFormatID.String()))
	if err != nil {
		fmt.Printf("error: %s\n", err)
		os.Exit(1)
	}

	fmt.Printf("%s\n", bom)
}
```

```
$ go run ./...
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "serialNumber": "urn:uuid:00bdbd1e-154b-43f5-9385-f244d3f1a37e",
  "version": 1,
  "metadata": {
    "timestamp": "2022-05-23T16:36:50+01:00",
    "tools": [
      {
        "vendor": "anchore",
        "name": "syft",
        "version": "[not provided]"
      }
    ]
  },
  "components": []
}
```

**Any other info**:

FYI, this is how the SBOM plugin figures out the syft version: 
- https://github.com/docker/sbom-cli-plugin/blob/e5f6dbb32d8130f75e186bc47bbc4eb670e82d98/internal/version/build.go#L47-L63

**Comment by spiffcs** [comment]
@ribbybibby thanks for filing the issue - we just got https://github.com/anchore/syft/pull/1011 approved and should be able to be used when merged.
