### ISSUE TITLE
Bug on homebrew installations with "0.46.3"

### ISSUE THREAD

**Issue by akhil-cervello** [anchore/syft#1013]
We're facing errors while "brew install syft"
Downloading https://github.com/anchore/syft/releases/download/v0.46.3/syft_0.46.3_linux_amd64.tar.gz
curl: (22) The requested URL returned error: 404
Error: syft: Failed to download resource "syft"

seems This 0.46.3 is not released in https://github.com/anchore/syft/releases
It's only tagged?

**Comment by luhring** [comment]
Hi @akhil-cervello, this should be resolved now. Apologies for the disruption. Can you try again?
