### ISSUE TITLE
Panic from Syft cyclonedx format method

### ISSUE THREAD

**Issue by cpendery** [anchore/syft#1014]
**What happened**:
Syft's `toSyftModel` produces a panic on an empty components list

**What you expected to happen**:
It should report and error instead like it does for all other missing fields that it requires to run properly

**How to reproduce it (as minimally and precisely as possible)**:
```go
package main

import (
	"bytes"
	"encoding/json"

	"github.com/CycloneDX/cyclonedx-go"
	"github.com/anchore/syft/syft"
)

func main() {
	f := syft.FormatByID(syft.CycloneDxJSONFormatID)
	bom := cyclonedx.BOM{
		BOMFormat:   "CycloneDX",
		SpecVersion: "1.4",
		Version:     1,
	}
	bomBytes, _ := json.Marshal(&bom)
	f.Decode(bytes.NewReader(bomBytes))
}
```

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: v0.46.3
- OS (e.g: `cat /etc/os-release` or similar): Windows 11 Pro, 21H2

**Comment by spiffcs** [comment]
Thanks for reporting the error and a way to reproduce it @cpendery. Let me take a quick look here and get a fix in for this bug.
