### ISSUE TITLE
Add test to catch need for JSON output schema update

### ISSUE THREAD

**Issue by jonasagx** [anchore/syft#1031]
**What would you like to be added**:
A test validating that the latest schema version (for SBOM JSON output format) and structures that are marshaled into JSON are matching.

**Why is this needed**:
Needed so code and schema are always aligned. 

**Additional context**:
The lack of checks caused an extra review step on https://github.com/anchore/syft/pull/1026

**Comment by spiffcs** [comment]
Closed as this file validates the syft output against the schema:
https://github.com/anchore/syft/blob/main/test/cli/json_schema_test.go
