### ISSUE TITLE
syft attest cmd is not exporting output to file

### ISSUE THREAD

**Issue by developer-guy** [anchore/syft#1061]
**What happened**:

**What you expected to happen**:

We (w/@dentrax) noticed that Syft attest command has a --file option to redirect the output o a file but this feature is not working.

To reproduce an issue run the following commands:

```sh
$ syft atttest --key <key> <img>  -o json --file att.json
$ cat att.json
'att.json': No such file or directory (os error 2)
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: 0.48.1
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by spiffcs** [comment]
👋 Hi Developer guy:

When you run something lime `syft attest --key cosign.key -o json alpine:latest > attest.json` and redirect the output you can write to a file.

I know for the SBOM we have the `--file` option. Would you like to see this flag added on attestation as well?

**Comment by developer-guy** [comment]
Yep, I know this is my workaround too I redirected to a file through the `>` operator. But yeah, it'd be better to support the `--file` option for attestation as well, would you mind assigning it to me?

**Comment by spiffcs** [comment]
Sure - stabilizing the surfaces would be awesome to get some consistency between the commands:
cc @anchore/ci-tools-project if anyone has a different opinion on this issue
