### ISSUE TITLE
feat: add Erlang/Elixir (rebar, mix) support

### ISSUE THREAD

**Issue by cpendery** [anchore/syft#1071]
**What would you like to be added**:
I'd like to have my Erlang/Elixir projects where I used Hex be able to produce sboms

**Why is this needed**:
Erlang and Elixir are programming languages that have CVEs reported and are well established, so we should be able to produce sboms for them.

**Additional context**:

**Comment by cpendery** [comment]
happy to take on this contribution if its not being worked on internally

**Comment by westonsteimel** [comment]
@cpendery , thanks, that would be fantastic!
