### ISSUE TITLE
Don't replace : with - in docker SPDX namespaces

### ISSUE THREAD

**Issue by aethanol** [anchore/syft#1111]
**What would you like to be added**:
In https://github.com/anchore/syft/pull/649, https://github.com/anchore/syft/blob/main/internal/formats/common/spdxhelpers/document_name.go#L26 was introduced which replaces `:` with `-` in namespaces. This impacts the output name of docker SPDX.
Ideally these docker names like `IMAGE[:TAG|@DIGEST]` would be the same as outputted by syft.

**Why is this needed**:
We are having to manually parse this on ingestion time, back to : so we can correlate docker images with their syft scans.

**Comment by kzantow** [comment]
For document name, we should not be "cleaning" the name -- it is a raw string. Check the following functions, it looks like we should NOT be calling `cleanName`:

* https://github.com/anchore/syft/blob/main/syft/formats/common/spdxhelpers/document_namespace.go#L19
* https://github.com/anchore/syft/blob/main/syft/formats/common/spdxhelpers/document_name.go#L10
