### ISSUE TITLE
Phantom release 0.53.0

### ISSUE THREAD

**Issue by log2** [anchore/syft#1128]
**What happened**:
Release 0.53.0 is shown as existent in git tags, so for example, using [asdf syft plugin](https://github.com/davidgp1701/asdf-syft.git):

`asdf latest syft` or `asdf latest syft 0.53.0`

which uses git tags (see [this code](https://github.com/davidgp1701/asdf-syft/blob/main/lib/utils.bash#L28)), the following output is shown:

`0.53.0`

However, that release cannot really be installed since it lacks actual binaries to download, so the following command fails:

`asdf install syft 0.53.0`

```
Downloading syft from https://github.com/anchore/syft/releases/download/v0.53.0/syft_0.53.0_darwin_amd64.tar.gz
tar: Error opening archive: Unrecognized archive format
```

The issue can be confirmed with curl:

```
❯ curl https://github.com/anchore/syft/releases/download/v0.53.0/syft_0.53.0_darwin_amd64.tar.gz
Not Found
```

**What you expected to happen**:

A release declared in tags should be downloadable and installable (either via asdf syft plugin, or by other means).

**How to reproduce it (as minimally and precisely as possible)**:

Just use asdf syft plugin with the aforementioned steps.

**Anything else we need to know?**:

Another way to fix this would be, in asdf syft plugin, to use a `curl https://api.github.com/repos/anchore/syft/releases` rather than a `git ls-tags` command, since the former looks at actual releases, while the latter lists barely the git tags (which may or may not have actual releases beneath them). In fact, the first command currently does not show `0.53.0` phantom version, while the second one does.

Note that this issue is much similar to grype's [issue](https://github.com/anchore/grype/issues/842) for 0.44.0 version.

**Environment**:
- Output of `syft version`:
- OS (e.g: `cat /etc/os-release` or similar):

```
❯ sw_vers
ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G72
```

**Comment by spiffcs** [comment]
The release has been published - closing this issue - Thanks for the quick report!
