### ISSUE TITLE
Add flag to disable Syft hitting toolbox-data.anchore.io

### ISSUE THREAD

**Issue by cpendery** [anchore/syft#1185]
**What would you like to be added**:
A flag to disable Syft's checking of the most recent version of Syft to prompt for potential update

**Why is this needed**:
Syft tries to hit Anchore's s3 toolbox on every run, which causes a long delay when running in an air gapped environment. 

```shell
[0030] ERROR failed to fetch latest version: Get "https://toolbox-data.anchore.io/syft/releases/latest/VERSION": dial tcp 111.11.1.111:443: i/o timeout
```

**Additional Information**
Grype provides this under the `GRYPE_DB_AUTO_UPDATE` environment variable

**Comment by joshbressers** [comment]
I think this exists

```
# enable/disable checking for application updates on startup
# same as SYFT_CHECK_FOR_APP_UPDATE env var
check-for-app-update: true
```

https://github.com/anchore/syft/blob/main/README.md?plain=1#L427
