### ISSUE TITLE
README instructions don't work verbatim

### ISSUE THREAD

**Issue by DaveJarvis** [anchore/syft#1196]
From the README:

``` bash
$ curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
```

**Expected**
Installs.

**Actual**
Doesn't install.

```
[info] fetching release script for tag='v0.55.0' 
[info] using release tag='v0.55.0' version='0.55.0' os='linux' arch='amd64' 
install: cannot create regular file '/usr/local/bin/syft': Permission denied
[error] failed to install syft 
```

System:

``` bash
$ uname -a
Linux hostname 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux
```

**Work around**
``` bash
$ curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin
[info] fetching release script for tag='v0.55.0' 
[info] using release tag='v0.55.0' version='0.55.0' os='linux' arch='amd64' 
[info] installed /usr/local/bin/syft 
```

**Additional details**
Consider updating the README instructions.

**Comment by spiffcs** [comment]
Nice find @DaveJarvis! - I'm not thrilled to be putting sudo into the install scripts so maybe there is a friendlier path we can find that the local user can install things onto:

`sh -s -- -b /home/$(whoami)/bin`?
`sh -s -- -b /home/$(whoami)/.local`?

**Comment by DaveJarvis** [comment]
> sh -s -- -b /home/$(whoami)/bin?

Not all systems/distros include `$HOME/bin` in the `PATH` environment variable by default. The following would cover most systems:

    mkdir -p $HOME/bin
    sh -s -- -b $HOME/bin
    export PATH="${PATH}:$HOME/bin"

Where setting the PATH would be done (optionally) by the user.

**Comment by kzantow** [comment]
This is currently a second documented way to install to an alternate directory in the [README here](https://github.com/anchore/syft#recommended). This would work for all cases where a user does not have permissions to install to `/usr/local/bin`. Maybe we just add a note to the effect of "if you encounter a Permission denied, you may need to specify a custom directory"?

**Comment by DaveJarvis** [comment]
> Maybe we just add a note to the effect of "if you encounter a Permission denied, you may need to specify a custom directory"?

Won't users almost always encounter the permission denied issue if they run the listed instructions verbatim? Why document a command that doesn't work?

**Comment by spiffcs** [comment]
Maybe update the install script to `curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b .` with an optional "here is how to get things into the path instructions"

**Comment by DaveJarvis** [comment]
@spiffcs if there's only a single binary, that'd be fine, although technically since `.` isn't typically in the path, you'd have to use `./syft` instead of `syft`. Truly, you are probably better off with:

``` bash
mkdir -p "${HOME}/bin"
export PATH="${PATH}:${HOME}/bin"
... sh -s -- -b "${HOME}/bin"
chmod +x "${HOME}/bin/syft"
```

**Comment by joshbressers** [comment]
We could opt for the sort of install experience nvm gives
https://github.com/nvm-sh/nvm#installing-and-updating

`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash`

It downloads to a .nvm directory then adds things to the shell rc file (.bashrc or .zshrc for example). This could be overkill for a single go binary, but is a nicer user experience

**Comment by per-bohlin** [comment]
For most Linux administrators, requiring running as root or with sudo is implied by the privileged path `/usr/local/bin`. To help inexperienced administrators, perhaps a note in the docs prior to the command saying something along the lines of "(may require root/sudo privileges)" may be enough to put them on the right path. Or, if the install script can detect the missing permissions, it could give the hint as part of the failure message.

Modifying user's .bashrc/.zshrc is for me the wrong way to go. The chosen installation path should be the deciding factor if I want the tool in path or not. As few side-effects as possible is advised. Not all installation contexts has a clear user; such as in docker images, base-images for VMs, tool-packages for CI. Side-effects such as modifying other files beyond the install directory risk breaking these kind of use-cases.

**Comment by kzantow** [comment]
We have a few suggestions here, and I think we would want to keep the download as a single line command. This is done easily as @spiffcs mentioned with:
```
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b .
```
The caveat is you would have to run `./syft`, which seems like it would be a simple thing to document. We then add the second variant with some text like: "If you would like to install in your system bin directory, run this as root:" 
```
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
```
That should avoid any confusion for users who do not have root access and that the `/usr/local/bin` probably needs root access to write to it. Hopefully a user could figure this out from there.

What do you all think?

**Comment by DaveJarvis** [comment]
Consider:

``` bash
mkdir -p $HOME/syft
cd $HOME/syft
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b .
./syft
```

**Comment by spiffcs** [comment]
This one from @DaveJarvis seems best as far as a "just works" standpoint to update the docs to help people get started
```
mkdir -p $HOME/syft
cd $HOME/syft
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b .
./syft
```

**Comment by kzantow** [comment]
What I don't understand about this one is why adding a subdirectory? It would work equally well in the current directory, provided it's writable. If a user has `cd`'d to a non-writable directory and can't understand why they can't write to said directory I'm not sure that we should cater to this type of error.

If we were going to include a multi-step process like this, it would be easier to do this, so the user wouldn't be changing directories and could scan wherever they happen to be in the filesystem easily:
```
mkdir -p $HOME/syft
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b $HOME/syft
$HOME/syft/syft
```

But I still think this is overkill, and we should have a 1-liner to get people started. Which could even be something like this:

```
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b $HOME
$HOME/syft
```

**Comment by DaveJarvis** [comment]
Technically, you'd probably want it in `$HOME/bin`, but I suggested `$HOME/syft` because I didn't know how many files were going to be created/installed and wanted to somewhat respect the XDG Base Directory Specification. However, the XBDS would probably mean using `$HOME/.syft` to avoid cluttering users' home directory. See:

* https://wiki.debian.org/XDGBaseDirectorySpecification
* https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by kzantow** [comment]
@DaveJarvis - there is just a single binary (`syft`) which gets installed.

**Comment by per-bohlin** [comment]
@DaveJarvis , the specification you point to states that "User-specific executable files may be stored in `$HOME/.local/bin`"

If there is a need for a 1-liner that does not require root, the most "standard" would probably be:

```
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b "$HOME/.local/bin"
```

Also, as per the specification, distributions should ensure that `$HOME/.local/bin` should be in the user's PATH which would allow the user to run `syft` from where-ever.

To me, this is a non issue. I only got involved to prevent scary side-effects during the installation that would trip up the use-cases I care about, which is automatic installation as part of automated system provisioning and CI work-flows.

**Comment by DaveJarvis** [comment]
> To me, this is a non issue.

Likewise. I only mentioned it because I tried to follow the instructions, verbatim, and they didn't work. Similarly, `$HOME/.local/bin` doesn't necessarily exist, so the instructions you proposed won't work out of the box. Consider:

``` bash
$ uname -a
Linux host Debian10-vm01 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux
$ cd $HOME/.local/bin
bash: cd: /home/username/.local/bin: No such file or directory
```

Of course, the following instructions would work most of the time:

``` bash
mkdir -p $HOME/local/.bin
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b "$HOME/.local/bin"
```

**Comment by per-bohlin** [comment]
@kzantow , `$HOME/.local/bin` is not at all universal.

In my previous post I only mentioned it since @DaveJarvis referenced the XDG standard, used by some Linux distributions, and I wanted to clarify what the standard actually said, because I felt it was misrepresented. XDG is just one standard of many. Even within the Linux community it is not universal and often deviated from in some aspect by the various distributions who use it. It is even less universal in the context of macOS and Windows - platforms that the install-script supports as well.

Personally, I don't think the README need to be changed - nor the install script. It is perfectly fine as it is.
It is concise and understandable and can easily be applied by the user to work regardless of Windows, Linux or macOS.

After all the tool is aimed at system administrators and it must be assumed that a system administrator knows about file system permissions. I use Ubuntu as my Linux distro of choice and then you get used to using sudo all the time. If I had written the instructions myself I might have written it to include `sudo`after the pipe just out of habit. But in a manual context I think the current writing is more correct.

I apologies if my response comes across as snarky - that is not my intention. Not at all. I'm a big believer in community and there are no stupid questions - especially if you are a beginner.

If I got a vote in the issue, I would recommend not to change anything.

**Comment by tgerla** [comment]
As far as I am reading, the consensus here is that we leave the existing directions alone. I'll go ahead and close this issue but if anyone disagrees, please feel free to send us a pull request and we'll be happy to evaluate it. Thanks all!
