### ISSUE TITLE
Adding cli timeout argument

### ISSUE THREAD

**Issue by otanamip** [anchore/syft#1198]
**What would you like to be added**:
cli option that will be used to set scan timeout, so once timeout expires the scan will exists, output relevant log and return appropriate return code

**Why is this needed**:
Providing the ability to limit command execution time

**Additional context**:

**Comment by kzantow** [comment]
Hi @otanamip would you be able to just run Syft within the `timeout` command?

Are you seeing hangups in Syft? Could you provide any more information -- e.g. what images you might be scanning that are slow to download?

**Comment by otanamip** [comment]
Hi,

Yes, this is how it works for us, we are running syft and use its output
for running grype

Thanks,
Ohad

**Comment by kzantow** [comment]
Thanks for the response @otanamip -- so in that case, would we be able to close this issue, since a viable workaround exists?

**Comment by kzantow** [comment]
I'm closing this issue since there is a simple workaround and adding a timeout is not necessarily something we want to do. But please reopen if this is really causing you pain!
