### ISSUE TITLE
Support for Conan lockfiles

### ISSUE THREAD

**Issue by kzantow** [anchore/syft#1222]
Hi syft community,

conanfile.txt is a primary/declarative use of conan to only install dependencies.
Most conan users use conanfile.py, the imperative way to define dependencies, build and packaging.
Do you plan to support conanfile.py? For example using lock files (https://docs.conan.io/en/latest/versioning/lockfiles.html)?

Regards.

_Originally posted by @EstebanDugueperoux2 in https://github.com/anchore/syft/issues/1083#issuecomment-1253742862_

**Comment by kzantow** [comment]
Hi @EstebanDugueperoux2, I created this issue to from your comment on #1083. When looking at this feature, it states:
> This is an experimental feature subject to breaking changes in future releases.

Maybe it would be wise to wait until the feature has stabilized? I do not think we will prioritize this at least until the feature is stable, but do welcome PRs!

**Comment by spiffcs** [comment]
@EstebanDugueperoux2 with `conan.lock` support committed I believe we are now cataloging a superset of the packages that would be located in `conan.py`. Do you still see any value in parsing `conan.py` and including that info?

**Comment by tgerla** [comment]
We'll go ahead and close this ticket but please feel free to re-open if conan.py support is still important now that we have support for the lockfiles. Thanks!
