### ISSUE TITLE
Improve architecture of cataloging

### ISSUE THREAD

**Issue by luhring** [anchore/syft#123]
### Background

@wagoodman and I had a good call yesterday. We talked through the current architecture of Syft's Go code and how we implement cataloging, and we came to two conclusions — **1)** there are some improvements we can and should make, and **2)** the details of these improvements warrant further discussion.

### Concerns

The current architecture is sufficiently cataloging images and other data sources, but there are a lot of pieces to the puzzle. Some of the components and the relationships between them might not be required in a future iteration. Having a larger number of components and component relationships to keep track of increases the difficulty for new team members and community developers to understand the code base well enough to help maintain it.

Specific areas of focus:

1. The `GenericCataloger` is solving a problem that might not exist down the road. Specifically, the `controller.catalog` method passes a `scope.Resolver` to each ecosystem-specific cataloger, asking it for a list of files that the controller will soon retrieve from the original data source as a batch operation. This is unnecessary, since the ecosystem-specific cataloger need only return a means of finding matching files, not the files themselves. The `GenericCataloger`'s purpose is to unburden each ecosystem-specific cataloger from having to implement a solution to the problem of finding files using the `scope.Resolver`, but ecosystem-specific catalogers shouldn't have to actually find files in the first place. The associated machinations of pre-registering ecosystem-specific parsing functions with the `GenericCataloger` can also go away in the future.

1. The ecosystem-specific cataloger structs (e.g. `python.Cataloger`) might not need to exist as such, and we may be able to achieve a more **functional** (instead of stateful/OOP) solution for cataloging overall. When the above item is addressed, the `GenericCataloger` struct will have no state to store (and more importantly, will cease to add value) and thus can be removed. With this, the ecosystem-specific catalogers will also no longer have any associated state and thus can be removed. The functionality that underpins "cataloging" as we think of it is currently attached to "parsing functions". But "cataloging" is perhaps a better name for these operations — operations that peruse a set of files and return a set of discovered packages.

### Improved flow

It's important to recognize a necessary optimization to how any ecosystem-specific cataloging inspects files within the input data source, necessitated by the fact that the data source can be (and will usually be) a container image. Reading files in a container image is a hefty task, as it involves multiple TAR extractions and typically multiple layer inspections.

Thus, the ideal flow for delegating cataloging work to ecosystem-specific implementations is:

1. Interrogate all ecosystems for the knowledge of how to find all files in the data source needed by the ecosystem for subsequent cataloging.
1. In batch, using the knowledge accumulated in the previous step, pull all requested files out of the data source. (For now, we pull all files into memory; however, down the road we may be able to apply an abstraction like `io.Reader` and/or using OS pipes to avoid pulling whole files into memory upfront.)
1. Supply each ecosystem with the files it requested and use the ecosystem's logic for determining what packages are present.

Given this optimized flow layout, we can improve upon the current architecture by asking ecosystems for instructions on how to find files, instead of asking the ecosystems to find the files themselves. Then, during the cataloging step, we can provide a means for the ecosystem to read files, where this read operation occurs on an abstraction layer, where the underlying data is the subset of the original input data source where the contained files are only the files the ecosystem requested in the first place.

### Future considerations: a plugin system

Down the road, we may want to implement some kind of plugin system. Although it should impede iterative progress in the short-term, it may prove useful to keep in mind that some cataloging could one day be delegated to a plugin, i.e. outside of this project's code base.

**Comment by wagoodman** [comment]
I think this issue has gotten a little stale; a quick summary of the asks here being squared up with the current state of the world:

- (from 1) Problem: the catalogers are asking for files in batches, and each batch has a cost associated with the request. Todays state: this batching is no longer done and, based on stereoscope changes, the cost of fetching files has been drastically reduced. I think this obviates the suggestions in the "improved flow" section too.
- (from 1) Statement: the ecosystem-specific catalogers shouldn't have to actually find files in the first place ... pre-registering ecosystem-specific parsing functions with the GenericCataloger can also go away in the future. Todays state: every cataloger has been able to express it's needs in terms of stating which files it needs and registering a parser function, and in cases where this isn't needed implementing the cataloger interface directly has worked. I see the suggestion for a change, but I don't see the motivating reason.
- (from 2) Statement: we can use functions over objects to perform cataloging. Todays state: the cataloger interface is fairly well established and entrenched, changing this would be quite expensive and the value is not immediately clear.
- Add a plugin system -- this would be awesome! We have that tracked under https://github.com/anchore/syft/issues/17
