### ISSUE TITLE
Install fails on macOS with Xcode 14 Command Line Tools

### ISSUE THREAD

**Issue by mdivkovic-speech** [anchore/syft#1272]
**What happened**:
Runnig `brew install syft` gives the following error:

```
==> Installing syft from anchore/syft
Error: Your Command Line Tools are too outdated.
You should download the Command Line Tools for Xcode 13.4.
```

**What you expected to happen**:
It should just install, with the actual latest Xcode Command Line Tools, instead of asking to install the old ones.

**How to reproduce it (as minimally and precisely as possible)**:
Run the following on the environment specified in this ticket
`brew tap anchore/syft`
`brew install syft`

**Anything else we need to know?**:

**Environment**:
- Intel macbook pro 2019
- macOS 12.6
- Xcode and command line tools version 14.0.1 (14A400)

**Comment by tgerla** [comment]
I think this might be a Brew problem, not a Syft problem. @mdivkovic-speech, can you try installing something else from brew to see what happens? You can run "brew doctor" for a self-check.

**Comment by tgerla** [comment]
Hey @mdivkovic-speech, we'll go ahead and close this one out but please let us know if you continue to see issues or need help. Feel free to stop by the Slack for some live troubleshooting if you need. Thanks!
