### ISSUE TITLE
Include `go.sum` h1 digest information in checksums

### ISSUE THREAD

**Issue by kzantow** [anchore/syft#1277]
Go binary scanning now supports h1 digests being output in Syft, CycloneDX, and SPDX formats. However, we are not including this information if doing a _source_ scan. We should include h1 digests from `go.sum` files when processing a corresponding `go.mod` file.

_Originally noted by @deitch in https://github.com/anchore/syft/issues/1265#issuecomment-1285740475_

**Comment by deitch** [comment]
Works quite nicely, thank you.

Now if only I could solve the "missing checksums in go compiled binaries when built using `-vendor`" issue, but that isn't syft's issue; rather it is that go isn't including the data. syft happily would use it if it were there.
