### ISSUE TITLE
Cataloger filtering for Java is incorrectly scoped

### ISSUE THREAD

**Issue by bm402** [anchore/syft#1386]
When filtering catalogers in `.syft.yaml` and the Java cataloger is specified, the filtering logic includes both the Java and JavaScript catalogers when the SBOM generation is run.

For example, for the following config:
```
catalogers:
  - java
```

The cataloger filtering logic [here](https://github.com/anchore/syft/blob/247b054ab56f848c477495218754166272f470b5/syft/pkg/cataloger/cataloger.go#L127-L160) matches the `java-cataloger`, but it also matches the `javascript-package-cataloger` and the `javascript-lock-cataloger`.

Only the `java-cataloger` should be matched.

Syft version: [0.62.3](https://github.com/anchore/syft/releases/tag/v0.62.3)

**Comment by wagoodman** [comment]
As of Syft 1.0 this has been fixed 🎉  -- now there is more exact cataloger selection where if you put in:
```
catalogers:
- java
```

You'll see in the `-vv` verbose output:
```
  default-catalogers:
      - java
  select-catalogers: []
```
... so note that the javascript cataloger is not selected.
