### ISSUE TITLE
Multiple output files with templates

### ISSUE THREAD

**Issue by mihaiandreiratoiu** [anchore/syft#1409]
### Description
When running syft with multiple -o=template  -t=templateFile  parameters it takes the latest templateFile for every output file

### Example
Input syft alpine -o template=f1.json -t f1.template -o template=f2.json -t f2.template 
Output:
- f1.json with f2.template
- f2.json with f2.template

**Comment by kzantow** [comment]
As a workaround, if you need multiple templates, could you store the Syft JSON and then convert it?

```shell
syft alpine -o json > alpine.syft.json
syft convert alpine.syft.json -o template -t f1.template1 > f1.json
syft convert alpine.syft.json -o template -t f2.template1 > f2.json
```

**Comment by mihaiandreiratoiu** [comment]
Hey, sorry for the delayed response. Thanks for the tip. I've tried it but it seems that convert doesn't support the template? I get the ```2023/01/10 17:49:22 error during command execution: 1 error occurred:
        * no template file: please provide a template path``` even when using -t

**Comment by kzantow** [comment]
This sounds like something we should be able to fix for the convert command!

**Comment by mihaiandreiratoiu** [comment]
Great, thanks!
