### ISSUE TITLE
`json` and `generate` binaries installation

### ISSUE THREAD

**Issue by 0-wiz-0** [anchore/syft#1413]
When installing syft, it also installs `json` and `generate`.

I tried them out, and they look like they might only be needed for building syft - they generate static files for me.

If that is true, then they should not be installed.

If that is wrong, they need documentation, a usage, and better names because the names are ripe for conflict with other programs, perhaps syft-json and syft-generate.

**Comment by kzantow** [comment]
Hi @0-wiz-0 , how are you installing Syft? Using one of the supported installation methods described here: https://github.com/anchore/syft/#installation?

**Comment by 0-wiz-0** [comment]
Hm, sorry, no.
I packaged this for (pkgsrc)[www.pkgsrc.org] and used the default installation method there - `go install` - and packaging up everything that's installed into `GOPATH`.
If you think that's not worth supporting, feel free to close the issue.

**Comment by kzantow** [comment]
The problem with `go install` is that as far as I'm aware, we don't really have control over exactly what it does, I don't think we'd be able to change anything in this case -- we use `json` and `generate` from Syft, so we can't remove them as dependencies.

**Comment by wagoodman** [comment]
@0-wiz-0 what is the specific `go install` command you ran?

**Comment by 0-wiz-0** [comment]
I used the default we have in pkgsrc:
```
/usr/pkg/go119/bin/go install -v ./...
```
but perhaps the last argument can be improved? There's an override I could set in pkgsrc.

**Comment by 0-wiz-0** [comment]
```
/usr/pkg/go119/bin/go install -v ./cmd/syft
```
fixes the installation, so I'll just use that. Nothing to do here :)
