### ISSUE TITLE
version options interface issue

### ISSUE THREAD

**Issue by valllabh** [anchore/syft#1425]
should not it be "VersionOptions" instead of "PackageOptions"

https://github.com/anchore/syft/blob/e1e489a2849c8432781a7cb58b257fa935efa1cf/cmd/syft/cli/options/version.go#L12

**Comment by spiffcs** [comment]
^ Thanks for the issue @valllabh! Yes nice catch - we're happy to accept a PR fixing this if you'd like to contribute

**Comment by spiffcs** [comment]
Closed - was fixed as a quick boy scout in an unrelated PR. Thanks for the issue!
