### ISSUE TITLE
Modify project structure

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#146]
From https://anchorecommunity.slack.com/archives/C0190NF9TSM/p1597250962029500

I'm going through and adding documentation to syft now throughout the project structure... that combined with zach’s question yesterday regarding the location of `main.go` is making me consider a slightly different project layout. 

Today we have:
```
.
├── cmd           <--- all "syft" bin functionality
│   ├── cmd.go
│   ├── root.go
│   └── ...
├── syft          <--- the top "lib" package github.com/anchore/syft/syft
│   ├── cataloger
│   ├── distro
│   ├── event
│   ├── ...
│   └── lib.go    <--- our lib helper utilties
└── main.go       <--- the entrypoint, main package, and root package
```
I think it could be more advantageous to pivot to this instead:
```
 .
├── cmd 
│   ├── syft      <--- all "syft" bin functionality, main package #1
│   │   ├── cmd.go
│   │   ├── root.go
│   │   ├── main.go  <--- the entrypoint
│   │   └── ...
├── pkg
│   ├── cataloger
│   ├── distro
│   ├── event
│   └── ...
└── lib.go       <--- our lib helper utilities and root package
```

Advantages are:
- More closely follows what the community expects (purely convention, but not 100% uniformly adopted by the community) https://github.com/golang-standards/project-layout
- Allows for multiple binaries. This is not "needed", but would be very awkward to add later... so why corner ourselves now?
- The github.com/anchore/syft documentation on pkgs.go.dev would reflect the library functionality first and the binary as a nested package.
- Gets rid of the "stutter" in the import path (e.g. import github.com/anchore/syft/syft/... )

Disadvantages:
- `go run main.go`  -> `go run cmd/syft/main.go`  is somewhat annoying and relatively not as easy to discover
- We would have `github.com/anchore/syft/pkg/pkg`  for the existing `pkg`  package today, which looks pretty odd. (so while we're taking away several stuttering paths, we're adding one).

Something worth noting, since the lib helpers are in the root of the repo and there are no structs or functions defined in pkg (the new one) then the usage would still be the same (e.g. `syft.Catalog(...)`).

LOE should be pretty low given IDE refactoring tools (on the order of minutes).

**Comment by luhring** [comment]
(replayed from Slack)

My initial reaction is that this proposal is interesting, but not worth the change at this point in time.

I think the cost of changes like this for developers on the project is high. I see the logic behind the new design, but there's logic behind the current design, too. I don't see either of these logics being stronger than the other. Secondarily, I don't see this new layout as "what the community expects", at least not without some significant caveats.
