### ISSUE TITLE
Attestation with a private key

### ISSUE THREAD

**Issue by TomiOhl** [anchore/syft#1465]
**What happened**:
The readme still has the steps using the now removed `--key` flag.
Relevant parts:

- [Local private key support](https://github.com/anchore/syft/tree/v0.66.1#local-private-key-support)
- [Adding an SBOM to an image as an attestation using Syft](https://github.com/anchore/syft/tree/v0.66.1#adding-an-sbom-to-an-image-as-an-attestation-using-syft)

**What you expected to happen**:
The readme should be updated to reflect the breaking changes between v0.65.0 and v0.66.0. Trying to run the given command results in the following error: `error during command execution: unknown flag: --key`. I'd appreciate up-to-date steps.

**Anything else we need to know?**:
If the problem is on my side and the readme is correct, let me know and I'll provide more relevant feedback.

**Comment by ReDemoNBR** [comment]
I have similar issue in my CI environment that has the key stored in the secrets.
I'm looking for updated steps for the attestation.

If needed, I can be available to help

**Comment by tgerla** [comment]
Hi @TomiOhl and @ReDemoNBR, thanks for catching this. We will have an updated README and a new way to specify a private key in the next release of Syft. Stay tuned--for the time being you can go back to Syft 0.66.0. There's some additional information about the change here: https://github.com/anchore/syft/pull/1442

Hope this helps and sorry for the trouble!

**Comment by spiffcs** [comment]
@TomiOhl I've merged a new change that's unreleased but on the tip of main. Let me know if this is still behaving incorrectly to your expectations.

Tested with:
![Image](https://user-images.githubusercontent.com/32073428/214890274-94cb2117-3d30-4453-840b-ccf1779d92ab.png)
