### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#149]
Issue used to upload assets to github for reference in markdown files. (Do not delete this issue)

**Comment by wagoodman** [comment]
![syft-demo](https://user-images.githubusercontent.com/590471/90277200-2a253000-de33-11ea-893f-32c219eea11a.gif)

**Comment by luhring** [comment]
![syft-cropped-resized-0](https://user-images.githubusercontent.com/5199289/136842627-35daa3c8-e942-4de0-8487-9a3ca0894c8c.png)
