### ISSUE TITLE
Support for Luarocks

### ISSUE THREAD

**Issue by cjbischoff** [anchore/syft#1516]
**What would you like to be added**:

Requesting support for Luarocks (reading/understanding the format and outputting the modules and associated licensing)

**Why is this needed**:

Luarocks is a widely used package manager for Lua modules.

- https://github.com/luarocks/luarocks
- [2.7k stars](https://github.com/luarocks/luarocks/stargazers)
Watchers
- [ 101 watching](https://github.com/luarocks/luarocks/watchers)
Forks
- [ 410 forks](https://github.com/luarocks/luarocks/network/members)
- heavily utilized within NGNIX

**Additional context**:

**Comment by bhavyastar** [comment]
Hey, @kzantow I would like to work on this issue. Would you please assign this to me?

**Comment by kzantow** [comment]
Sure thing, @bhavyastar, done!

**Comment by jspeed-meyers** [comment]
@bhavyastar, any progress? I *might* be able to help with such a PR if you haven't already completed it :) 

cc @luhring

**Comment by cjbischoff** [comment]
Could we bump this and make it a priority?

**Comment by jspeed-meyers** [comment]
Sorry @willmurphyscode -- I think my window of opportunity passed :)

**Comment by willmurphyscode** [comment]
It looks like this was implemented but the issue never closed: https://github.com/anchore/syft/pull/2613
