### ISSUE TITLE
Include container information in SPDX

### ISSUE THREAD

**Issue by kzantow** [anchore/syft#1518]
**What would you like to be added**:
For container scans, SPDX output should contain a container package (with Primary Package Purpose set to `CONTAINER`), which is what the `SPDXRef-DOCUMENT DESCRIBES` relationship should point to.

Packages found within the container should have `CONTAINS` relationships from the container.

While investigating this, it would be good to understand if packages for _each layer within the container_ should be added in between. It seems both tern and the k8s bom tool generate SPDX from containers in this fashion: e.g. the SPDX relationships build a graph like: `container -> layer -> package`

**Why is this needed**:
More closely align with other tools and standards.

**Comment by kzantow** [comment]
Discussion resulted in this initial change will _not_ include layer information for a number of reasons, primarily:
* Syft by default uses a _squashed_ scope, so it will not necessarily include all the layer information
* Syft currently results in packages showing up _only_ in the last layer they are located in
* This makes dir/file scans result in the same document structure as container scans

**Comment by eliaslevy** [comment]
#1241 appears to be a duplicate of this issue.

**Comment by lumjjb** [comment]
👋, just checking in and wondering what the status of these discussions are if there are any updates!

**Comment by kzantow** [comment]
Closing this as a duplicate of #1241
