### ISSUE TITLE
Allow user-defined output formats

### ISSUE THREAD

**Issue by luhring** [anchore/syft#152]
Some CLI tools, including `docker`, provide a command line option for the user to specify exactly in what form they would like to receive the tool's output.

<img width="793" alt="Screen Shot 2020-08-18 at 3 30 33 PM" src="https://user-images.githubusercontent.com/5199289/90557039-e189b180-e167-11ea-82a8-62c1c0b32218.png">

This is incredibly useful, as it allows users to hand pick which fields they are interested in, and it allows users to consume data using formats that the developers haven't yet considered or implemented.

For example, users could get CSV data out of the tool without us having to create an explicit output option for CSV:

```
$ syft myimage --format '{{.Name}},{{.Version}},{{.Type}}`
adduser,3.118ubuntu2,deb
alsa-topology-conf,1.2.2-1,deb
alsa-ucm-conf,1.2.2-1ubuntu0.1,deb
apt,2.0.2ubuntu0.1,deb
...
```

Go makes this really easy with its built-in [template](https://golang.org/pkg/text/template/#pkg-overview) functionality. Given the user-specified template string and the struct from which the data comes, it's trivial to loop through structs in a collection and output text in the format the user wants.

**Note:** This output feature can apply equally to other tools besides syft, but this is just a place to start.

This issue is related to https://github.com/anchore/grype/issues/42, but takes a different, more generalized approach. Both approaches might be desired, and they wouldn't inherently conflict with each other.

**Comment by nicosto** [comment]
Hi,
This will be really useful to have this to report to application that doesn't support cyclondx/spdx.

**Comment by luhring** [comment]
I'd like us to move forward on this now. But one update from the description — let's make sure to implement this functionality so that **it's exactly the same experience for users as Grype's templating functionality**, which is documented here: https://github.com/anchore/grype#using-templates

**Comment by jonasagx** [comment]
Nice, I can take a look at it.
