### ISSUE TITLE
apk packages with simplified license show NOASSERTION

### ISSUE THREAD

**Issue by deitch** [anchore/syft#1529]
**Please provide a set of steps on how to reproduce the issue**

syft reports the license concluded as `NOASSERTION` when a license that may not be complete but is nonetheless intelligible is found.

For example, use the following dockerfile:

```dockerfile
FROM alpine:3.17
RUN apk add openssh-client-common
```

Running syft on the above will give the following output for the package `openssh-client-common` (in spdx-json format):

```json
  {
   "name": "openssh-client-common",
   "SPDXID": "SPDXRef-Package-apk-openssh-client-common-931d8f7c42c54694",
   "versionInfo": "9.1_p1-r1",
   "originator": "Person: Natanael Copa \u003cncopa@alpinelinux.org\u003e",
   "downloadLocation": "https://www.openssh.com/portable.html",
   "sourceInfo": "acquired package info from APK DB: lib/apk/db/installed",
   "licenseConcluded": "NOASSERTION",
   "licenseDeclared": "NOASSERTION",
   "copyrightText": "NOASSERTION",
   "description": "OpenBSD's SSH client common files",
```

The relevant part of `/lib/apk/db/installed` is:

```
C:Q1YcVPyM0QbevnRbzdyPGn4hQmAjk=
P:openssh-client-common
V:9.1_p1-r1
A:aarch64
S:835516
I:3186688
T:OpenBSD's SSH client common files
U:https://www.openssh.com/portable.html
L:BSD
```

I stepped through syft's code, and found that it carried the `"BSD"` license in the `Licenses` field all the way through until [license.ID()](https://github.com/anchore/syft/blob/fb388c0f2525e0e4af8399ba44e5f1fe5b9de9ae/internal/spdxlicense/license.go#L17), where it lowercases it ("BSD" -> "bsd") and then checks in the table [here](https://github.com/anchore/syft/blob/fb388c0f2525e0e4af8399ba44e5f1fe5b9de9ae/internal/spdxlicense/license_list.go#L8). The table has lots of variants of BSD with versions and such, but nothing that is just plain "bsd".

I get that the license itself really _should_ be "BSD with a version". My question is how we should support this in the real world, where these exist. Perhaps there should be an option `--accept-unknown-licenses=true`, to say, "if I do not recognize the license, instead of `NOASSERTION`, I will show the text as is, maybe with some warning".

For what it is worth, the `APKBUILD` with license is [here](https://git.alpinelinux.org/aports/tree/main/openssh/APKBUILD?h=3.17-stable).

Note: may be related to #933 ; I chose to open a new issue as I have as simple replication and am focused on one particular problem, rather than the "license output differs between files". The cause, I believe, is the same.

**Comment by kzantow** [comment]
It looks like for SPDX, we could probably put these licenses in the [other licenses section](https://spdx.github.io/spdx-spec/v2.3/other-licensing-information-detected/#102-extracted-text-field) and link these with `LicenseRef-<something>`, what do you think?

**Comment by deitch** [comment]
Yeah I think that would work. It's the "NOASSERTION" when we know a license is there that is surprising.

**Comment by kzantow** [comment]
I've added this to the backlog, it seems like a worthwhile addition 👍

**Comment by deitch** [comment]
What can I do to help move it along?

**Comment by kzantow** [comment]
PRs are always welcome -- if you had time to attend [the community meeting tomorrow](https://calendar.google.com/calendar/u/0/r?cid=Y182OTM4dGt0MjRtajI0NnNzOThiaGtnM29qNEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) we could always discuss it ([add to the agenda here](https://docs.google.com/document/d/1ZtSAa6fj2a6KRWviTn3WoJm09edvrNUp4Iz_dOjjyY8/edit?usp=sharing)).
