### ISSUE TITLE
Extend cycloneDX presenters with syft-specific values

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#154]
The CycloneDX spec allows for user-defined values to be added to most select sections. We should extend each component to report out grype-specific information. Similar to our json output, but embedded in each component section:

```xml
<syft:metadata version="1">
    <catalogers>
        <cataloger>python-cataloger</cataloger>
    </catalogers>
    <locations>
        <location>
            <path>/somewhere/to-path.json</path>
            <layer-index>1</layer-index>
        </location>
    </locations>
</syft:metadata>
```

**Comment by coderpatros** [comment]
In v1.3 of the spec we have added generic properties for metadata, components and services 

They might not suit for this. But if they do, it would make converting between XML, JSON and protobuf formats easier.

**Comment by samj1912** [comment]
Some of this is added in #710
