### ISSUE TITLE
Support for multiple image refs of same sha in OCI layout

### ISSUE THREAD

**Issue by saisatishkarra** [anchore/syft#1544]
**What would you like to be added**:
1. Syft should be able to scan and detect multiple image refs of mediaType `application/vnd.oci.image.index.v1+json` for the same sha in single oci-layout

**Why is this needed**:
Needed to avoid scanning twice for images with the same sha and different tag

**Additional context**:
<img width="738" alt="Screen Shot 2023-02-07 at 11 43 05 AM" src="https://user-images.githubusercontent.com/29549979/217323402-06c23d23-04cc-4b7b-bf23-125d3249a19f.png">

**Comment by tgerla** [comment]
Hi @saisatishkarra, thanks for filing the issue. We have a couple of questions over here. Usually these OCI manifests are used, for instance, to list different architectures of the same image (which would have different SHAs), so we are a little bit confused as to why you would have a manifest with two instances of the same exact image (same SHA). Can you provide a few more details about where this manifest came from, what build tool created it, or how to create it, and we can take a closer look? Thanks!

**Comment by saisatishkarra** [comment]
This index manifest is produced when using a `https://github.com/docker/build-push-action` with multiple tags (list/csv) for a single architecture of the same image. Each tag is considered to produce a separate manifest within the index.json with differing `io.containerd.image.name` pointing to tag variants  in the `annotations` for same image sha

**Comment by spiffcs** [comment]
There is a potential enhancement we can make in https://github.com/anchore/stereoscope where we check the manifest list, and if all of the digest are equal, we can proceed with the scan. @wagoodman if we find that this is only one single image we can just pick one and go right? 

I've added this to the backlog as a stereoscope enhancement while we wait for a 2nd from @wagoodman

**Comment by saisatishkarra** [comment]
@spiffcs Is there an update on this?

**Comment by spiffcs** [comment]
@saisatishkarra just filed a PR in stereoscope to address this.

- https://github.com/anchore/stereoscope/pull/202 -

Apologies for the long response time here!

**Comment by spiffcs** [comment]
This PR has been merged so I'll look to get this brought into syft for the next release
