### ISSUE TITLE
Extend CycloneDX presenter with dependency graph

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#155]
#67 brings about the Cyclone DX presenter. We should extend out select catalogers to capture inter-dependencies for each package discovered. This data can better be leveraged to add the Dependency Graph Extension to the Cyclone DX presenter (https://cyclonedx.org/ext/dependency-graph)

**Comment by samj1912** [comment]
Fixed by #706

**Comment by luhring** [comment]
Should we close this now?

**Comment by samj1912** [comment]
I believe so, merged in https://github.com/anchore/syft/pull/768
