### ISSUE TITLE
Syft spdx sbom lists package as a dependency of itself

### ISSUE THREAD

**Issue by aniruth37** [anchore/syft#1581]
**What happened**:
Used syft 0.72.0 on the image `cgr.dev/chainguard/wolfi-base` to generate SPDX-SBOM.
The relationships section of SBOM contains circular dependency i.e. a package is listed as a dependency of itself.

Excerpt of output
```
  {
   "spdxElementId": "SPDXRef-Package-apk-glibc-e31fd36d27edb88e",
   "relatedSpdxElement": "SPDXRef-Package-apk-glibc-e31fd36d27edb88e",
   "relationshipType": "DEPENDENCY_OF"
  },
  {
   "spdxElementId": "SPDXRef-Package-apk-glibc-e31fd36d27edb88e",
   "relatedSpdxElement": "SPDXRef-Package-apk-glibc-e31fd36d27edb88e",
   "relationshipType": "DEPENDENCY_OF"
  },
```

Similar issue is seen for the image - `cgr.dev/chainguard/python`

**What you expected to happen**:
A package should not be dependent on itself and there should not be any circular dependencies.

**Steps to reproduce the issue**:
`syft cgr.dev/chainguard/wolfi-base -o spdx-json=wolfi-syft.spdx.json`

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
```
Application:        syft
Version:            0.72.0
JsonSchemaVersion:  6.2.0
BuildDate:          2023-02-16T16:09:46Z
GitCommit:          2642a3616170ccbda9d8c8cb4f4a6b0fd5c63da9
GitDescription:     v0.72.0
Platform:           linux/amd64
GoVersion:          go1.19.5
Compiler:           gc
```

- OS (e.g: `cat /etc/os-release` or similar):

**Comment by WhyJee** [comment]
Silly question but could it be related to a bug in the glibc package ?
```
# apk info -r glibc
glibc-2.37-r0 is required by:
glibc-2.37-r0
...
```

See also:
```
# apk info -q -R glibc
so:libc.so.6
so:libm.so.6
...

```
# apk info -q -P glibc
so:libc.so.6=6
so:libm.so.6=6
...
```

Thus strictly speaking this dependency is true : glibc depends on glibc.
Now if we compare with another type of image which also contains glibc and has the same provide/require info, Syft is not generating the "DEPENDENCY_OF" links.
Thus combination of:
* package require info
* syft package analyzer: this type of link is only reported for APK

**Comment by kzantow** [comment]
@WhyJee I think your assessment is correct (I've validated this myself against the image referenced): Syft is only surfacing the data it finds. I don't think we want to make a change at this point, because it would be against the general philosophy of Syft, which is to surface findings rather than interpreting them. If this is causing huge problems, we could possibly revisit it, but for now I'm going to close it as working correctly.
