### ISSUE TITLE
Encountering "cycle during symlink resolution" with syft version 0.71.0 onwards

### ISSUE THREAD

**Issue by hkadakia** [anchore/syft#1586]
**What happened**:
When running syft to generate an SBOM on an ubuntu image, I encountered the below error.

```
No packages discovered
2023/02/17 12:20:38 error during command execution: 1 error occurred:
	* failed to find binaries by mime types: unable to get ref for path="/usr/local/bin/ksh": cycle during symlink resolution
```

**What you expected to happen**:
Syft should run successfully and generate the SBOM in the output format specified.

**Steps to reproduce the issue**:
```
echo "FROM ubuntu:latest
RUN apt-get update && apt-get install ksh93u+m && ln -s /bin/ksh /usr/local/bin/ksh" | docker build -t syft-symlink-bug:latest - && syft -vvv syft-symlink-bug:latest
```

Verbose mode output: https://gist.github.com/hkadakia/973e53dfd3f2358374b7d77b2d623907

**Anything else we need to know?**:
This issue was introduced in version 0.71.0 onwards.

**Environment**:
- Output of `syft version`: 
```
(oath_tools) ➜  sboms syft version
Application:        syft
Version:            0.72.0
JsonSchemaVersion:  6.2.0
BuildDate:          2023-02-16T15:22:43Z
GitCommit:          2642a3616170ccbda9d8c8cb4f4a6b0fd5c63da9
GitDescription:     [not provided]
Platform:           darwin/amd64
GoVersion:          go1.19.6
Compiler:           gc
```
- OS (e.g: `cat /etc/os-release` or similar):
```
(oath_tools) ➜  sboms sw_vers
ProductName:	macOS
ProductVersion:	12.6.3
```

**Comment by mathrock** [comment]
I believe this may be a regression in behaviour introduced by PR #1510.

**Comment by wagoodman** [comment]
Thanks for reporting! Fixed in https://github.com/anchore/syft/pull/1604 and will be in the upcoming v0.73.0 release.

Also TIL you can pipe Dockerfile contents into `docker build` -- nice trick! 🙌
