### ISSUE TITLE
Install script not working with newest release

### ISSUE THREAD

**Issue by Ju-Ru** [anchore/syft#1594]
**What happened**:
I tried to install Syft using the command from the README:
`curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b ./`

`[error] received HTTP status=000 for url='https://github.com/anchore/syft/releases/latest' `
`[error] unable to find tag='' `
`[error] do not specify a version or select a valid version from https://github.com/anchore/syft/releases`

**What you expected to happen**:
Download and installation of latest release.

**Steps to reproduce the issue**:
Run above command. 

**Anything else we need to know?**:
It worked before the current release.

**Environment**:
- Output of `syft version`: -
- OS (e.g: `cat /etc/os-release` or similar): RHEL 9.1

**Comment by tgerla** [comment]
I just tried this myself and it worked fine, can you try again? Maybe it is an intermittent network problem. Thanks,

**Comment by tgerla** [comment]
We'll close this one but let us know if you have more trouble. Thanks.
