### ISSUE TITLE
Why container image @sha256 is not supported?

### ISSUE THREAD

**Issue by evanchaoli** [anchore/syft#1652]
**What would you like to be added**:

When specifying a container image, seems that only image is tag is support:

```
$ syft image:tag
```

`tag` doesn't exactly identify an image, because a tag can be overwritten. In some system, to ensure the image is used, we only use image@sha256, however `syft` doesn't that form:

```
$ syft image@sha256 # not supported
```

**Why is this needed**:

A image `tag` doesn't exactly identify an image, because a tag can be overwritten. In some system, to ensure the image is used, we only use image@sha256.

**Additional context**:

**Comment by kzantow** [comment]
This does work in Syft, but you need to provide the actual hash, e.g.:
```
syft python@sha256:0b106e1d2bf485c2a41474bc9cd5103e9eea4e179f40f10741b53b127059221e
```
You can optionally specify a tag, too:
```
python:3.11-slim@sha256:0b106e1d2bf485c2a41474bc9cd5103e9eea4e179f40f10741b53b127059221e
```

**Comment by evanchaoli** [comment]
Thanks for the answer.
