### ISSUE TITLE
Syft SBOMs support dependency hierarchies. 

### ISSUE THREAD

**Issue by bardenstein** [anchore/syft#1674]
**What would you like to be added**:
When I generate SBOMs from Syft (in either CycloneDX or SPDX), the resulting SBOM files don't show the dependency hierarchies (i.e. the tree relationships between libraries) that other generators do (like the open-sbom-generator). 

I want/need to be able to see, for a given vulnerable library, how it was introduced into an asset.

Ex:
- Dependency 1 (has a CVE)
- - introduced by dep 2
- - - introduced by dep 3
- - - - introduced by dep 4, which is a top-level library / root node. 

**Why is this needed**:
This allows me to tell developers what libraries they specifically need to upgrade/replace in order to remediate vulns or other issues introduced. 

**Additional context**:

**Comment by eliaslevy** [comment]
This is a duplicate of #572.

**Comment by wagoodman** [comment]
Indeed it's a dup -- I'll close this one. Shout out if there is extra context that is not capture in the original issue.
