### ISSUE TITLE
Error messaging when using podman but daemon is not available is unclear

### ISSUE THREAD

**Issue by vargenau** [anchore/syft#1687]
**What happened**:

With Docker:
```
syft docker:apache/airflow:2.3.0b1-python3.10 --scope all-layers -o spdx-tag-value > airflow-syft-docker.spdx
 ✔ Loaded image            
 ✔ Parsed image            
 ✔ Cataloged packages      [1097 packages]
 ✔ Cataloged file metadata 
 ✔ Cataloged file digests  
```

With Podman:
```
syft podman:apache/airflow:2.3.0b1-python3.10 --scope all-layers -o spdx-tag-value > airflow-syft-podman.spdx
2023/03/22 10:38:10 error during command execution: 1 error occurred:
	* failed to construct source from user input "podman:apache/airflow:2.3.0b1-python3.10": could not fetch image "apache/airflow:2.3.0b1-python3.10": no host address
```

**What you expected to happen**:

Command with Podman should succeed.

**Steps to reproduce the issue**:

See above

**Environment**:
- Output of `syft version`:
```
syft version
Application:        syft
Version:            0.75.0
JsonSchemaVersion:  7.0.1
BuildDate:          2023-03-13T17:50:56Z
GitCommit:          cc0a376aba43e7f9c5fe66320643f72088533838
GitDescription:     v0.75.0
Platform:           linux/amd64
GoVersion:          go1.19.6
Compiler:           gc
```

- OS (e.g: `cat /etc/os-release` or similar):
```
cat /etc/os-release
PRETTY_NAME="Ubuntu 22.10"
NAME="Ubuntu"
VERSION_ID="22.10"
VERSION="22.10 (Kinetic Kudu)"
VERSION_CODENAME=kinetic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=kinetic
LOGO=ubuntu-logo
```

**Comment by kzantow** [comment]
Syft currently only supports podman when it is run as a daemon. Is this the configuration you are using? If not, you should be able to get it set up following the docs here: https://github.com/containers/podman/blob/main/contrib/systemd/README.md

**Comment by vargenau** [comment]
Thank you for your answer.
I will check.
Is this restriction documented somewhere?
Also, the error message could be more explicit.

**Comment by kzantow** [comment]
Specifically, the docs say: 
> use images from the Podman daemon

I agree, the error message could be improved -- will add to the backlog for this.

**Comment by kzantow** [comment]
Syft currently surfaces all source errors when no source is returned as part of: https://github.com/anchore/syft/pull/2610, including an indication from podman, such as:
```
  - podman: podman not available: making http client: connection to bastion host="localhost:58904" failed: dial tcp [::1]:58904: connect: connection refused
```

**Comment by cx-harshjeet-patil** [comment]
@kzantow I am new to Syft . Can you please tell me "Syft currently only supports podman when it is run as a daemon" it still the case or it has started supporting docker?
