### ISSUE TITLE
co.elastic.clients:elasticsearch-java is not reported, even when the corresponding jar is present

### ISSUE THREAD

**Issue by sundarsubburaj** [anchore/syft#1720]
**What happened**:
The syft tool successfully locates the uber jar, and successfully identifies many packages within it. There is one package though, co.elastic.clients:elasticsearch-java, that is doesn't report on. I've confirm the full elasticsearch-java jar is present and expanded into the uber jar just like the others.

**Comment by kzantow** [comment]
Thanks for the report @sundarsubburaj. Is there a public image or uber jar file that you could point to exhibiting this behavior? If not, could you provide a script to create one?

**Comment by sundarsubburaj** [comment]
Hi @kzantow, 

Below is the mvn repository link for the concerned jar (Elasticsearch Java API client 7.17.9). The jar can be downloaded from the link. Please review.

https://mvnrepository.com/artifact/co.elastic.clients/elasticsearch-java/7.17.9

Thanks.

**Comment by tgerla** [comment]
Hi @sundarsubburaj, we took a look at the co.elastic.clients:elasticsearch-java jar and unfortunately there is no metadata in that jar that allows us to identify it based on what we are looking for today: package name, package version, implementation name, etc. Unfortunately that means Syft won't be able to list it in the resulting SBOM.

You might want to consider filing an issue with Elastic to have them build this jar in such a way that would include the metadata we need for identification. Happy to provide them additional details about our identification mechanisms if you choose to do that. Hope this helps!
