### ISSUE TITLE
Install.sh doesn't work when adding `-k` to curl command due to self-signed cert

### ISSUE THREAD

**Issue by thommelutten** [anchore/syft#1739]
**What happend**
Running `curl -k -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin` when having a self-signed certificate results in the following error

```
[error] received HTTP status=000 for url='https://github.com/anchore/syft/releases/latest'
[error] unable to find tag=''
[error] do not specify a version or select a valid version from https://github.com/anchore/syft/releases
```

**What you expected to happen**:
Syft would be downloaded and installed.

**Anything else we need to know?**:
The error is due to the self-signed certificate, and while I don't want to advocate for a `--insecure` flag, the error could be more transparent.

**Comment by Natediesel7** [comment]
Same error here. How to address?

**Comment by spiffcs** [comment]
👋 Thanks for filing the issue @thommelutten! - 

@Natediesel7 - if you're downloading via a proxy or some other configuration you might need to modify this line in the install.sh:
https://github.com/anchore/syft/blob/main/install.sh#L207

Adding `-k` there should fix things up for you

There's also the option of downloading the asset directly from the release page:
https://github.com/anchore/syft/releases

We'll take a look at trying to make the error more transparent or give a workaround for those who need to bypass SSL verification.

**Comment by djbazuka01** [comment]
Was this problem ever resolved as I am facing the same issue and don't know how to resolve ?. I am newbie and don't really know how to install asset directly from GitHub and use that to install into Linux.

**Comment by JohnCalin** [comment]
> 👋 Thanks for filing the issue @thommelutten! -
> 
> @Natediesel7 - if you're downloading via a proxy or some other configuration you might need to modify this line in the install.sh: https://github.com/anchore/syft/blob/main/install.sh#L207
> 
> Adding `-k` there should fix things up for you
> 
> There's also the option of downloading the asset directly from the release page: https://github.com/anchore/syft/releases
> 
> We'll take a look at trying to make the error more transparent or give a workaround for those who need to bypass SSL verification.

The install script always re-downloads itself (to be sure to run the correct installer based on which version is being installed).
If you do make manual changes (for example, adding `-k` to your curl commands) run it with
```
DOWNLOAD_TAG_INSTALL_SCRIPT=false ./install.sh
```
to prevent re-download.

**Comment by willmurphyscode** [comment]
Is this still an issue for anyone? If so, can you help me understand why you would want to pass `-k` to an install script? The install script works with GitHub specifically, and so should never trust a self-signed cert.

**Comment by thommelutten** [comment]
@willmurphyscode It is no longer relevant for me, so it can be closed from my perspective.
