### ISSUE TITLE
[question]Does syft recognize project relationships introduced in source form?

### ISSUE THREAD

**Issue by laiyoufafa** [anchore/syft#1826]
If project A introduces project B in source form, and project B introduces project C in source form, can syft recognize that A includes B includes C, and if so, what should I do?

**Comment by kzantow** [comment]
Syft currently does not surface relationships from most catalogers, although it has the ability to. At present, I believe only the APK cataloger is actually surfacing package relationships but there are definitely plans to improve this. One thing to note is many catalogers work by scanning a lockfile of some sort, which often does not have the dependency relationships, only a flat list of all the packages included, so gathering this information might be a little tricky in some cases.

**Comment by tgerla** [comment]
Hi @laiyoufafa, hopefully @kzantow has answered your question. I'll go ahead and close this issue but if you need anything else feel free to open another one, or if applicable, re-open this one. Thanks!
