### ISSUE TITLE
Rename Location virtualPath to accessPath

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#1835]
Today we have the concept of a location of a RealPath (absolute path to a file where there are no symlinks, which is canonical) and a VirtualPath (what path we requested to get to this RealPath). Given that the virtual path is all about how a path was accessed, a more accurate name would be `AccessPath`. Making this change would break most consumers that are depending on this value, and duplicating the field temporarily seems like overkill. However, we could as a hold over period allow for an application configuration where we allow for the old expression in the JSON output only.

**Comment by willmurphyscode** [comment]
> duplicating the field temporarily seems like overkill

Can you help me understand why it seems like overkill?

**Comment by wagoodman** [comment]
Mainly because there may be several location objects in an SBOM, and paths can get rather lengthy. Duplicating this field would mean that we could be making SBOMs noticeably larger. Another approach is to allow for configuration for the format to opt into the legacy approach (e.g. `SYFT_JSON_LEGACY=true`) as in https://github.com/anchore/syft/pull/1983
