### ISSUE TITLE
symlinks within a scanned directory tree are parsed outside the tree, failing if target does not exist

### ISSUE THREAD

**Issue by deitch** [anchore/syft#1860]
**What happened**:

Here is a simple test case:

```sh
$ mkdir /tmp/syft
$ touch /tmp/syft/a /tmp/syft/b
$ ln -s /foo/bar /tmp/syft/link
```

The `link` can point to anywhere, as long as it both starts with `/` and does not exist.

The error you get will be:

```
2023/06/01 13:43:01 error during command execution: 1 error occurred:
        * unable to determine resolver while cataloging packages: unable to create directory resolver: unable to index filesystem path="/foo/bar": lstat /foo: no such file or directory
```

**What you expected to happen**:

Ideally, it would recognize that `/tmp/syft/link` points outside of the scanned directory and not follow it. At minimal, it should handle it and not fail.

**Steps to reproduce the issue**:

See above.

**Anything else we need to know?**:

The commit that caused the issue is [6afbffce](https://github.com/anchore/syft/commit/6afbffce283dd3f3f0372dc90c034f061b03dc5f)

**Root cause analysis**

Coming in an edit

**Comment by deitch** [comment]
## Root cause analysis

When it walks through the directory tree in [directory_indexer.go](https://github.com/anchore/syft/blob/main/syft/internal/fileresolver/directory_indexer.go), and specifically [indexTree](https://github.com/anchore/syft/blob/main/syft/internal/fileresolver/directory_indexer.go#L98), it sees the symlink and parses the target [here in indexPath()](https://github.com/anchore/syft/blob/main/syft/internal/fileresolver/directory_indexer.go#L143).

It then recognizes that this is a new root (target starts with `/`), and adds it to the roots, which are returned to the caller [indexAllRoots()](https://github.com/anchore/syft/blob/main/syft/internal/fileresolver/directory_indexer.go#L61).

It then tries to index this new root, in the above example `/foo/bar`, bu calling `indexTree()` again.

Prior to the above commit, it would try to walk the new root, see nothing, and just keep going.

The above commit adds [this section](https://github.com/anchore/syft/blob/main/syft/internal/fileresolver/directory_indexer.go#L123-L126) which checks of the root is a real path. Overall, that is a good thing for `indexTree()`, but in this case, it cannot stat `/foo` and then just fails, returning the error.

## Recommendations

It is my opinion that we should not be following symlinks at all. Either way, it either hinders or doesn't help:

* if the target of the link is _inside_ the directory we are parsing, then we will get to it anyways
* if the target of the directory is _outside_ the directory we are parsing, then it should be treated as out of scope and ignored

However, if we still desire to have directory parsing, then we should ignore symlinks whose target cannot be found.

A somewhat better alternative (more correctly, addition) would be to have an option either to ignore symlinks (thus fitting with my proposed logic above) or follow them.

Either way, I think "this symlink points nowhere" is a good reason to skip it. The fix for that is fairly simple as well.

When we parse the symlink, [here](https://github.com/anchore/syft/blob/main/syft/internal/fileresolver/directory_indexer.go#L373), check if the target exists. If not, do not return the target.

```go
	if _, err := os.Stat(targetAbsPath); err != nil && errors.Is(err, os.ErrNotExist) {
            targetAbsPath = ""
        }
	return targetAbsPath, nil
```

**Comment by jpalermo** [comment]
We're running v0.83.1 which includes the fix but we're getting the errors still:
```
* unable to determine resolver while cataloging packages: unable to create directory resolver: unable to index filesystem path="/tmp/tmp.283DGJmbvR/dev/fd/1": unable to index branch="/tmp/tmp.283DGJmbvR/dev/fd/1": lstat /proc/694/fd/pipe:[801872502]: no such file or directory
```
The errors exist when running with v0.83.0 and v0.83.1 but do not exist on v0.82.0

In our case, we're mounting an image and scanning it, so the `/dev/fd/1` symlink is pointing outside of the mount point to somewhere under `/`.

CC @selzoc

**Comment by spiffcs** [comment]
Reopened because of a new report from @jpalermo - @anchore/tools

**Comment by jpalermo** [comment]
For anybody else running into this problem. We've worked around it by scanning the mounted image using `chroot` to keep the symlinks correct.

**Comment by kzantow** [comment]
I believe this issue has been resolved by the addition of the `--base-path` flag and related config option by https://github.com/anchore/syft/pull/1867 I'm copying the explanation from https://github.com/anchore/syft/issues/1359#issuecomment-4183444970 if someone lands here

### if you are scanning a source code type filesystem, you probably DO NOT want to set base-path

For example you if you have:

```
/src
/src/repo # symlink to /repo
/repo
```

If you scan `/src`, when resolving the `/src/repo` you want the default behavior, which would resolve absolute paths relative to the root of the filesystem, not the scanned directory. If you set `base-path` in this scenario to `/src`, the symlink would not resolve properly.

### if you are scanning a directory that should be considered a standalone filesystem, you DO want to set the base-path

Let's say you extract `my-vm.tar` to `/tmp/extracted` and you scan this directory, in this case, you _do_ want symlinks to resolve relative to the scan root of `/tmp/extracted`, so you should set `--base-path /tmp/extracted`, matching the scanned directory.

Syft always resolves absolute paths internally, so the way these symlinks get resolved necessarily has to account for the aforementioned scenarios.

Please let me know if I've misunderstood the problem, hopefully understanding how `--base-path` works will lead you to the right configuration for your needs.
