### ISSUE TITLE
Multiple instances of the same package

### ISSUE THREAD

**Issue by vargenau** [anchore/syft#1881]
**What happened**:

```
syft docker:bitnami/mongodb:6.0.6-debian-11-r0 --scope all-layers -o spdx-tag-value@2.2 > mongodb-6.0.6-debian-11-r0.spdx
```
[mongodb-6.0.6-debian-11-r0.spdx.txt](https://github.com/anchore/syft/files/11771285/mongodb-6.0.6-debian-11-r0.spdx.txt)

Many packages are reported multiple times.

For example, package `pkg:golang/golang.org/x/text@v0.3.7` is reported 9 times.

```
##### Package: golang.org/x/text

PackageName: golang.org/x/text
SPDXID: SPDXRef-Package-go-module-golang.org-x-text-1224fca30eac5afd
PackageVersion: v0.3.7
PackageDownloadLocation: NOASSERTION
FilesAnalyzed: false
PackageSourceInfo: acquired package info from go module information: /opt/bitnami/mongodb/bin/mongodump
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: NOASSERTION
PackageCopyrightText: NOASSERTION
ExternalRef: SECURITY cpe23Type cpe:2.3:a:golang:x\/text:v0.3.7:*:*:*:*:*:*:*
ExternalRef: PACKAGE-MANAGER purl pkg:golang/golang.org/x/text@v0.3.7
```

Content is the same in 9 instances, except the `SPDXID`.

**What you expected to happen**:

I would expect that packages are reported only once (same name, same version, same purl).

**Steps to reproduce the issue**:

See command line above.

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: syft 0.83.1
- OS (e.g: `cat /etc/os-release` or similar): Ubuntu 22.10

**Comment by kzantow** [comment]
Hi @vargenau -- if you run across instances like this, I would suggest looking at the Syft JSON output, it has a lot more information. I can see for the `golang.org/x/text` package a few entries:

```json
  {
   "id": "d359038d99f64aec",
   "name": "golang.org/x/text",
   "version": "v0.3.7",
   "type": "go-module",
   "foundBy": "sbom-cataloger",
   "locations": [ 
    {
     "path": "/opt/bitnami/mongodb/.spdx-mongodb.spdx",
...
```

```json
  {
   "id": "a9889aeaf8a940d9",
   "name": "golang.org/x/text",
   "version": "v0.3.7",
   "type": "go-module",
   "foundBy": "go-module-binary-cataloger",
   "locations": [
    {
     "path": "/opt/bitnami/mongodb/bin/bsondump",

...
```

```json
  {
   "id": "1224fca30eac5afd",
   "name": "golang.org/x/text",
   "version": "v0.3.7",
   "type": "go-module",
   "foundBy": "go-module-binary-cataloger",
   "locations": [
    {
     "path": "/opt/bitnami/mongodb/bin/mongodump",
...
```

I've omitted the remainder, but they have similar differences:

* one entry was found by the `sbom-cataloger`, which means an SBOM was present in the image and scanned
* the `path` is different for the entries -- e.g. there are multiple binaries which show that this package is present in multiple different locations

In the SPDX document, you _should_ see relationships from the packages to the corresponding files from which they were identified, e.g.:
```json
  {
   "spdxElementId": "SPDXRef-Package-go-module-golang.org-x-text-a9889aeaf8a940d9",
   "relatedSpdxElement": "SPDXRef-File-opt-bitnami-mongodb-bin-bsondump-b7ec9cd3c4301521",
   "relationshipType": "OTHER",
   "comment": "evident-by: indicates the package's existence is evident by the given file"
  },
...
  {
   "fileName": "/opt/bitnami/mongodb/bin/bsondump",
   "SPDXID": "SPDXRef-File-opt-bitnami-mongodb-bin-bsondump-b7ec9cd3c4301521",
   "checksums": [
    {
     "algorithm": "SHA1",
     "checksumValue": "0000000000000000000000000000000000000000"
    }
   ],
   "licenseConcluded": "NOASSERTION",
   "copyrightText": "",
   "comment": "layerID: sha256:cfeba68de0ff71ebff49d255509af456f9e26086e2e5b596cc15464607bc8ddf"
  },
```

Is there some other behavior you are expecting here?

**Comment by tgerla** [comment]
We'll go ahead and close this issue but please feel free to let us know if you have more questions. Thanks.

**Comment by spiffcs** [comment]
Linking this on #931 as an additional case to potentially handle

**Comment by vargenau** [comment]
@kzantow @spiffcs @tgerla 
Hi,
Thank you for your comments and sorry for answering so late.

I am using SPDX output from Syft, as we use SPDX as input for our internal tool.
So the Syft JSON output is useful to understand why there are multiple instances, but I cannot use it as input.

For me, if you have the same PURL:
```
ExternalRef: PACKAGE-MANAGER purl pkg:golang/golang.org/x/text@v0.3.7
```
it is the same package.

Our internal tool cannot create different packages with the same PURL.

So I still would expect that Syft SPDX outputs only one instance of package with the same PURL.
You could use PackageComment to provide information on the fact that the package has been found multiple times.

What do you think?
