### ISSUE TITLE
Disabling terminal output coloring

### ISSUE THREAD

**Issue by tchaumeny** [anchore/syft#1893]
**What would you like to be added**:

I couldn't find a way to disable the terminal coloring of output.
Usually, this is achievable by setting the env variable `NO_COLOR=1`, which has no effect with Syft.

**Why is this needed**:

This is useful when syft output is processed outside of the terminal.

**Comment by kzantow** [comment]
Hi @tchaumeny we are currently looking to update a library to use Bubbletea, which will support that option. However, if you're looking to use the tools with logs, a better option might be using `-q` which means "quiet" as this disables the real-time terminal UI in favor of just outputting the SBOM directly to stdout.

**Comment by wagoodman** [comment]
While working on the bubbletea port PR I tried out the NO_COLOR env var on the current version of syft and it seemed to work

<img width="446" alt="Screenshot 2023-06-30 at 9 01 31 AM" src="https://github.com/anchore/syft/assets/590471/57a27cab-43d3-4597-8706-85bbf6e3e591">

(I've also confirmed the same behavior when swapping to bubbletea). Can you let me know what distro name and version you're running on and how you're invoking syft?

**Comment by tchaumeny** [comment]
I'm using syft on macos 13.3.1, here is an example:

<img width="517" alt="Screenshot 2023-06-30 at 16 21 15" src="https://github.com/anchore/syft/assets/1296387/0715d8dd-d6a2-4a79-986c-1973e884f9e8">

**Comment by wagoodman** [comment]
Curious! what shell and terminal emulator are you using?

**Comment by tchaumeny** [comment]
The shell is zsh on macos native Terminal, and `TERM=xterm-256color`

**Comment by tchaumeny** [comment]
Oh actually I noticed I have the same behavior as you have on your screenshot, `NO_COLOR=1` actually disables colors for the output below. It doesn't for the additional output generated with the `-v`flag.

<img width="297" alt="Screenshot 2023-06-30 at 16 45 42" src="https://github.com/anchore/syft/assets/1296387/07e95e87-8f27-4782-9cb7-d811d912a4ea">

**Comment by wagoodman** [comment]
ah! that's helpful, I think I know where the problem is. Our logger has been configured to always enforce color, we can adjust that.
