### ISSUE TITLE
Add syft packages sub command.

### ISSUE THREAD

**Issue by hev** [anchore/syft#190]
As an API author I would like to leverage syft to list packages so that the output can be used by API consumers. 

__AC__
Add the following new command. 

```
 syft packages [IMAGE-PATH]
```
1. Add a sub-command that mimics the behavior of the root command for listing packages. 
1. The primary use case is to output json but keep existing flag options from the root command such as -o. 
1. Keep the existing root command

__Steps to Test__
1. Analyze known sample image for known package content. 
1. Test existing syft flags (e.g. -o)

**Comment by Toure** [comment]
__Steps to Test Failures__

1. Ensure that malformed inputs are handled correctly
1. Ensure that root commands remain functional
1. Ensure empty arguments are also handled correctly

**Comment by wagoodman** [comment]
This would be an ideal time to include CLI-level testing (assert the CLI behaves as it should)

**Comment by wagoodman** [comment]
this has been completed (a while ago, I think sometime Jan 2021)
