### ISSUE TITLE
Remove syft root command and provide feature equivalent sub-commands

### ISSUE THREAD

**Issue by hev** [anchore/syft#191]
As a syft user it is confusing to have both a root command and sub-command that have the same behavior (see #190)

__AC__
1. Syft should require user to enter a sub command
1. Add a sub-command that accounts for all of the existing root command scope. 
1. If a user enters the root command the output should show help text

**Comment by Toure** [comment]
__Steps to Test__

1. Ensure empty arguments return general help
1. Ensure that newly for formed sub-commands are functional

**Comment by spiffcs** [comment]
Closing this issue for now - 

Thanks for the feedback on the command structure!

We're definitely thinking about removing the alias or just removing the packages subcommand in the future for a v1 release, but we have no plans as of right now to tackle this part of the code base.
