### ISSUE TITLE
Correlate package index entries with discovered installations

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#199]
**What would you like to be added**:
Today syft catalogs content based on what is discovered in "index-like" files --like the `package-lock.json`, `yarn.lock`, `requirements.txt`, etc. It would be ideal to attempt to verify that the packages discovered in these index files are actually installed within the container image being scanned. That is, just because there is an entry in the `package-lock.json`, it doesn't mean that the package is installed unless we head to `./node_modules/<name>/...` and verify there is something there (best effort). This is the case with all catalogers today, not just the examples given.

**Why is this needed**:
This can help with false positives --say when a stray `yarn.lock` file is left in a container image even after the team has transitioned off of the yarn tool entirely (meaning all entries in the `yarn.lock` can't be trusted).

**Additional context**:
https://github.com/anchore/scan-action/issues/55

**Comment by luhring** [comment]
This has been taken care of. We've split out catalogers into two sets, depending on if we're scanning an image or a directory. This lets us adapt our cataloging strategy accordingly (such as by looking for `package.json` files vs. for `package-lock.json` files). See https://github.com/anchore/syft/pull/203/files#diff-7acc307a618d1c1ea285e6778539597836475c951c896eca95787375d15fef58
