### ISSUE TITLE
Question: meaning of syft:location:X:path & syft:cpe23

### ISSUE THREAD

**Issue by prosunjitbiswas** [anchore/syft#2024]
In the generated SBOM using `syft packages` , I see that in more than one properties for a included component for `syft:location` and `syft:cpe23`.  
```
       {
          "name": "syft:location:0:path",
          "value": "venv/lib/python3.9/site-packages/flake8_pyproject-1.2.3.dist-info/METADATA"
        },
        {
          "name": "syft:location:1:path",
          "value": "venv/lib/python3.9/site-packages/flake8_pyproject-1.2.3.dist-info/RECORD"
        },
      
       {
          "name": "syft:cpe23",
          "value": "cpe:2.3:a:python:python_Flake8_pyproject:1.2.3:*:*:*:*:*:*:*"
        },
        {
          "name": "syft:cpe23",
          "value": "cpe:2.3:a:python_Flake8:Flake8-pyproject:1.2.3:*:*:*:*:*:*:*"
        },

```

1. I wonder, why more than one `syft:cpe23` is included in component.properties? Also how these CPEs are different than `component.cpe`? 
2. What does it mean by `syft:location:X:path`? 
3. Additionally, is there any document here all the component.properties used in SBOM generated by syft are explained?

**Comment by kzantow** [comment]
Hi @prosunjitbiswas:

1) Quite frequently, Syft generates multiple CPEs for packages but CycloneDX only has a single CPE location, so Syft outputs additional CPEs in the properties section. This isn't ideal, as Syft/Grype are the only consumers of these additional CPEs as far as I know, but it's a necessary evil if we need to do CPE matching downstream, for example in Grype.

2) The `syft:location:#:path` properties are [locations Syft includes in packages](https://github.com/anchore/syft/blob/main/syft/pkg/package.go#L24).

3) There isn't a document describing all the properties, but these correspond to properties on [the Syft package data model](https://github.com/anchore/syft/blob/main/syft/pkg/package.go#L19-L32) which do not have analogous locations in the CycloneDX data model to store them. Generally, these are useful only to Syft/Grype, and shouldn't need to be used for other purposes.

**Comment by tgerla** [comment]
Hi @prosunjitbiswas, hopefully Keith's reply answered your questions here. We'll go ahead and close this issue but feel free to reopen it or open another one if you need anything else. Thanks.
