### ISSUE TITLE
CycloneDx relationships is not a tree

### ISSUE THREAD

**Issue by ShuP1** [anchore/syft#2090]
**What happened**:

#2063 makes CycloneDx relationships valid to the spec *(Thanks!)* but it is not a dependency tree.

There is not relationship between the explicitly installed packages and the root component.

**What you expected to happen**:

Each packages with no dependency *(so explicitly installed)* should depend on the root component `bom-ref`

**Steps to reproduce the issue**:

- `syft packages alpine:latest -o cyclonedx-json > sbom.json`
- `.metadata.compoenent.bom-ref` is `1d098408640ab242`
- `.dependencies` should contain
```json5
 "dependencies": [
    {
      "ref": "1d098408640ab242",
      "dependsOn": [
        "pkg:apk/alpine/alpine-baselayout@3.4.3-r1?arch=x86_64&distro=alpine-3.18.3&package-id=4457aba38f428cff",
        "pkg:apk/alpine/apk-tools@2.14.0-r2?arch=x86_64&distro=alpine-3.18.3&package-id=5586ad29e03ffa4e",
        // ...
      ]
    },
    {
      "ref": "pkg:apk/alpine/alpine-baselayout@3.4.3-r1?arch=x86_64&distro=alpine-3.18.3&package-id=4457aba38f428cff",
      "dependsOn": [
        "pkg:apk/alpine/alpine-baselayout-data@3.4.3-r1?arch=x86_64&upstream=alpine-baselayout&distro=alpine-3.18.3&package-id=afce4445f1c5ffeb",
        "pkg:apk/alpine/busybox-binsh@1.36.1-r2?arch=x86_64&upstream=busybox&distro=alpine-3.18.3&package-id=337ecb49f16db0b4"
      ]
    },
    {
      "ref": "pkg:apk/alpine/apk-tools@2.14.0-r2?arch=x86_64&distro=alpine-3.18.3&package-id=5586ad29e03ffa4e",
      "dependsOn": [
        "pkg:apk/alpine/ca-certificates-bundle@20230506-r0?arch=x86_64&upstream=ca-certificates&distro=alpine-3.18.3&package-id=f4908edd2139049e",
        "pkg:apk/alpine/libcrypto3@3.1.2-r0?arch=x86_64&upstream=openssl&distro=alpine-3.18.3&package-id=2f57c3c70ea9fc61",
        "pkg:apk/alpine/libssl3@3.1.2-r0?arch=x86_64&upstream=openssl&distro=alpine-3.18.3&package-id=e6e2202cd771db91",
        "pkg:apk/alpine/musl@1.2.4-r1?arch=x86_64&distro=alpine-3.18.3&package-id=b2eff2e1d40bcf72",
        "pkg:apk/alpine/zlib@1.2.13-r1?arch=x86_64&distro=alpine-3.18.3&package-id=f1797a8b6624b019"
      ]
    },
    // ...
}
```

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: `0.89.0`
- OS (e.g: `cat /etc/os-release` or similar): Ubuntu

**Comment by kzantow** [comment]
Hi @ShuP1, I'm not sure if there should be _dependency_ relationships from the root element (`.metadata.component`) to the other components. In SPDX, we are able to qualify relationships as different types, for example a `CONTAINS` relationship makes sense: an image _contains_ the packages we found. However, a `DEPENDENCY_OF` relationship has a different semantic meaning, and given the naming in CycloneDX, it seems we should only be putting _dependency_ relationships here. In CDX there isn't a way to label the relationship type. It doesn't look like compositions are quite right, either. Is there another way to include this part of the graph in a more semantically correct way?

**Comment by kzantow** [comment]
I'd say the issue probably is twofold:

1) DependencyTrack should probably assume some sort of "contains" relationship inherently if there's a `.metadata.component` defined
2) The CDX spec should _really_ have a relationship mechanism with types, like SPDX does to support more semantically correct graphs

One or both of these things would help to accomplish what I think you're hoping for, which is an accurate graph in DependencyTrack, correct?
