### ISSUE TITLE
Add support for `containers-storage` backend for container images

### ISSUE THREAD

**Issue by hkadakia** [anchore/syft#2107]
**What would you like to be added**:
Support for source path `containers-storage` when looking for container images.

**Why is this needed**:
We build some of our container images using `buildah`. Buildah by default puts these locally built container images in `containers-storage` location. Syft currently does not look for images in that location & hence miss scanning of those images built locally.

A current workaround we are using for syft to locate those images is `skopeo copy containers-storage:localhost/test-image:latest docker-archive:/tmp/test-image.tar:test-image:latest`. This still has a problem of being lossy and we might land up not having the correct layer info.

**Additional context**:

**Comment by tgerla** [comment]
Related to anchore/stereoscope#197

**Comment by tgerla** [comment]
The work here will be done in Stereoscope and no work will be needed in Syft, so we'll close this one as a duplicate and all work here will be tracked in the Stereoscope issue.
