### ISSUE TITLE
SPDX-2.3 is misidentified as SPDX-2.2

### ISSUE THREAD

**Issue by jamietanna** [anchore/syft#2112]
**What happened**:

When using [`formats.Decode`](https://pkg.go.dev/github.com/anchore/syft@v0.89.0/syft/formats#Decode) or [`formats.Identify`](https://pkg.go.dev/github.com/anchore/syft@v0.89.0/syft/formats#Identify) with an SPDX-2.3 document, it is misidentified as SPDX-2.2

**What you expected to happen**:

The document is parsed as the correct type.

**Steps to reproduce the issue**:

See https://github.com/anchore/syft/pull/2111's example tests added.

**Anything else we need to know?**:

It appears to be due to the fact that the `validator` only checks that the document can be parsed, but does not that it's the right version.

Changing the order of [`formats.Formats()`](https://github.com/jamietanna/syft/blob/5dc626d9b22586a2d18918f1b34b28074c9318b1/syft/formats/formats.go#L26-L42) works, but then SPDX-2.2 is parsed as SPDX-2.3.

I had a quick look at it, but may need a nudge from the maintainers in how best to approach this so it still fits within the `sbom.Decoder` and `sbom.Validator` interfaces.

**Comment by wagoodman** [comment]
fixed by https://github.com/anchore/syft/pull/2186
