### ISSUE TITLE
pURL for reactor-netty-* libraries is incorrect

### ISSUE THREAD

**Issue by olivierboudet** [anchore/syft#2152]
**What happened**:
When using reactor-netty in java applications, pURL of netty packages is incorrectly reported.

**What you expected to happen**:
For `reactor-netty-core` I expect the pURL to be `pkg:maven/io.projectreactor/reactor-netty-core@x.x.x` but instead it is `pkg:maven/io.projectreactor.netty.reactor-netty-core/reactor-netty-core@x.x.x`.

**Steps to reproduce the issue**:
Run `syft codecentric/spring-boot-admin:2.7 -o syft-json | jq '.artifacts[] | select (.name | contains("reactor-netty-core")) | .purl'
` 
The package purl is  `pkg:maven/io.projectreactor.netty.reactor-netty-core/reactor-netty-core@1.0.25` instead of `pkg:maven/io.projectreactor/reactor-netty-core@1.0.25`

**Anything else we need to know?**:

Is suppose this happens because `reactor-netty-core` jar does not include `pom.xml`, so groupId is deduced from manifest : 
```
Bundle-Name: reactor-netty-core
Bundle-SymbolicName: io.projectreactor.netty.reactor-netty-core
```
but in this case `Bundle-SymbolicName` includes both groupId and artifactId...
Perhaps a workaround can be to remove the value of `Bundle-Name` field from the `Bundle-SymbolicName` ?  

**Environment**:
- Output of `syft version`:
```
Application:     syft
Version:         0.90.0
BuildDate:       2023-09-11T21:22:00Z
GitCommit:       b82c0ffc3417bdc8c38f4633af95a668ec29fa35
GitDescription:  v0.90.0
Platform:        linux/amd64
GoVersion:       go1.21.0
Compiler:        gc
```
- OS (e.g: `cat /etc/os-release` or similar):
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

**Comment by wagoodman** [comment]
Since opening this issue, it seems that this is now producing the correct purl:
```
 syft codecentric/spring-boot-admin:2.7 -o syft-json | jq '.artifacts[] | select (.name | contains("reactor-netty-core")) | .purl'
 ✔ Pulled image
 ✔ Loaded image                                                                                                                                      codecentric/spring-boot-admin:2.7
 ✔ Parsed image                                                                                                sha256:15441f975812051bf22e63b5284a96bec6d8f91192ddb4281acee601c6edbecc
 ✔ Cataloged contents                                                                                                 cdb3f470ccf968f64497806bfbc033be0857984123ee27b6e560d0d1bbfe90af
   ├── ✔ Packages                        [92 packages]
   └── ✔ Executables                     [1,047 executables]

"pkg:maven/io.projectreactor.netty/reactor-netty-core@1.0.25"
```

Note, this is different than the noted purl from the issue description (the namespace has an extra `.netty`), however, this latest result from syft is what we'd expect based on the pURL spec for maven packages:

> The group id is the namespace and the artifact id is the name.

Note that the group ID and artifact ID for https://mvnrepository.com/artifact/io.projectreactor.netty/reactor-netty-core/1.0.25
is `io.projectreactor.netty` and `reactor-netty-core`.
