### ISSUE TITLE
Unify scan for different container archive formats

### ISSUE THREAD

**Issue by devfbe** [anchore/syft#2177]
**What would you like to be added**:
At the moment, when calling `syft packages` for a container archive, you have to tell syft explicitly, which kind of container archive you want to scan (docker-archive or oci-archive). It would be really nice to add an auto detection here so that you can just call syft packages `container-archive:foo.tar` and syft automatically detects the container archive. This should be easy to implement because the tar file structure is really different for docker and oci-archives (oci-archives contain an index.json, docker archives a manifest.json and so on).

**Why is this needed**:
We use syft in our CICD pipeline for example in a kaniko build job which can save the current image as tar file. It is not defined at the moment which kind of image format is used and this may change in future or it may change when building images derived from different base image formats. At the moment we have to guard this in our pipelines by manually checking the contents of the tar - but it would really nice if syft could use an auto detection here, so that we don't have to implement that on our own.

**Comment by devfbe** [comment]
If the maintainers would be interested in this feature, I would try to implement this and offer it as patch.

**Comment by wagoodman** [comment]
Today the scheme input is optional -- syft will attempt to guess the correct source type based on the provided input (using the most specific type first). You should be able to run syft safely without it:


```
syft ./foo.tar
```

Are you seeing that this is not working correctly?

**Comment by tgerla** [comment]
Hey @devfbe, since we haven't heard back, we'll close this issue but please feel free to reply and re-open it if you still need help here...thanks!
