### ISSUE TITLE
Jar parser chokes on empty lines

### ISSUE THREAD

**Issue by ecki** [anchore/syft#2179]
https://github.com/anchore/syft/blob/8f57d22f639e132cbd87324abacd864232c611ce/syft/pkg/cataloger/java/parse_java_manifest.go#L35

We have manifests which contain something like this. The line is leading with a blank, so it is not an empty line which should trigger the section change. I guess removing the Trim would fix this problem ($ denotes line end):

```manifest
Key-keykeykey: initialconfig:com/seeburger/aqmtestclient/aqmtestclient$
 ,$
  line1,$
  line2,$
        $    # aka not empty line
  line3,$
```
That value (especially line break semantics) is not so important for the analysis, but the warnings are annoying.

**Comment by wagoodman** [comment]
I think this *might* be as simple as removing the `strings.TrimSpace`, however, this needs to be verified. 

Dev note: for the person picking this up, on top of fixing the correctness issue we should also try and improve the manifest parser to [not log too many warnings](https://github.com/anchore/syft/blob/8f57d22f639e132cbd87324abacd864232c611ce/syft/pkg/cataloger/java/parse_java_manifest.go#L49) under these conditions (be a little more resilient) .
