### ISSUE TITLE
Contributing New Catalogers - A Guide for Hacktoberfest and Beyond

### ISSUE THREAD

**Issue by spiffcs** [anchore/syft#2184]
# Contributing New Catalogers to Syft

# Join the community meeting on October 12 where we will be discussing new features being added to syft and the inflight cataloger work. [Calendar Link](https://calendar.google.com/calendar/u/0/r?cid=Y182OTM4dGt0MjRtajI0NnNzOThiaGtnM29qNEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

## To see the current open cataloger requests check out the list [here](https://github.com/anchore/syft/issues?q=is%3Aissue+is%3Aopen+label%3Anew-cataloger). If an issue is not assigned it is open for anyone to contribute.

--------------------------

## What is a Cataloger
A cataloger is syft's term for a module that knows how to detect and analyze components from a particular package manager or ecosystem. 

If you're interested in contributing a new cataloger take a look at the below documentation. The issue also goes further into how to start thinking about what type of cataloger you contribute after selecting the ecosystem. If you have questions you can always @anchore/tools on this thread and we will come by and answer any questions you have.
[Developing.MD](https://github.com/anchore/syft/blob/44e54802380f949a1476c25c1b48c5e3488e89bc/DEVELOPING.md#syft-catalogers)
Be sure to following the [Contributing](https://github.com/anchore/syft/blob/main/CONTRIBUTING.md) documentation when authoring your feature!

## Types of Cataloger
Catalogers generally come in two flavors: 

### Declared package Cataloger
One type of cataloger describes declared packages. These catalogers are used by default when scanning directories ("directory catalogers"). The default list can be found here: https://github.com/anchore/syft/blob/44e54802380f949a1476c25c1b48c5e3488e89bc/README.md?plain=1#L185-L215 These catalogers tend to be when you are parsing manifest files for package managers (e.g. python requirements.txt, a ruby gemfile.lock, javascript package.json).

    
Example:

Given this `package-lock.json`
```json
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "@actions/core": {
      "version": "1.6.0",
      "resolved": "https://registry.npmjs.org/@actions/core/-/core-1.6.0.tgz",
      "integrity": "sha512-NB1UAZomZlCV/LmJqkLhNTqtKfFXJZAUPcfl/zqG7EfsQdeUJtaWO98SGbuQ3pydJ3fHl2CvI/51OKYlCYYcaw==",
      "requires": {
        "@actions/http-client": "^1.0.11"
      }
    }
  }
```

Syft would construct this package
```golang
{
	Name:      "@actions/core",
	Version:   "1.6.0",
	FoundBy:   "javascript-lock-cataloger",
	PURL:      "pkg:npm/%40actions/core@1.6.0",
	Language:  pkg.JavaScript,
	Type:      pkg.NpmPkg,
	MetadataType: pkg.NpmPackageLockJSONMetadataType,
},
```

### Installed 
The second type of cataloger is one that catalogs installed packages. These catalogers are used by default when scanning container images ("image catalogers"). This tends to be when you are parsing files that are left behind by package managers when you use them to install software packages (e.g. the RPM database, python egg or wheel metadata, etc.). The default list used for image scanning can be found here:https://github.com/anchore/syft/blob/38d5ef2c84e9bb8245c657daf2a3f97facde0a8f/README.md?plain=1#L166-L183

Example:

The [ALPM](https://github.com/anchore/syft/tree/main/syft/pkg/cataloger/alpm) cataloger searches for `desc` files using the following [glob](https://github.com/anchore/syft/blob/38d5ef2c84e9bb8245c657daf2a3f97facde0a8f/syft/pkg/alpm_metadata.go#L14):
`**/var/lib/pacman/local/**/desc`. [Here](https://en.wikipedia.org/wiki/Glob_(programming)) is a quick primer on glob matching.

So given a `desc` file like below is found:
```file
%NAME%
gmp

%VERSION%
6.2.1-2

%BASE%
gmp

%DESC%
A free library for arbitrary precision arithmetic

%URL%
https://gmplib.org/

...........
```

Syft would construct:
```golang
{
	Name:    "gmp",
	Version: "6.2.1-2",
	Type:    pkg.AlpmPkg,
	FoundBy: "alpmdb-cataloger",
	MetadataType: "AlpmMetadata",
}
```

## IMPORTANT
Make sure to read through different cataloger examples to be sure you're including all required information for a syft package. The above examples have been cut down for brevity, but other important fields like `purl`, `licenses`, and `locations` should also be considered.

# How to write a cataloger
Before getting started in implementing a cataloger you need to determine which one you are trying to build from the above flavors. If you’re not sure about which of the above flavors you’re trying to implement, feel free to tag the @anchore/tools in the issue - we’re always happy to answer questions or help with the design of new features.

### Examples
Here are some good example of catalogers added recently to work off of when considering the contribution:

1. The GithubAction and Workflow cataloger is the most recent https://github.com/anchore/syft/pull/2140
2. The R cataloger is a good example of a new image cataloger https://github.com/anchore/syft/pull/1790
3. The Haskell cataloger https://github.com/anchore/syft/pull/1290

### Components of a Cataloger
Let's take a look at a single cataloger and its constituent components and how it gets wired up into syft, starting with the Haskell cataloger:
### [The parser function](https://github.com/anchore/syft/blob/534a5f54b037df898475b6fe9b6a65844fba5ab5/syft/pkg/cataloger/haskell/parse_stack_yaml.go#L22) 

This function is what does all of the work in a cataloger. It takes a `io.Reader` to a file that contains content to be cataloged, in this case a [stack.yaml](https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/haskell/test-fixtures/stack.yaml) file

### [The cataloger object itself](https://github.com/anchore/syft/blob/534a5f54b037df898475b6fe9b6a65844fba5ab5/syft/pkg/cataloger/haskell/cataloger.go#L13), 

This object pairs up a parser function with one or more globs to files that should be cataloged, in this case **/stack.yaml files. For a primer on `globs` see the [previous](https://en.wikipedia.org/wiki/Glob_(programming)#:~:text=The%20glob%20command%2C%20short%20for,command%3A%20%2Fetc%2Fglob.) link from this issue.

### [The list of catalogers](https://github.com/anchore/syft/blob/8a414b5366fb81333fa8e8888880134d1b70badc/syft/pkg/cataloger/cataloger.go#L82)

Lastly you need to wire up your cataloger into that syft will use at runtime. As mentioned earlier, there are two kinds of catalogers (and not necessarily mutually exclusive), so you’ll need to add your cataloger to one or both lists.

After looking through the above examples section, the developing document is the best place to head next for details on building a new cataloger:
https://github.com/anchore/syft/blob/main/DEVELOPING.md#building-a-new-cataloger

### Summary
As maintainers we're always happy to help guide this process so if you're interested please feel free to tag @anchore/tools in any of the spaces you might have questions.

**Comment by wagoodman** [comment]
Cleaning up hacktoberfest activities
