### ISSUE TITLE
`if` with identical `then` and `else` blocks in `cli/options/writer_test.go`

### ISSUE THREAD

**Issue by chavacava** [anchore/syft#2192]
https://github.com/anchore/syft/blob/86005d1593c2c73f96e2958dde8624e2b897b47e/cmd/syft/cli/options/writer_test.go#L186-L190

Either the whole conditional can be replaced by `assert.NotNil(t, w.out) ` or the `else` branch should be fixed.

(found by [revive](https://github.com/mgechev/revive) while testing it on syft code base)

**Comment by kzantow** [comment]
It seems like the first suggestion would probably be fine. PRs welcome! :)
