### ISSUE TITLE
Exclude path option

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#221]
**What would you like to be added**:
Ability to exclude paths from being scanned (mirror of issue https://github.com/anchore/grype/issues/183)

**Why is this needed**:
You may already have a container running made from the image you want to catalog, however, there may be volume mounts or container additions that you'd like to explicitly ignore.

**Comment by dpippenger** [comment]
It's interesting this issue has seen so little attention. Providing a --exclude flag for directories would open up syft for generating an SBOM for the container host itself. Doing this would create a whole new functionality for syft/grype and Anchore engine for the cost of one cli argument.

**Comment by wagoodman** [comment]
I want to extend the original CLI ergonomic suggestions put forth by @yudong from https://github.com/anchore/syft/issues/221#issuecomment-936436399 :
```bash
# exclude single path
syft my/image:latest --exclude /some/path

# exclude multiple paths
syft my/image:latest -e /some/dir -e /some/file -e /something/else

# exclude by glob
syft my/image:latest -e /some/place/*.txt
```

And additionally being able to express this via the application configuration:
```yaml
exclude:
  - /some/path
  - /some/other/place
  - /a/**/glob
  - *.txt
```

This should work the same regardless if we are scanning an image or a directory.

This new behavior suggests the following changes:
- Adding the ability to bail early when indexing individual paths within layer tars (based on path/glob exclusion rules): https://github.com/anchore/stereoscope/blob/003132a67c108b437dafa50bfbc3fa4e89944cbe/pkg/image/layer.go#L145-L148
- Ability to prune entire branches from `filepath.Walk` based on path/glob exclusion rules within the syft directory resolver: https://github.com/anchore/syft/blob/main/syft/source/directory_resolver.go#L98-L107

A few notes that could influence the implementation:
- syft and stereoscope has normalized glob resolution (in string matching and otherwise) with [doublestar](https://github.com/bmatcuk/doublestar) and not with the globbing implementation from the standard lib
- there is already [path filtering on the directory resolver](https://github.com/anchore/syft/blob/main/syft/source/directory_resolver.go#L112-L116) but must visit all nodes discovered by walking, which may not be ideal. Migrating that mechanism to a new mechanism that affects the walking trajectory itself would be ideal.

**Comment by cameronkerrnz** [comment]
Similarly to exclusion, but more generalisable, can we just have a list of files (eg. find ..... | syft packages -), which would mean that operators could more easily list / exclude (find ... | grep -v ... | syft packages -)

I'm interested in seeing what I can use syft for for finding log4j instances on servers; kinda topical.

**Comment by cameronkerrnz** [comment]
If anyone wants a workaround that would allow for this, they could (given root privileges) use the 'unshare' Linux command to create a different mount namespace, then bind-mount an empty directory over any directory they would like to exclude), then run syft... sort of like this:

```
mkdir /var/empty/syft
unshare --mount sh -c "
  # note that syft already ignores /sys /proc and /dev, but you'll want 0.32.1 if you don't specify those at least.
  for d in /sys /proc /dev /run /home
  do
    mount /var/empty/syft/ $d -o bind,ro
  done
  syft dir:/
"
```

**Comment by richlv** [comment]
Thank you for this improvement - looks great, taking into account multiple options and wildcards, similar to the rsync implementation.
