### ISSUE TITLE
README needs update for exclude option

### ISSUE THREAD

**Issue by NataliaAn** [anchore/syft#2246]
**What happened**:

README file is outdated when it comes to the `exclude` option. It took me a while to work out what it was as the syft scan wasn't running with the syntax shown in the examples.

**What you expected to happen**:

Syft scan to run correctly with the exclude option but it didn't run at all.

**Steps to reproduce the issue**:

Run a command with the suggested options of README for exclude e.g. `syft <source> --exclude './out/**/*.json'`

**Anything else we need to know?**:

Seems like `=` is needed, it would be good to update README to reflect that so correct syntax on the guide for the above would be `syft <source> --exclude='./out/**/*.json'`

**Environment**:
- Output of `syft version`: v0.92.0
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by tgerla** [comment]
Hi @NataliaAn, thanks for the report. I've tested this myself on Syft 0.94 as well as 0.92 and I am not able to reproduce any difference in behavior between "--exclude=..." and "--exclude ..."  -- I am not sure if I'm doing something different than you. Here's what I've done:

Two directories, a and b, a containing a few random jars, and b is empty:

```
tgerla@Timothys-MacBook-Pro-2 syft-2246 % ls -lR
total 0
drwxr-xr-x  4 tgerla  staff  128 Oct 30 12:02 a
drwxr-xr-x  2 tgerla  staff   64 Oct 30 12:02 b

./a:
total 64
-rw-r--r--  1 tgerla  staff  12919 Oct 30 12:02 org.eclipse.osgi.util_3.7.0.v20220427-2144.jar
-rw-r--r--  1 tgerla  staff  12919 Oct 30 12:02 org.eclipse.osgi_3.18.0.v20220516-2155.jar

./b:
total 0
```

Running syft 4 times with different configurations of --exclude seem to produce the expected results regardless of the =:

```
tgerla@Timothys-MacBook-Pro-2 syft-2246 % syft --exclude ./a .
 ✔ Indexed file system                                                                                                                                                                                 .
 ✔ Cataloged packages              [0 packages]
[0000]  WARN no explicit name and version provided for directory source, deriving artifact ID from the given path (which is not ideal)
No packages discovered
tgerla@Timothys-MacBook-Pro-2 syft-2246 % syft --exclude=./a .
 ✔ Indexed file system                                                                                                                                                                                 .
 ✔ Cataloged packages              [0 packages]
[0000]  WARN no explicit name and version provided for directory source, deriving artifact ID from the given path (which is not ideal)
No packages discovered
tgerla@Timothys-MacBook-Pro-2 syft-2246 % syft --exclude ./b .
 ✔ Indexed file system                                                                                                                                                                                 .
 ✔ Cataloged packages              [2 packages]
[0000]  WARN no explicit name and version provided for directory source, deriving artifact ID from the given path (which is not ideal)
NAME       VERSION  TYPE
v20220427  2144     java-archive
v20220516  2155     java-archive
tgerla@Timothys-MacBook-Pro-2 syft-2246 % syft --exclude=./b .
 ✔ Indexed file system                                                                                                                                                                                 .
 ✔ Cataloged packages              [2 packages]
[0000]  WARN no explicit name and version provided for directory source, deriving artifact ID from the given path (which is not ideal)
NAME       VERSION  TYPE
v20220427  2144     java-archive
v20220516  2155     java-archive
```

Do you have a way to reproduce this that we can try? Thanks much!

**Comment by NataliaAn** [comment]
I've figured what was happening. I wasn't splitting it correctly when it had the space on the subprocess.run arguments. It had to be either two separate values `'--exclude', path` or one consecutive `--exclude=path`. I'm closing the issue.
