### ISSUE TITLE
WARNINGs suppression

### ISSUE THREAD

**Issue by NataliaAn** [anchore/syft#2247]
**What would you like to be added**:

It would be good to have a warning suppression options (maybe per warning id).

**Why is this needed**:

It will help clean up the output of the scans as some warnings are expected to show up e.g. the ones on manifests of external packages' syntax. Once suppressed it would be easier if some unexpected warning comes up to spot it easier.

**Comment by tgerla** [comment]
Hi @NataliaAn, thanks for the suggestion. We do have some basic log level management features in the configuration file -- you can adjust the log level from "error" to "debug", etc. You can also set this by environment variable, like:

```
$ SYFT_LOG_LEVEL=error syft myimage:latest
```

We can consider a warning suppression system but I wonder if you might be able to share with us some of the spurious warnings you are seeing that you want to suppress? They might be set to the wrong log level and we could consider adjusting them.

Do you have a public image that generates some of these warnings? We would be happy to take a look.

**Comment by tgerla** [comment]
I'm going to go ahead and close this issue because we haven't heard back, but please feel free to re-open if the warnings are still affecting you--happy to consider solutions. Thanks!
