### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by jeff-cook** [anchore/syft#228]
**What would you like to be added**:

A published Docker image to run syft.

**Why is this needed**:

With a published Docker image it would simplify usage in most CI environments. Without a published Docker image syft is installed every time it runs within a CI environment.

**Additional context**:

**Comment by davidkarlsen** [comment]
I see the PR was merged, but no tags available at: https://hub.docker.com/r/anchore/syft ?

**Comment by luhring** [comment]
Hi @davidkarlsen — one related PR was merged, but the primary PR has not been merged (#310). Long story short, this required more work than it seemed at first glance, and we ended up needing to make substantial changes to our release pipeline. (More details in that PR description.)

We're hoping to pick this back up shortly and begin publishing images to Docker Hub.
