### ISSUE TITLE
Annotate where each CPE on a package is sourced from

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#2282]
Today we have a list of CPEs on a package, which classically have always been generated with logic tailored for each ecosystem:
```json
"cpes": [
  "cpe:2.3:a:ansi-regex:ansi-regex:5.0.1:*:*:*:*:*:*:*",
  "cpe:2.3:a:ansi-regex:ansi_regex:5.0.1:*:*:*:*:*:*:*",
  "cpe:2.3:a:ansi_regex:ansi-regex:5.0.1:*:*:*:*:*:*:*",
  "cpe:2.3:a:ansi_regex:ansi_regex:5.0.1:*:*:*:*:*:*:*",
  "cpe:2.3:a:ansi:ansi-regex:5.0.1:*:*:*:*:*:*:*",
  "cpe:2.3:a:ansi:ansi_regex:5.0.1:*:*:*:*:*:*:*"
]
```

Since then a CPE index sourced from the NVD data [has been added](https://github.com/anchore/syft/pull/1897), which means that there is more than one way for a CPE to make it onto a package. Or, more specifically, if there is a single CPE on a package, it's unclear if that CPE was generated or if it was from the new index.

Also, there may be more places that we source this CPE information, say lifting from packaging metadata, other 3rd party indexes, etc. Ideally the SBOM should be able to represent where the information was sourced from without the consumer needing to guess this.

We could make a change to annotate CPEs with this information:
```json
"cpes": [ 
  {
   "value": "cpe:2.3:a:ansi-regex:ansi-regex:5.0.1:*:*:*:*:*:*:*",
   "source": "auto-generated"
  },
  {
   "value": "cpe:2.3:a:ansi:ansi-regex:5.0.1:*:*:*:*:*:*:*",
   "source": "nvd-cpe-index"
  }
]
```

This proposal would necessarily be a breaking change, however, open to other ways to introduce this in a non-breaking way!

**Comment by willmurphyscode** [comment]
> Or, more specifically, if there is a single CPE on a package, it's unclear if that CPE was generated or if it was from the new index.

@wagoodman I don't understand why the case where there is a single CPE is special. It looks like we append, even in cases where there is an exact match in the dictionary:

https://github.com/anchore/syft/blob/b0ab75fd89246ac4ee37abebd4753d8449bfb3aa/internal/task/package_task_factory.go#L112-L117

So I think even if there are multiple CPEs on a package, it's unclear whether they were generated or whether one of them was found in the NVD CPE dictionary.

**Comment by willmurphyscode** [comment]
Note that this issue is connected #2529 - changing how Syft represents CPEs is probably also a good time to decouple the representation from an external library as well.
