### ISSUE TITLE
zero exit status is returned when there are failures 

### ISSUE THREAD

**Issue by alfredodeza** [anchore/syft#231]
**What happened**: While scanning an image that produces errors in parsing, a zero exit status is observed. Having a non-zero exit status is crucial so other consumers of `syft` (e.g. Anchore Engine), can detect a serious anomaly.

This particular case seems serious enough because the errors found are preventing proper cataloging of an image. These is a subset of the errors produced:

```
[0003] ERROR cataloger 'javascript-package-cataloger' failed to parse entries (reference={id:3194 Path:/usr/lib/node_modules/npm/node_modules/execa/package.json}): failed to parse package.json file: json: cannot unmarshal object into Go struct field PackageJSON.author of type string
[0003] ERROR cataloger 'javascript-package-cataloger' failed to parse entries (reference={id:4863 Path:/usr/lib/node_modules/npm/node_modules/pacote/node_modules/minipass/package.json}): failed to parse package.json file: json: cannot unmarshal object into Go struct field PackageJSON.author of type string
[0003] ERROR cataloger 'javascript-package-cataloger' failed to parse entries (reference={id:3948 Path:/usr/lib/node_modules/npm/node_modules/json-schema/package.json}): failed to parse package.json file: json: cannot unmarshal object into Go struct field PackageJSON.author of type string
[0003] ERROR cataloger 'javascript-package-cataloger' failed to parse entries (reference={id:2527 Path:/usr/lib/node_modules/npm/node_modules/byte-size/package.json}): failed to parse package.json file: json: cannot unmarshal object into Go struct field PackageJSON.author of type string
[0003] ERROR cataloger 'javascript-package-cataloger' failed to parse entries (reference={id:5963 Path:/usr/lib/node_modules/npm/node_modules/validate-npm-package-license/package.json}): failed to parse package.json file: json: cannot unmarshal object into Go struct field PackageJSON.author of type string
[0003] ERROR cataloger 'javascript-package-cataloger' failed to parse entries (reference={id:2789 Path:/usr/lib/node_modules/npm/node_modules/config-chain/package.json}): failed to parse package.json file: json: cannot unmarshal object into Go struct field PackageJSON.author of type string
[0003] ERROR cataloger 'javascript-package-cataloger' failed to parse entries (reference={id:4936 Path:/usr/lib/node_modules/npm/node_modules/path-parse/package.json}): failed to parse package.json file: json: cannot unmarshal object into Go struct field PackageJSON.author of type string
```

**What you expected to happen**: A non-zero exit status when there are errors that can affect cataloging of an image

**How to reproduce it (as minimally and precisely as possible)**:

```
$ syft -o json anchore/test_images:npm
....
$ echo $?
```

**Anything else we need to know?**: This is a tricky one, and should probably be addressed before https://github.com/anchore/syft/issues/230 

**Environment**:
- Output of `syft version`: current tip of main
- OS (e.g: `cat /etc/os-release` or similar): OSX but it shouldn't matter

**Comment by wagoodman** [comment]
Agreed on needing to return a non-zero code on this case, but also want to point out a nuance I feel is important. I feel in this case we want to make certain to be "loud" when errors occur, surfacing them to the user when they occur, but not necessarily halt execution where the error occurs. That is, I feel that cataloging should continue through the remaining catalogers when hitting this case, but also agree that we should ultimately indicate a problem with a non-zero return code.

This means we can't simply return a `error` prematurely at https://github.com/anchore/syft/blob/v0.4.1/syft/cataloger/common/generic_cataloger.go#L107-L108, but instead accumulate the errors and ultimately return them.

**Comment by alfredodeza** [comment]
@wagoodman the problem is that this was not clear at all in Anchore Engine. It wasn't clear at all that entries couldn't get parsed, and all output was eaten up because of it.

I believe that `ERROR` levels should always return a non-zero exit status. If we don't want these to be a non-zero exit status but bubble them up to the user, then that is fine, but perhaps a lower log level is the alternative. 

There are two use cases here, one for a user, and the other for a machine-consumable call. This particular problem was critical on the latter. Anchore Engine needs to have a way to detect these and error out.

**Comment by luhring** [comment]
My understanding of what we're saying here:

We all agree:
- If an error is being surfaced (e.g. via logger), the exit status should be non-zero.

It's not clear if we agree:
- It's okay _**not to halt the process immediately**_ when an error is handled — that is, as long as when the process _**eventually**_ exits, it returns a non-zero code, it's acceptable for other parts of the program to continue, which allows for potentially surfacing additional useful information (such as _additional_ errors), and then finally exiting non-zero (since at least one error occurred).

**Comment by wagoodman** [comment]
I think we are in agreement about the basics, yes?

> I believe that ERROR levels should always return a non-zero exit status

Agreed. To be clear the case outlined in this issue is truly an error --we attempted to parse a field that exists and parsing failed. We do not necessarily want to report that "nothing" went wrong, as it has

> If we don't want these to be a non-zero exit status but bubble them up to the user, then that is fine, but perhaps a lower log level is the alternative.

Agreed. We've recently added a warning log level to the logger to help with this situation for cases that are not inherently errors. The problem described in this issue is inherently an error, so a warning level should not apply here.

Regarding...

> It's not clear if we agree ... [whether] it's okay not to halt the process immediately when an error is handled

I'm voting we should allow for a "stop-and-error-now" vs "deferred-error" distinction. That is, we should have a "class" of error that roughly translates to "An error occurred, but keep going... at the end of execution, having this class of error means we should return a non-zero exit code". To be clear, this mechanism doesn't exist yet in the code base, so we need to add it... **I feel that would be the purpose of this issue would be to add the "deferred-error" mechanism described above and incorporate it such that when the npm parser error case described above occurs we return a non-zero exit code.**

**Comment by alfredodeza** [comment]
For the context of this ticket and what triggered it, the main concern is to have a non-zero exit status when there are errors. It doesn't really matter _in that context_ if the execution halts immediately or if it continues. As long as there are non-zero exit status, it doesn't matter that much.

I don't think the scope of this ticket should cover additional work to address a "deferred-error" as that doesn't change the nature of the problem

**Comment by luhring** [comment]
Given that we won't create a "deferred-error" mechanism, and that the ERROR-level log entries that resulted in a zero exit code have been changed to WARN-level, it's now the case that ERROR-level log entries correlate with non-zero exits. Thus, we'll close this.

**Comment by furrpleTtalgi** [comment]
> I think we are in agreement about the basics, yes?
> 
> > I believe that ERROR levels should always return a non-zero exit status
> 
> Agreed. To be clear the case outlined in this issue is truly an error --we attempted to parse a field that exists and parsing failed. We do not necessarily want to report that "nothing" went wrong, as it has
> 
> > If we don't want these to be a non-zero exit status but bubble them up to the user, then that is fine, but perhaps a lower log level is the alternative.
> 
> Agreed. We've recently added a warning log level to the logger to help with this situation for cases that are not inherently errors. The problem described in this issue is inherently an error, so a warning level should not apply here.
> 
> Regarding...
> 
> > It's not clear if we agree ... [whether] it's okay not to halt the process immediately when an error is handled
> 
> I'm voting we should allow for a "stop-and-error-now" (simply return an error and stop processing immediately) vs "deferred-error" distinction. That is, we should have a "class" of error that roughly translates to "An error occurred, but keep going... at the end of execution, having this class of error means we should return a non-zero exit code" (this is the "deferred-error"). To be clear, this mechanism doesn't exist yet in the code base, so we need to add it... **I feel that the purpose of this issue would be to add the "deferred-error" mechanism described above and incorporate it such that when the npm parser error case described above occurs we return a non-zero exit code.**

can we stop the scanning manually now?

**Comment by luhring** [comment]
(^ This was opened in a separate issue: https://github.com/anchore/syft/issues/415. Replied there.)
