### ISSUE TITLE
Latest syft version combined with grype does not find vulnerabilities

### ISSUE THREAD

**Issue by jokarl** [anchore/syft#2319]
**What happened**:
Running the [syft SBOM action](https://github.com/anchore/sbom-action) in a workflow generates an SBOM, but when combined with [scan action](https://github.com/anchore/scan-action) it did not produce any warnings, even though I purposefully put a vulnerable dependency in my project: https://www.nuget.org/packages/System.Text.RegularExpressions/4.3.0

I downloaded the resulting SBOM artifact and scanned it locally, where I run grype version `0.73.1`, and this did not produce any warnings either.

I then generated the SBOM locally, with the exact same command as the action uses, where I had an older version of syft (`0.73.0`).  When I then ran this SBOM together with grype, I get warnings as I would expect:

I then updated syft locally to `0.96.0` and scanned my codebase again, piping the SBOM to grype, and then I get no warnings at all.

**What you expected to happen**:
I would expect the latest version of syft to work combined with the latest version of grype.

**Steps to reproduce the issue**:
Create a dotnet project with a reference to package:

```
<PackageReference Include="System.Text.RegularExpressions" Version="4.3.0" />
```
Build the project to get a `deps.json` file

Install syft `0.73.0`:
```
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin v0.73.0
```
Generate SBOM:
```
syft packages -vv dir:. -o spdx-json > syft.spdx.json 
```
Run grype:
```
grype syft.spdx.json
 ✔ Vulnerability DB                [no update available]  
 ✔ Scanned for vulnerabilities     [1 vulnerability matches]  
   ├── by severity: 0 critical, 1 high, 0 medium, 0 low, 0 negligible
   └── by status:   1 fixed, 0 not-fixed, 0 ignored 
NAME                            INSTALLED  FIXED-IN  TYPE    VULNERABILITY        SEVERITY 
System.Text.RegularExpressions  4.3.0      4.3.1     dotnet  GHSA-cmhx-cq75-c4mj  High
```

Install latest syft version:
```
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
```

Generate the SBOM again with the same command as previous generartion.  
Scan the file again:

```
grype syft.spdx.json
 ✔ Vulnerability DB                [no update available]  
 ✔ Scanned for vulnerabilities     [0 vulnerability matches]  
   ├── by severity: 0 critical, 0 high, 0 medium, 0 low, 0 negligible
   └── by status:   0 fixed, 0 not-fixed, 0 ignored 
No vulnerabilities found
```

**Anything else we need to know?**:
I am not sure if this issue is for grype or syft, so I apologize if this is the incorrect place to raise this issue.

**Environment**:
syft
```
Application: syft
Version:    0.96.0
BuildDate:  2023-11-09T14:04:09Z
GitCommit:  0891d35e0774f175e3a3f170edcce9ad2f4f015b
GitDescription: v0.96.0
Platform:   darwin/arm64
GoVersion:  go1.21.3
Compiler:   gc
```
grype
```
Application:         grype
Version:             0.73.1
BuildDate:           2023-11-09T14:46:11Z
GitCommit:           e44ec4d4bc680f70b191b88dd2e635a82d4b5c45
GitDescription:      v0.73.1
Platform:            darwin/arm64
GoVersion:           go1.21.3
Compiler:            gc
Syft Version:        v0.96.0
Supported DB Schema: 5
```
OS
```
ProductName:            macOS
ProductVersion:         14.0
BuildVersion:           23A344
```

**Comment by tgerla** [comment]
Hi @jokarl, would it be possible to share with us the SBOMs, the one that produces the result from Grype and the one that doesn't? We would be happy to take a look.

**Comment by jokarl** [comment]
Hi there, sorry about the delay. Attached [syft.json](https://github.com/anchore/syft/files/13402824/syft.json) is the SBOM in `syft-json` format.

Oddly enough, I generated this with syft `0.96.0` and scanned with grype `0.73.1`, exactly as what I outlined in my original post with the difference that I used `syft-json` as the format. Scanning the `syft-json` format with grype works:

```
❯ grype syft.json 
 ✔ Vulnerability DB                [no update available]  
 ✔ Scanned for vulnerabilities     [1 vulnerability matches]  
   ├── by severity: 0 critical, 1 high, 0 medium, 0 low, 0 negligible
   └── by status:   1 fixed, 0 not-fixed, 0 ignored 
NAME                            INSTALLED  FIXED-IN  TYPE    VULNERABILITY        SEVERITY 
System.Text.RegularExpressions  4.3.0      4.3.1     dotnet  GHSA-cmhx-cq75-c4mj  High
```

I then generated the SBOM again with syft `0.96.0` and format `spdx-json`, and then I instead get this behaviour. [Here](https://github.com/anchore/syft/files/13402832/syft.spdx.json) is the spdx.json file

```
❯ grype syft.spdx.json
 ✔ Vulnerability DB                [no update available]  
 ✔ Scanned for vulnerabilities     [0 vulnerability matches]  
   ├── by severity: 0 critical, 0 high, 0 medium, 0 low, 0 negligible
   └── by status:   0 fixed, 0 not-fixed, 0 ignored 
No vulnerabilities found
```

**Comment by tgerla** [comment]
Since we haven't heard back we'll go ahead and close this issue since we believe it to be fixed--please re-open or open a new issue if you run into any more trouble!
