### ISSUE TITLE
Invalid SPDX.JSON files according to spdx.org

### ISSUE THREAD

**Issue by PipeItToDevNull** [anchore/syft#2453]
When using Syft in my GithubActions [here](https://github.com/PipeItToDevNull/nginx-certbot/actions/runs/7292755178) the results being generated are invalid according to [SPDX.org' validation tool](https://tools.spdx.org/app/validate/) and their jar tool 

```bash
> java -jar .\spdx-tools-2.2.8-jar-with-dependencies.jar SPDXViewer .\pipeittodevnull-nginx-certbot.spdx.json\pipeittodevnull-nginx-certbot.spdx.json

15:36:48.053 [main] ERROR org.apache.jena.riot - [line: 1, col: 1 ] Content is not allowed in prolog.
Error creating SPDX Document: [line: 1, col: 1 ] Content is not allowed in prolog.
```

I see issues 1401, 1568, and 1616, but I would assume I do not understand something here instead of thinking this application is broken.

If someone could show me a viewer for these files, or explain that these formats are not standardized that would be great.

**Comment by tgerla** [comment]
Hi @PipeItToDevNull, I ran your SPDX file through the online validator and it gave me a few warnings, but no parse errors. The error message that you posted from the Java tool appears to be a mismatch between file formats--is it possible that parser is expecting XML, and you are passing it JSON? The "line: 1, col: 1" leads me to believe that it is immediately failing to parse. Can you verify that the spdx-tools SPDXViewer expects JSON input?

**Comment by PipeItToDevNull** [comment]
Thanks, it seems you are correct on all counts. I appreciate your time

**Comment by tgerla** [comment]
Great, thanks for the update. Let us know if you run into any other problems.
