### ISSUE TITLE
Conan Lock 2.x requires fields support

### ISSUE THREAD

**Issue by houdini91** [anchore/syft#2462]
**What would you like to be added**:
In conan 2.x i see there is a `requries` field listing the packages instead of the `graph_lock`.

For spec change details see https://github.com/conan-io/tribe/blob/main/design/034-new_lockfiles.md. and https://docs.conan.io/2/tutorial/versioning/lockfiles.html#tutorial-versioning-lockfiles.

Example of random conan.lock with this fields.
* https://github.com/openvinotoolkit/openvino/blob/387f4536ec4d931d9a75dce4d4885366583a3968/conan.lock#L3
* https://github.com/fpelliccioni/asio_course/blob/f7d9f22715c3fee264b0b7b79424528fc90ccbae/conan.lock#L3

Link a suggestion PR https://github.com/anchore/syft/pull/2461.

**Comment by tgerla** [comment]
Hi @houdini91, thanks for the report and the pull request! We will take a look as soon as we can.
