### ISSUE TITLE
Mismatch between package name and sourceInfo

### ISSUE THREAD

**Issue by SSJune821** [anchore/syft#2483]
**What happened**:
I scanned my spring boot project using maven. Among the SBOM results, it was confirmed that the file names of sourceInfo and package name were different.
![image](https://github.com/anchore/syft/assets/26968714/90ec7af2-5291-40bd-a1cb-ccae5d647b45)
package name/version is xsdlib/2013.6.1, but sourceInfo is woodstox-core-6.2.4.jar

**What you expected to happen**:
I expected that there would be a package name and sourceInfo matching it.

**Steps to reproduce the issue**:
After adding woodstock-core version 6.2.4 to pom.xml, create a war file through mvn install to create a target folder. Then, create sbom from the entire project folder using the syft program. (I used spdx-json format.)

**Anything else we need to know?**:
N/A

**Environment**: 
- Output of `syft version`: syft 0.100.0
- OS (e.g: `cat /etc/os-release` or similar): Windows 10(22H2) build 19045.3803

**Comment by kzantow** [comment]
Thanks for the report @SSJune821 -- sometimes Java archives contain multiple packages (very common for `.ear`, `.war`, and similar but also can be true for JARs). Would you be able to provide a set of steps to reproduce the problem to make sure we're understanding it correctly?

**Comment by SSJune821** [comment]
> Thanks for the report @SSJune821 -- sometimes Java archives contain multiple packages (very common for `.ear`, `.war`, and similar but also can be true for JARs). Would you be able to provide a set of steps to reproduce the problem to make sure we're understanding it correctly?

@kzantow Yes. I created a Spring Starter project using STS4. And in pom.xml

```
<dependency>
<groupId>com.fasterxml.woodstox</groupId>
<artifactId>woodstox-core</artifactId>
<version>6.2.4</version>
</dependency>
```

Add and create a war file with maven install. After that, target my project folder and run syft <MyProject> --output spdx-json=mybom.json

Thank you

**Comment by tgerla** [comment]
Hi @SSJune821,

Thanks for the details. As a simple test, I downloaded the woodstox-core jar directly and ran Syft on it:

```
tgerla@Timothys-MacBook-Pro-2 syft-2483 % syft .
 ✔ Indexed file system                                                                                                                                     .
 ✔ Cataloged contents                                                                       cdb4ee2aea69cc6a83331bbe96dc2caa9a299d21329efb0336fc02a82e1839a8
   └── ✔ Packages                        [3 packages]
NAME           VERSION   TYPE
isorelax       20090621  java-archive
woodstox-core  6.2.4     java-archive
xsdlib         2013.6.1  java-archive
```

So I believe that this jar file indeed includes both woodstox-core and xsdlib. The `sourceInfo` field is not necessarily going to match the name of every package found, but instead it's a simple text descriptor of the origin of the package. In this case, xsdlib and isorelax are packages found inside the woodstox-core jar, which is what the `sourceInfo` field is saying.

Does this help?

**Comment by spiffcs** [comment]
Just a quick follow up: I checked the syft json response for this the result you're showing in your original example looks correct:
```
    {
      "id": "623ab3ae0e79af29",
      "name": "xsdlib",
      "version": "2013.6.1",
      "type": "java-archive",
      "foundBy": "java-archive-cataloger",
      "locations": [
        {
          "path": "/woodstox-core-6.2.4.jar",
          "accessPath": "/woodstox-core-6.2.4.jar",
          "annotations": {
            "evidence": "primary"
          }
        }
      ],
      "licenses": [],
      "language": "java",
      "cpes": [
        "cpe:2.3:a:xsdlib:xsdlib:2013.6.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:java:xsdlib:2013.6.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:dev:xsdlib:2013.6.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:msv:xsdlib:2013.6.1:*:*:*:*:*:*:*"
      ],
      "purl": "pkg:maven/net.java.dev.msv/xsdlib@2013.6.1",
      "metadataType": "java-archive",
      "metadata": {
        "virtualPath": "/woodstox-core-6.2.4.jar:net.java.dev.msv:xsdlib",
        "pomProperties": {
          "path": "META-INF/maven/net.java.dev.msv/xsdlib/pom.properties",
          "name": "",
          "groupId": "net.java.dev.msv",
          "artifactId": "xsdlib",
          "version": "2013.6.1"
        },
        "pomProject": {
          "path": "META-INF/maven/net.java.dev.msv/xsdlib/pom.xml",
          "parent": {
            "groupId": "net.java.dev.msv",
            "artifactId": "msv",
            "version": "2013.6.1"
          },
          "groupId": "net.java.dev.msv",
          "artifactId": "xsdlib",
          "version": "",
          "name": "MSV XML Schema Library",
          "description": "XML Schema datatypes library"
        }
      }
    }
```

```
      "name": "xsdlib",
      "SPDXID": "SPDXRef-Package-java-archive-xsdlib-623ab3ae0e79af29",
      "versionInfo": "2013.6.1",
      "supplier": "NOASSERTION",
      "downloadLocation": "NOASSERTION",
      "filesAnalyzed": false,
      "sourceInfo": "acquired package info from installed java archive: /woodstox-core-6.2.4.jar",
```

The virutal path in the syft json output shows that this package was pulled from the woodstox-core archive:
```
/woodstox-core-6.2.4.jar:net.java.dev.msv:xsdlib
```

@tgerla is spot on about how `sourceInfo` is being used.
