### ISSUE TITLE
Unable to scan docker.io/rancher/pause

### ISSUE THREAD

**Issue by f16falcon4** [anchore/syft#2486]
**What happened**:
Attempts to scan pause:3.6 result in an empty SBOM. Syft states that no packages can be found.
**What you expected to happen**:
I expect Syft to detect the pause binary.
**Steps to reproduce the issue**:
Option 1: Run syft in image scan mode `syft <image>`.
Option 2: Pull container, export it to tarball, extract tarball, run Syft in directory scan mode `syft </path/to/dir>`
**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: 0.100.0
- OS (e.g: `cat /etc/os-release` or similar): RHEL 8

**Comment by tgerla** [comment]
Hi @f16falcon4, I've taken a look at this image and it seems to only have file, a statically linked binary for "pause", and no other packages that Syft can identify. Syft does have a mechanism to detect binaries, but we currently don't have a classifier for "pause". I'm not familiar with that particular app, but if you can come up with a way to detect, a classifier could be added. Here is the current set of classifiers of known binaries: https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/binary/default_classifiers.go

Hope this helps! Let us know if you'd like to implement a classifier for it and we can help.

**Comment by tgerla** [comment]
We'll close this issue but please feel free to re-open or open a new issue if you need to. Thanks!
