### ISSUE TITLE
Custom configuration file detection

### ISSUE THREAD

**Issue by Vishnu-2810** [anchore/syft#2493]
Custom syft.yaml file is placed in home directory syft is installed in /usr/local/bin i have made some changes in syft.yaml for eg:pretty print true for parent and cyclonedx-json but not getting reflected ...Will there be any configuration files overwriting my changes while execution ?I want to change the max file scan size to 4GB. How to check whether which config file is taken during execution @tgerla @wagoodman 

Please help me to resolve this issue 

Thanks in advance!

**Comment by tgerla** [comment]
Hi @Vishnu-2810, you can run `syft` or `grype` without any arguments and it will show you the exact configuration file paths it uses. You can also explicitly specify a config file with `-c myconfig.yaml` to override the search paths. Hope this helps!
