### ISSUE TITLE
Syft missing linux kernel archives from SBOM results

### ISSUE THREAD

**Issue by 99sao** [anchore/syft#2524]
我想知道如何进行vmlinuz的检测，我对vmlinuz-5.4.0-169-generic的检测并没有任何结果

> I want to know how to detect vmlinuz. My detection of vmlinuz-5.4.0-169-generic did not produce any results.

 _(edit from @wagoodman with google translate output)_

**Comment by tgerla** [comment]
Hi @99sao, can you ask in English? It would be easier for us to help you. Thank you!

**Comment by wagoodman** [comment]
What version of syft are you using @99sao ? I'm seeing an issue with at least the latest syft release (the linux kernel cataloger is not wired up) -- I'll get a fix in for that. But I'm not entirely certain that is what you were running into if you were using an older syft version.
