### ISSUE TITLE
Cataloger dpkg-db is present without "-" in readme in version 0.98

### ISSUE THREAD

**Issue by yogevhenig89** [anchore/syft#2545]
**What happened**:
When using the cataloger like the docs suggests  - dpkgdb not result for this cataloger are found

**What you expected to happen**:
Syft is using this cataloger

**Steps to reproduce the issue**:

**Anything else we need to know?**:
It is working when using it like: "dpkg-db"

**Environment**:
- Output of `syft version`: 0.98
- OS (e.g: `cat /etc/os-release` or similar): ubuntu-focal-20.04-amd64-minimal-20200929

**Comment by spiffcs** [comment]
👋 Hey @yogevhenig89 can you give us an example of what you're trying to do? The docs have changed recently so we might not be working off the same notes.

Here is a valid command that uses "tags" to select the dpkg cataloger:
```bash
syft scan --select-catalogers debian debian:latest
```

Note you can see all catalogers and their related tags by running:
```bash
syft cataloger list
```

**Comment by yogevhenig89** [comment]
Hey, @spiffcs, I know I'm talking about the docs for the 0.98 release. The commands you referencing related to newer versions.

**Comment by tgerla** [comment]
Hi @yogevhenig89, at this point we aren't able to make updates to the docs for previous releases. This may change in the future, but for now, please go ahead and use the latest release, and feel free to let us know if you see any issues with the current docs. Thanks!
