### ISSUE TITLE
syft attest command missing --key flag

### ISSUE THREAD

**Issue by vremy** [anchore/syft#2590]
**What happened**:

I tried to perform an attest with a local cosign key but the `--key` flag is not found as shown in the output below.

```sh
 ~  >> syft attest --output cyclonedx-json --key cosign.key ubuntu:latest
unknown flag: --key
```

**What you expected to happen**:

I expected the `---key` flag to be available so i can use my  local cosign key

**Steps to reproduce the issue**:

1. Install the latest version  of Syft, 0.103.1
2. Create a cosign key in your current directory

```sh
 ~  >> cosign generate-key-pair
Enter password for private key:
Enter password for private key again:
Private key written to cosign.key
Public key written to cosign.pub
```

3. Use the `syft attest` command in combination with the `--key` flag.

```sh
 ~  >> syft attest --output cyclonedx-json --key cosign.key ubuntu:latest
```

**Anything else we need to know?**:

**Environment**:

```sh
 ~  >> syft version
Application: syft
Version:    0.103.1
BuildDate:  2024-01-31T17:09:14Z
GitCommit:  377538e4a692b8070716eb091456b112ccc2cb81
GitDescription: v0.103.1
Platform:   linux/amd64
GoVersion:  go1.21.6
Compiler:   gc
```

```sh
 ~  >> cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

And finally i want to thank you guys for this project :)

**Comment by kzantow** [comment]
This has been fixed in the latest syft (via https://github.com/anchore/syft/pull/2551)
