### ISSUE TITLE
Add syft config command

### ISSUE THREAD

**Issue by kickinranch** [anchore/syft#2598]
**What would you like to be added**:
Right now the syft --help shows all configuration options, which is great, but it's fairly verbose. Ideally the configuration information could be rendered with `syft config` or similar. This could cover not only what values exist based off of the environment and config files but also be able to see what the default config would have rendered as without considering other inputs.

**Why is this needed**:
Make the help easier on the eyes!

**Comment by wagoodman** [comment]
dev note: work for this in the clio lib has been started in https://github.com/anchore/clio/pull/44
