### ISSUE TITLE
Using custom templates to parse output does not work anymore

### ISSUE THREAD

**Issue by amascia-gg** [anchore/syft#2599]
**What happened**:
Starting from `v0.102.0` using templates to parse Syft's output does not work.

**What you expected to happen**:
We get Syft's output data even with a template.

**Steps to reproduce the issue**:
The `README` provides an example of a custom template file `csv.tmpl`:
```
"Package","Version Installed","Found by"
{{- range .Artifacts}}
"{{.Name}}","{{.Version}}","{{.FoundBy}}"
{{- end}}
```

Using this template with Syft v0.102.0 or higher gives a blank csv file:
```
"Package","Version Installed","Found by"
```

whereas on lower version it works.

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release` or similar): MacOS Sonoma 14.3

**Comment by tgerla** [comment]
Hi @amascia-gg, sorry, we need to update the README to match. This is one of the breaking changes in Syft 0.102.0 -- you can read more about it on this issue: https://github.com/anchore/syft/pull/2542 -- the motivation behind this change was to make it easier to write template--previously, the templates accessed the internal Go data structures, but now the template uses the JSON object. You can run `syft -o json ...` to get the JSON version of your SBOM to see the data structure and the fields you have access to.

To solve your problem temporarily (without changing your templates), you can set the environment variable `SYFT_FORMAT_TEMPLATE_LEGACY=1` or make the change in your syft configuration file.

Thank you for letting us know about the outdated README. Please let us know if you have any trouble and we can give you some more advice. Thanks!
