### ISSUE TITLE
Image tag not contain all specified catalogers

### ISSUE THREAD

**Issue by yogevhenig89** [anchore/syft#2656]
**What happened**:
Using syft latest version 0.105.0, when running syft catalogers list I get the table and there are 19 catalogers containing the image tag

alpm-db-cataloger
binary-cataloger
cargo-auditable-binary-cataloger
conan-info-cataloger
dotnet-portable-executable-cataloger
dpkg-db-cataloger
go-module-binary-cataloger
graalvm-native-image-cataloger
java-archive-cataloger
javascript-package-cataloger
linux-kernel-cataloger
nix-store-cataloger
php-composer-installed-cataloger
portage-cataloger
python-installed-package-cataloger
r-package-cataloger
rpm-db-cataloger
ruby-installed-gemspec-cataloger
wordpress-plugins-cataloger

But when trying to use the tag with the following command on some random folder
 ./syft dir:~/Desktop/test -vv --select-catalogers image

I only get that 14 catalogers were used:

alpm-db-cataloger
apk-db-cataloger
dpkg-db-cataloger
portage-cataloger
rpm-db-cataloger
dotnet-portable-executable-cataloger
python-installed-package-cataloger
go-module-binary-cataloger
java-archive-cataloger
graalvm-native-image-cataloger
nix-store-cataloger
binary-cataloger
linux-kernel-cataloger
wordpress-plugins-cataloger

**What you expected to happen**:
Syft use all the catalogers with the image tag

**Steps to reproduce the issue**:

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: 0.105.0
- OS (e.g: `cat /etc/os-release` or similar): MacOs

**Comment by tgerla** [comment]
We'll go ahead and close this issue, but please let us know if you need anything else.
