### ISSUE TITLE
Unable to scan OCI images with syft v0.105.1

### ISSUE THREAD

**Issue by sophiewigmore** [anchore/syft#2678]
**What happened**:

Hey there,
We recently bumped to [v0.105.1](https://github.com/anchore/syft/releases/tag/v0.105.1), and scanning OCI archives is no longer working. It was previously working with v0.105.0.
* Command we ran: `syft scan build/run.oci --output cyclonedx-json=syft-output.json`
* Output: 
```
failed to construct source from user input "build/run.oci": unable to load image: unable to use OciTarball source: failed to visit tar entry="." : potential path traversal attack with entry: "."
```

Any ideas if we're doing something wrong, or if this is just a bug? I didn't see anything concerning in the CHANGELOG for v0.105.1, except potentially https://github.com/anchore/syft/pull/2664

**What you expected to happen**:

Scanning succeeds as usual

**Steps to reproduce the issue**:

1. Get an OCI archive
2. Run `syft scan <OCI archive> --output cyclonedx-json=syft-output.json`

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
```
Application: syft
Version:    0.105.1
BuildDate:  2024-02-26T16:52:59Z
GitCommit:  928511ea0f1449e057e8057e38743d258b22476b
GitDescription: v0.105.1
Platform:   darwin/amd64
GoVersion:  go1.21.7
Compiler:   gc
```

**Comment by spiffcs** [comment]
Thanks for the heads up on this @sophiewigmore! Let me try and reproduce this and come back with an answer as to the cause. I'll also try and get a fix filed asap after determining the failure.

**Comment by spiffcs** [comment]
PR filed in stereoscope - https://github.com/anchore/stereoscope/pull/225

**Comment by spiffcs** [comment]
Fix pulled in here: https://github.com/anchore/syft/pull/2683

**Comment by spiffcs** [comment]
Confirmed fix by pulling the affect build-pack from 
https://github.com/paketo-buildpacks/jammy-full-stack/releases/tag/v0.1.22

```
[I] hal@CPHILLIPS ~/GolandProjects/syft (update-stereoscope)
❯ go run cmd/syft/main.go scan jammy-full-stack-0.1.22-build.oci --output cyclonedx-json=syft-output.json
 ✔ Parsed image                                                                                                                                                                                                   sha256:ae3bdba0314a72fec46ac12cc3e1509475f1257d65ee6b084fd0899d300c39b7
 ✔ Cataloged contents                                                                                                                                                                                                    dc6aae0717a791c676f4837fdee42b5e255829ccf8da5fb643ee2ecc9effab2a
   ├── ✔ Packages                        [718 packages]
   ├── ✔ File digests                    [28,403 files]
   ├── ✔ File metadata                   [28,403 locations]
   └── ✔ Executables                     [1,867 executables]
```

**Comment by spiffcs** [comment]
@sophiewigmore this closed because the PR fixing the issue went in (gh issues with fix keyword close on PR resolve not release 😢 )

Expect to see this in the next syft release - we JUST got out v1.0.0 so I'll coordinate with the team for when v1.0.1 goes out.

If you need this in the immediate term feel free to tag me and I can work with you guys to get a version built from main.

**Comment by sophiewigmore** [comment]
@spiffcs thank you for the quick fix!! you are the best :) 
We can definitely wait for the next release, I'll just roll back the version as-needed until then. Cheers

**Comment by sophiewigmore** [comment]
@spiffcs the new release looks like its working! Thanks again
