### ISSUE TITLE
Add the Common Platform Enumeration (CPE) for the CycloneDX output

### ISSUE THREAD

**Issue by geertvanheusden** [anchore/syft#268]
**What would you like to be added**:
The Common Platform Enumeration (CPE) which is currently missing in the CycloneDX output

**Why is this needed**:
It makes the current CycloneDX report unusable for tools like Dependency Track which uses the CPE to scan for vulnerabilities.

_Dependency Track related message:_
> The internal analyzer evaluates components against an internal vulnerability database derived from the National Vulnerability Database and VulnDB (if enabled). This analyzer makes use of the Common Platform Enumeration (CPE) defined in components. Components with a valid CPE will be evaluated with this analyzer.

**Comment by wagoodman** [comment]
Given that https://github.com/anchore/syft/pull/271 has been merged, looks like this can get picked up now.

Developer note: don't use [this](https://github.com/CycloneDX/specification/blob/master/schema/bom-1.2.xsd#L304-L311) use [this instead](https://github.com/CycloneDX/specification/blob/master/schema/bom-1.2.xsd#L606-L616)

**Comment by wagoodman** [comment]
On second look, I misinterpreted the XML schema; though the type definition still exists in the schema, the usage within components has been explicitly listed as deprecated (https://github.com/CycloneDX/specification/blob/master/schema/bom-1.2.xsd#L307). 

We could add the CPE, however, it seems potentially ill-advised since Syft generates multiple potential CPEs from the underlying raw data, where as the cyclonedx spec allows for a single value --this could be problematic since it would be a guess.

@geertvanheusden do you know if Dependency Track is planning to keep pulling CPEs from CycloneDX documents in the future (or what they may be using in it's place)?

**Comment by geertvanheusden** [comment]
I just did an additional check and apparently applications with a valid PURL are checked against an internal analyser (NVD) as well. I might have misinterpreted the documentation or it is outdated/incorrect. 
@stevespringett maybe you can elaborate on the correct and current behaviour?

**Comment by stevespringett** [comment]
@geertvanheusden I assume you're referring to Dependency-Track? If so DT has a few different analyzers including an internal analyzer (uses CPE for NVD and VulnDB), NPM Advisories (PURL), and OSS Index (PURL).

Findings from OSS Index may be unique (not in the NVD) or may be CVEs. In DT 3.8 and previous, it was unclear what analyzer was attributed to finding a vulnerability on a component. In DT 4.0, attribution is now specifically supported along with a reference URL to the external source of the finding.

More than likely, a CycloneDX BOM was imported and the components had a PURL. If OSS Index was enabled, then those components would additionally be analyzed with the OssIndexAnalyzerTask possibly resulting in CVEs being identified and a NVD label being applied to it. Again, in 3.8.0 and prior, it wasn't super clear what analyzer was attributed to the finding. This is much improved in 4.0 being released later this month.

**Comment by geertvanheusden** [comment]
Thanks @stevespringett for taking the time to provide us with this clear answer. 

Based on the above answer I think it would still be relevant to have the CPE available in the CycloneDX BOM as Dependency Track still uses it to scan for vulnerabilities against two databases. If however it would be a guess as multiple CVE's could be dedicated from the raw-data for one application, it might not be the best solution to have it after all.

**Comment by wagoodman** [comment]
Thanks for the clarity @geertvanheusden / @stevespringett . We are planning on sorting the list of CPEs to be most specific first in the near future, in which case we could put in the "best guess" in the cycloneDX output --not foolproof, but potentially worth while. Until we have that ranking in place I'd suggest leaving out CPE for now (we can leave this issue open too).

**Comment by samj1912** [comment]
Given that https://github.com/anchore/syft/pull/289/files was merged in - would it make sense to add the CPE field in the CycloneDX output?

**Comment by wagoodman** [comment]
Now that sorting by specificity is in I think adding in CPE into the CycloneDX output would be alright 👍 (still not perfect, but probably better than a random guess)
