### ISSUE TITLE
The extension part (metadata) in the output is not according to the CycloneDX specifications

### ISSUE THREAD

**Issue by geertvanheusden** [anchore/syft#270]
**What happened**:

The CycloneDX output format is invalid according to the specs. Version 1.2 of the CycloneDX specification should use the `<metadata>` tag instead of the extension. The snippet (current output of syft) below demonstrates this. 

<?xml version="1.0" encoding="UTF-8"?>
<bom xmlns="http://cyclonedx.org/schema/bom/1.2" xmlns:bd="http://cyclonedx.org/schema/ext/bom-descriptor/1.0" version="1" serialNumber="urn:uuid:68e4a7c5-dc89-482d-9fd3-223bd8002b2e">
  <components>
 ...
 </components>
 <bd:metadata>
    <bd:timestamp>2020-11-18T10:11:12+01:00</bd:timestamp>
    <bd:tool>
      <bd:vendor>anchore</bd:vendor>
      <bd:name>syft</bd:name>
      <bd:version>0.8.0</bd:version>
    </bd:tool>
    <bd:component type="container">
      <name>image-xyz</name>
      <version>sha256:cbdee75f57018631712246e91054b89fc6ec3f13215cf00a749256e80bd67ddd</version>
    </bd:component>
  </bd:metadata>
</bom>

**What you expected to happen**:

The output should have a valid structure according to the specs. More info and an example can be found over here:
* https://cyclonedx.org/ext/bom-descriptor/
* https://cyclonedx.org/use-cases/#packaging-and-distribution

**How to reproduce it (as minimally and precisely as possible)**:

By using the CycloneDX output format with syft on an image. 

**Anything else we need to know?**:

I noticed this issue while importing the CycloneDX BOM into Dependency Track.
A ticket was incorrectly reported over here https://github.com/DependencyTrack/dependency-track/issues/841.

**Comment by wagoodman** [comment]
Good call, this looks like a relatively easy fix. We should also check why this passed schema validation (I think it was seen as an extra tag, so was allowed, thus not verified... sounds like we need an extra check in place here)
