### ISSUE TITLE
Syft reports some fw* pckages, which are nowhere to find

### ISSUE THREAD

**Issue by DanielRuf** [anchore/syft#2753]
**What happened**:

Syft returns a list, which contains some fw* packages like fwerror. But we can not find any Maven package with this name.

Is this some bug?

![grafik](https://github.com/anchore/syft/assets/827205/c5ff1626-6dc4-400f-ae9f-ad89f72e5126)

**What you expected to happen**:

To correctly report the used dependencies.

**Steps to reproduce the issue**:

**Anything else we need to know?**:

**Environment**: Linux (Ubuntu 22.04 LTS)
- Output of `syft version`:
```
Application: syft
Version:    1.1.0
BuildDate:  2024-03-25T21:41:42Z
GitCommit:  f4e18961b979f5e6d0cc3b1e4fce608c8ceb29d8
GitDescription: v1.1.0
Platform:   linux/amd64
GoVersion:  go1.21.8
Compiler:   gc
```
- OS (e.g: `cat /etc/os-release` or similar):

```
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by tgerla** [comment]
Hi @DanielRuf, thanks for the report. What exactly are you scanning? We will at least need to see the full directory contents that you are scanning to troubleshoot. We will also need to see the JSON output of the Syft run. Please run `syft ./ -o json > output.json` and attach the output.json to this issue, and we will be happy to take a look.

**Comment by DanielRuf** [comment]
@tgerla thanks for the swift reply.

I have checked the generated file and it lists `/krad.web/lib/com/xyz/za/fwerror/1.0/fwerror-1.0.jar`.

`xyz` is a replacement for the customer name.

I will check with the project team internally (if the mentioned path is really there or not) to clarify if this is a bug or not.

**Comment by DanielRuf** [comment]
It seems they were really placed there. Closing since I was not aware of the fact, that compiled Java classes as jar files were placed there.

Sorry for taking your time.

**Comment by tgerla** [comment]
No problem! Thanks for the update and let us know if you run into anything else.
