### ISSUE TITLE
Introduce an additional command line switch so that syft command understands I am passing a directory

### ISSUE THREAD

**Issue by subhammisra45** [anchore/syft#277]
<img width="1680" alt="Screenshot 2020-11-21 at 12 17 46 PM" src="https://user-images.githubusercontent.com/22505845/99869832-22c0b000-2bf4-11eb-9f75-e58ac6e60c25.png">
**What would you like to be added**:
Introduce an additional command line switch so that syft command understands I am passing a directory
**Why is this needed**:
even if , when I am running the syft command from a directory where my target directory exists, if it doesn't have an extension, it tries to pull  an image by that directory name.

**Comment by luhring** [comment]
Hi @subhammisra45! Syft can do that today, actually. When specifying the directory or image source to scan, you can prefix your input with a "scheme", which tells Syft explicitly how to interpret your input, which means it won't try to guess.

For your example, you should be able to run `syft dir:/docker/tmp`. The `dir` scheme supports relative paths, too, so if your working directory is already `/docker`, you can run `syft dir:tmp`.

More information on scheme options can be found if you run `syft help`, under the section _"You can also explicitly specify the scheme to use"_.
