### ISSUE TITLE
Cannot parse field from line: '======='

### ISSUE THREAD

**Issue by luoyimu1** [anchore/syft#280]
**What happened**:

[0012] ERROR failed to catalog: 1 error occurred:
* unable to catalog python package=/usr/lib/python3/dist-packages/filelock-3.0.10.egg-info/PKG-INFO: cannot parse field from line: '======='

**What you expected to happen**:
this should not be an error..
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Dockerfile:
FROM python:3.9-slim AS base

ARG PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y \
    git \
 && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    libldap2-dev \
    libsasl2-dev \
    ldap-utils \
    tox \
    lcov \
    valgrind \
 && rm -rf /var/lib/apt/lists/*

RUN pip install -U pip pipenv

ADD Pipfile* /tmp/
WORKDIR /tmp
RUN pipenv install --system --ignore-pipfile

ADD src/ /app/

WORKDIR /app
RUN useradd -m -u 777 mrdocker \
    && chown mrdocker:mrdocker /app

##----------------------------------------------------------------------

FROM base AS runtime

USER mrdocker

LABEL maintainer="Security"

ENTRYPOINT ["python3", "main.py"]

**Environment**:
- Output of `grype version`:0.5.0
- OS (e.g: `cat /etc/os-release` or similar): Linux

**Comment by luhring** [comment]
>Separately, the PKG-INFO file in 3.0.12 has another characteristic that Syft might not be handling correctly — specifically, the contents of a markdown file (the packages README.md) is appended to the end of the file without a specifying field. We're looking into the spec to determine if this is correct or also a malformation.

It turns out **Syft does handle this case correctly**. (Syft parsing should end for a given file when it encounters a new blank line, and it does).

**Comment by luoyimu1** [comment]
Hey @luhring,
Thanks a lot for the info:)
From the docker log i can see the initial installed version is 3.0.10 which caused the issue here, and it updates to 3.0.12 during "pip install -U pip pipenv" stage, but grype still catch up with the 3.0.10 PKG-INFO (I couldn't find 3.0.12 PKG-INFO in the filesystem either).
Do you have any suggestions on how we could possibly fix it?
Cheers,
