### ISSUE TITLE
Unable to pull/analyze docker image as of 0.9.0

### ISSUE THREAD

**Issue by wlfshmn** [anchore/syft#284]
**What happened**:

As of syft 0.9.0, pulling certain images fails.
```
# syft quay.io/coreos/kube-state-metrics:v1.7.2
 ⠙ Loading image         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  [saving image to disk]
 ⠋ Parsing image         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 
[0000] ERROR failed to catalog input: could not fetch image 'quay.io/coreos/kube-state-metrics:v1.7.2': could not read image: layer read failed: FileCatalog doesn't have an entry for all files in FileTree
```

**What you expected to happen**:

A successful pull and analysis, as happens with 0.8.0 (no packages found, but analysis is sucessfull). Docker pulls the image just fine.

**How to reproduce it (as minimally and precisely as possible)**:

syft quay.io/coreos/kube-state-metrics:v1.7.2

**Anything else we need to know?**:

All v* tags I've tried of that image are broken back to v1.6.0, which works. 1.6.0 was Alpine based and 1.7.0 and later appear to be based on distroless. However, the v2.* and latest tags work, and are also based on distroless.

**Environment**:
- Output of `syft version`:
```
Application:   syft
Version:       0.9.1
BuildDate:     2020-12-02T23:06:31Z
GitCommit:     6f9ded60ed144de3e837effdee5d96366441e7d3
GitTreeState:  clean
Platform:      linux/amd64
GoVersion:     go1.14.12
Compiler:      gc
```

- OS (e.g: `cat /etc/os-release` or similar):
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by wagoodman** [comment]
@wlfshmn thanks for reporting! We'll be releasing v0.9.2 shortly that addresses this.
