### ISSUE TITLE
Very High Memory Usage Using Syft

### ISSUE THREAD

**Issue by dor-hayun** [anchore/syft#2942]
**What happened**:
High memory consumption when scanning 5GB image

**What you expected to happen**:
controlled memory consumption

**Steps to reproduce the issue**:
scan very big sized images and check the memory consumption

**Anything else we need to know?**:
<img width="966" alt="image" src="https://github.com/anchore/syft/assets/94103962/31ee5fa8-6c02-4bfd-9fcd-776159564634">

**Environment**:
- Output of `syft version`: 1.5.0
- OS (e.g: `cat /etc/os-release` or similar):
seems like there are many dotnet packages in the images

**Comment by abhiseksanyal** [comment]
See also - https://github.com/anchore/stereoscope/issues/233#issuecomment-2159190475

**Comment by willmurphyscode** [comment]
We'll track this work over at https://github.com/anchore/stereoscope/issues/233, since this is really a stereoscope issue.
