### ISSUE TITLE
Hello brother, about how to associate the components in spdx json. json packages with Layers

### ISSUE THREAD

**Issue by limaonet** [anchore/syft#3022]
I am a beginner and I am not sure if the type of question I submitted is correct

I want to retrieve which Layer the component comes from in spdx JSON. Can you help me

**Comment by kzantow** [comment]
Hi @limaonet, we are looking at how to best expose this information. Issue #435 is where we will track the work, so if you are interested in this feature, vote and follow that issue. I'm going to close this as a duplicate.
