### ISSUE TITLE
Syft Not reading components with Dots in Names from requirements.txt

### ISSUE THREAD

**Issue by Ajit-15** [anchore/syft#3080]
**What happened:**
Syft fails to read and process components listed in requirements.txt if the component names contain dots ("."). This leads to incomplete dependency analysis and compliance issue.

**What you expected to happen:** Ideally it should read all the dependencies from requirements.txt. 

**Steps to reproduce the issue:** Create a requirements.txt using below dependencies and run the syft tool, you will observe that those components wont be there in output.
zope.event==5.0
zope.interface==6.4.post2

**Anything else we need to know?:** Using command - Syft scan dir:. --scope AllLayers -o json> ./Syft-output.json

**Environment**:
Windows, running syft on command line

**Comment by popey** [comment]
This looks to be fixed by pr #3070

**Comment by Ajit-15** [comment]
Thank you for Quick action. :)

**Comment by Ajit-15** [comment]
Would it be possible to kindly provide the timeline information for the newer version?

**Comment by kzantow** [comment]
Hi @Ajit-15 a new version of Syft is out with this change: https://github.com/anchore/syft/releases/tag/v1.10.0
