### ISSUE TITLE
UT TestParseRpmFiles is failing

### ISSUE THREAD

**Issue by TimBrown1611** [anchore/syft#3100]
**What happened**:
I am running make unit and the test of TestParseRpmFiles is failing. 
This is the error I see:
```
--- FAIL: TestParseRpmFiles (0.00s)
    --- FAIL: TestParseRpmFiles/test-fixtures/rpms (0.00s)
        parse_rpm_archive_test.go:93: Specific Differences:
            {[]pkg.Package}:
            	-: [Pkg(name="abc" version="0:1.01-9.hg20160905.el7" type="rpm" id="") Pkg(name="zork" version="0:1.0.3-1.el7" type="rpm" id="")]
            	+: []
            
        parse_rpm_archive_test.go:93: unexpected packages from parsing (-expected +actual)
              []pkg.Package(
            - 	{
            - 		s`Pkg(name="abc" version="0:1.01-9.hg20160905.el7" type="rpm" id="")`,
            - 		s`Pkg(name="zork" version="0:1.0.3-1.el7" type="rpm" id="")`,
            - 	},
            + 	nil,
              )
FAIL
```
**What you expected to happen**:
UT should pass, the environment I am running the test is clean.
**Steps to reproduce the issue**:
Pull the main and run make unit
**Anything else we need to know?**:
Thanks!
**Environment**:
- Output of `syft version`: main (1.10.0)
- OS (e.g: `cat /etc/os-release` or similar): linux

**Comment by kzantow** [comment]
Hey @TimBrown1611 would you be able to retest this? We made some recent changes to test fixtures, and belive this to be fixed now.
