### ISSUE TITLE
Create a tekton task for syft

### ISSUE THREAD

**Issue by luhring** [anchore/syft#313]
It'd be great to integrate with the [tekton](https://tekton.dev/) ecosystem as a _task_, so that people can easily use Syft in their tekton pipelines.

At the time of writing, there are only 3 tasks in the category of "security" in the [tekton catalog](https://hub-preview.tekton.dev/).

See here for details: https://github.com/tektoncd/catalog#tekton-catalog

**Comment by ScottChapman** [comment]
This would be really important for us as well, we are developing a company wide tekton based pipeline solution. Clearly we can roll our own, but having this available for folks to use would be nice

**Comment by developer-guy** [comment]
I want to work on this issue, can you please assign it to me @luhring? :)

**Comment by luhring** [comment]
Similar issue for Grype: https://github.com/anchore/grype/issues/232

**Comment by wagoodman** [comment]
@developer-guy are you still interested in working on this issue? If so, no rush! Just trying to get a pulse on this issue 👍

**Comment by developer-guy** [comment]
yes of course 🚀

**Comment by developer-guy** [comment]
https://github.com/tektoncd/catalog/pull/895/commits/ff56730497cbf80b6e9c1fdcb03d48097e3f87b3

I've completed the syft one 🙋🏻‍♂️

**Comment by spiffcs** [comment]
@developer-guy highest of fives!

**Comment by wagoodman** [comment]
Tracking @developer-guy PR here 🎉  https://github.com/tektoncd/catalog/pull/895

**Comment by developer-guy** [comment]
we can close this one due the PR above is merged 🥳🕺🏻

**Comment by wagoodman** [comment]
🎊
