### ISSUE TITLE
Missing support for path prefixes during import to Anchore API

### ISSUE THREAD

**Issue by luhring** [anchore/syft#315]
This means that Syft's import feature **does not work** with the standard way we deploy Enterprise via Helm, where the API paths should be prefixed with `/v1/`. For details on the chart config, see https://github.com/anchore/anchore-charts/blob/8ff7bc108290ce07a6f2d92db5aa1be11985dc23/stable/anchore-engine/templates/enterprise_ui_configmap.yaml#L20

We're finding that users are trying to specify path prefixes with the host parameter (e.g. `-H` on the CLI), such as `https://mydeployment.example.com/v1`.

At a minimum:

1. We need a way to allow the user to specify path prefixes as they tell Syft where their deployment is located (we should **not** assume that the user's API is deployed at a root path for a hostname).
1. We need to ensure users have a smooth interaction with Anchore Enterprise by default.

**Comment by zhill** [comment]
This is a combination of a specific ingress config (combined UI and API, which isn't required, you can use 2 ingresses), and Anchore's service path optimization that makes /v1/ optional by rewriting /v1/ as a prefix internally. The API definition itself is versioned with /v1 prefix for that version of the API.

But supporting arbitrary prefixes on the routes will help general compatibility with various ingress/routing options between the system and syft.
