### ISSUE TITLE
SBOM generated from poetry lock file contains no license information on any dependencies

### ISSUE THREAD

**Issue by nfelt14** [anchore/syft#3204]
**What happened**:

I am unable to generate an SBOM that contains license information on dependencies from a poetry lock file.

**What you expected to happen**:
I would expect an SBOM to contain license information.

**Steps to reproduce the issue**:

1. Use poetry to generate a lock file
2. perform a scan on the file

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: 
```
Application: syft
Version:    1.11.1
BuildDate:  2024-08-20T16:25:20Z
GitCommit:  95b4a88256bddebb91831250f28f602f8c36552a
GitDescription: v1.11.1
Platform:   windows/amd64
GoVersion:  go1.22.6
Compiler:   gc
```
- OS (e.g: `cat /etc/os-release` or similar): Windows/Ubuntu

**Comment by nfelt14** [comment]
There is also no license information for any of the GitHub actions that are used in the repo.

**Comment by spiffcs** [comment]
Thanks @nfelt14 for the issue! I didn't know `poetry.lock` allowed for a field that contained license metadata. I tried searching for the specific documentation outlining the `poetry.lock` specification and only found this:
https://github.com/orgs/python-poetry/discussions/6763

Do you have an example project with a lot of licenses we could use as a basis for development?

The only example I could find in our org has a single license `unknown`
```
[package.extras]
license = ["ukkonen"]
```

**Comment by nfelt14** [comment]
We are trying to generate SBOMs for this repo: https://github.com/tektronix/tm_devices

The workflow is here: https://github.com/tektronix/tm_devices/actions/workflows/sbom-scan.yml

After I spent more time looking into it, it may be a lack of information that poetry provides, so I don't know if there is much that can be done on this side.

**Comment by spiffcs** [comment]
No worries! This looks like a good candidate for https://github.com/anchore/syft/issues/1115

- If there is a url we can use from the poetry lock we can probably enhance the cataloger to color in this license information if you're running syft in an environment where you don't care about network connections going out to find more information about what is being cataloged into the SBOM.

**Comment by nfelt14** [comment]
> No worries! This looks like a good candidate for #1115
> 
> * If there is a url we can use from the poetry lock we can probably enhance the cataloger to color in this license information if you're running syft in an environment where you don't care about network connections going out to find more information about what is being cataloged into the SBOM.

That would work great!

**Comment by spiffcs** [comment]
Tagged this in #1115 closing as it will be implemented as a part of that issue.
