### ISSUE TITLE
Cataloger for Rust crates from Cargo.lock

### ISSUE THREAD

**Issue by westonsteimel** [anchore/syft#338]
**What would you like to be added**:
It would be great to have the ability to catalog rust crates from Cargo.lock files.

**Why is this needed**:
It would increase the accuracy of the BOM generated by syft

**Additional context**:
I started looking a bit into what this would entail in a branch at https://github.com/westonsteimel/syft/tree/rust-cargo-cataloger.  I wasn't really sure on naming for `syft/pkg/type.go`, I went with `rust-cargo` for the moment, but I think it should probably just be `cargo` or maybe just `rust` as I see it is just `python` for PythonPkg and cargo is that canonical way to manage packages in the rust ecosystem.  

I also made PR https://github.com/package-url/packageurl-go/pull/24 to add support for rust to the go package url module that this project uses, but it looks like @wagoodman already has a request out there for modification to it for debian packages that has been there for awhile so I doubt that would be merged anytime soon, if ever.

**Comment by westonsteimel** [comment]
Anyways, I'll probably keep hacking on this when I have a chance, but figured it would be good to get an issue out to track and so that others can provide feedback etc or take it up if they want and I'm moving too slowly.

**Comment by luhring** [comment]
@westonsteimel Excellent suggestion! It would be very nice to support the Rust/Cargo ecosystem.

I looked at your branch, and it looks quite good. Re "what to call the type / ecosystem?", we struggle with this ourselves. But I think this branch is good enough to open up a Syft PR, and we can have the team look at it and go from there.

I really appreciate you putting this together!
