### ISSUE TITLE
Add hyphen replacement in CPE generator

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#361]
Today the CPE generator in anchore-engine [substitutes `-` for `_` within product names](https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/policy_engine/engine/loaders.py#L1132) for a candidate CPE for java packages --Syft should make the same replacement when [generating candidate names](https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/cpe.go#L109).

**Comment by zhill** [comment]
I don't think this needs to be constrained only to java packages. Reviewing the NVD CPE dictionary, it is very rare to find hyphens in the product name (there are some, even within the commons-* java libs from apache). I think the right solution is to present both as potentially valid CPEs for the package in cases where syft is trying to predict possible CPEs (e.g. not a more pointed or lookup-based solution).
