### ISSUE TITLE
Malformed Python package metadata can cause parse failure

### ISSUE THREAD

**Issue by fazalmajid** [anchore/syft#365]
**What happened**:

     ✔ Vulnerability DB     [no update available]
     ✔ Loaded image         
     ✔ Parsed image         
     ⠼ Cataloging image     [packages 0]
    [0020] ERROR failed to catalog: 1 error occurred:
            * unable to catalog python package=/usr/local/lib/python2.7/site-packages/GeoIP-1.3.2.dist-info/METADATA: cannot parse field from line: '		       Version 2.1, February 1999'

**What you expected to happen**:

Warn or at least stop parsing when the malformation is encountered

**How to reproduce it (as minimally and precisely as possible)**:

Run syft on an image that has the MaxMing GeoIP module version 1.3.2 installed

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:

    Application:   syft
    Version:       [not provided]
    BuildDate:     [not provided]
    GitCommit:     [not provided]
    GitTreeState:  [not provided]
    Platform:      darwin/amd64
    GoVersion:     go1.16.2
    Compiler:      gc

- OS (e.g: `cat /etc/os-release` or similar):

Mac OS X Mojave

**Comment by fazalmajid** [comment]
Here is the offending METADATA file (renamed METADATA.txt due to Github attachment filename limitations)

[METADATA.txt](https://github.com/anchore/syft/files/6236764/METADATA.txt)

**Comment by luhring** [comment]
@fazalmajid Thanks for the report — just to start with, what version of Grype are you running? Based on the output of `grype version` it looks like you aren't using a released version. If you built from source, which commit did you use?

**Comment by fazalmajid** [comment]
I built from source using `go get github.com/anchore/syft` and `go get github.com/anchore/syft` so I got whatever was on the master branch around the time I filed the report.

**Comment by fazalmajid** [comment]
I'm sorry, the error was actually in Grype (hence the message about downloading the bulnerability database), Syft does in fact only generate a warning.

I recompiled grype from master and it no longer generates the error
