### ISSUE TITLE
Use of asterisk (*) in CPEs leading to many false positives in vulnerability matching

### ISSUE THREAD

**Issue by luhring** [anchore/syft#396]
It would be ideal to find ways to minimize the use of stars (a.k.a. asterisks / `*`) in CPE fields in generated CPEs to minimize the number of false positives in downstream vulnerability matching.

The ultimate goal is to reduce the count of false positives that Grype produces. The amount of FP reduction considered acceptable will be a judgment call by the team.

We'll need a feedback loop, where we can make targeted changes to Syft's CPE-generation logic and evaluate if that had the intended effect of reducing false positives in Grype's matching.

Strategies to consider trying:

1. ~Replace all `*` (any) with `-` (N/A).~
2. Do the above replacement for only the VENDOR field.

Use the available test harness tooling to get the results for any given change made.

**Comment by zhill** [comment]
Anchore Engine's legacy scanner generates vendor fields as wildcard (or ANY) by default. This is done because we have not found reliable ways to predict a vendor name from many kinds of package metadata. Removing this may cause missed matches in a vulnerability scan in [Grype](github.com/anchore/grype).

**Comment by wagoodman** [comment]
@zhill it may mean that as we run across cases for particular ecosystems or package types that we selectively allow for an "ANY" vendor value, but it seems that there are strong indications that this is currently doing more harm than good when applied as a vendor candidate value for all packages.
