### ISSUE TITLE
commandConn warnings when using remote Docker instance

### ISSUE THREAD

**Issue by alfredodeza** [anchore/syft#398]
The following happens when I run any syft command:

```
go run main.go -vvvv -o json alpine:latest > /tmp/alpine.json
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed
```

Problem does not show at commit c02ab88d5f88c6214a8a067093c98165a4775529

But does show with c363b2b53257ffb3cf82f98eeaaf1482c463ee79

It also doesn't show when using a local Docker instance or when prefixing the image with `registry:`

**Comment by spiffcs** [comment]
Ran this locally on tip of main and no warning was generated.
![Screen Shot 2021-11-12 at 1 02 41 PM](https://user-images.githubusercontent.com/32073428/141513671-848b586c-8361-4f2c-b292-4fd369d25f41.png)

**Comment by alfredodeza** [comment]
@spiffcs interesting... did you have a _remote_ Docker instance as well? This problem only showed up when using a remote Docker instance (I believe over SSH).

**Comment by spiffcs** [comment]
Ooo thanks for the additional context here. Let me check using a remote docker instance.

**Comment by luhring** [comment]
Hi @alfredodeza !

**Comment by alfredodeza** [comment]
I'm probably the only poor soul to run Docker over ssh and getting those messages from `syft` anyway

**Comment by spiffcs** [comment]
Yea setting up an environment now to replicate it locally. Thanks for jumping in with the SSH hint!.

**Comment by tgerla** [comment]
I'm going to close this old ticket but please feel free to re-open if it's still a problem!
