### ISSUE TITLE
Assume `:latest` tag implicitly

### ISSUE THREAD

**Issue by DannyBen** [anchore/syft#411]
**What would you like to be added**:

I would like to be able to specify a docker image, without using the `:latest` tag.

**Why is this needed**:

This is the practice in all other docker CLI tools, and in `Dockerfile`.

**Additional context**:

Whenever running `syft image_name`, and there are more than one tags for this image, syft fails with this message:

```
$ syft alpine
 ✔ Loaded image
failed to determine image source: could not fetch image 'alpine': cannot process multiple docker manifests
```

I expect this command to assume I meant `alpine:latest` and not `alpine:*`

**Comment by luhring** [comment]
Related to https://github.com/anchore/grype/issues/215

**Comment by wagoodman** [comment]
Indeed, we can do this in the stereoscope lib for the docker and registry image providers:
- https://github.com/anchore/stereoscope/blob/main/pkg/image/docker/daemon_provider.go#L42
- https://github.com/anchore/stereoscope/blob/main/pkg/image/oci/registry_provider.go#L26

filling in the tag for the given reference if there is no tag or digest provided.

**Comment by spiffcs** [comment]
This should be closed now with the latest stereoscope update:
https://github.com/anchore/stereoscope/pull/136
