### ISSUE TITLE
Ability to stop scanning

### ISSUE THREAD

**Issue by gmmvllfrt** [anchore/syft#415]
**Ability to be able to stop while scanning**:
*When the user just mistakenly scan the file*

**Comment by luhring** [comment]
Hi @furrpleTtalgi, I'm not sure exactly what you're asking for.

With "stop while scanning", do you mean to exit from the process early?

If so, hitting `Ctrl+C` while the app is running should do the trick. Can you give that a try and let me know if that addresses your need?

**Comment by spiffcs** [comment]
I'm going to close this issue since we have a a good way to quit scanning. If there is anything we're missing or a new feature needed we can always reopen the issue
