### ISSUE TITLE
How to join the Anchore Community Slack?

### ISSUE THREAD

**Issue by JamieMagee** [anchore/syft#423]
**What happened**:

I followed the link in the issue template. The Anchore community slack only allows registrations from `@anchore.com`, `@nvidia.com`, and `@cisco.com` email addresses.

**What you expected to happen**:

The ability to register

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by luhring** [comment]
Hi @JamieMagee, great catch. And sorry for the awkward experience!

It looks like we're direct-linking to specific Slack channels, which causes non-authenticated users to be redirected to the page you're seeing. Anchore's "join link" for Slack is https://anchore.com/slack. We'll make an update to the issue template to make sure outsiders can easily come in. 😃
