### ISSUE TITLE
Distro not detected for centos:6

### ISSUE THREAD

**Issue by fikery** [anchore/syft#429]
1. on linux os
2. docker pull centos:6
3. syft centos:6 -o json
4. distro data is null
![图片](https://user-images.githubusercontent.com/32973757/120615176-976d8480-c48a-11eb-8672-33d25337058d.png)

**Comment by luhring** [comment]
Hi @fikery, thanks for the issue! When I try to reproduce, I find that Syft _can_ scan the image, but it's not correctly detecting the distro, as shown in your screenshot. Specifically, the values are empty strings (not null). I think that might be what you're reporting, but wanted to make it clear what kind of failure is occurring.

This is a good find, and this is certainly a bug.

**Comment by dakaneye** [comment]
Reproducing logs:
```
[0003] DEBUG No Refs found from path: /etc/os-release
[0003] DEBUG No Refs found from path: /usr/lib/os-release
[0003] DEBUG No Refs found from path: /bin/busybox
[0003]  INFO could not identify distro
```

During the catalog packages stage of syft’s execution, the tool tries to grab the distro information of one of the above files, however in the `centos:6` image, none of those files appear to exist:

I ran the image locally via `docker run -it —rm centos:6 tail -f /dev/null` and exec’d into the container
```
[root@ff38ba4cdd97 /]# ls /etc | grep release
centos-release
redhat-release
system-release
system-release-cpe
```

Furthermore, each of those files has much less information than centos normally has in it’s `/etc/*-release` file:

```
[root@ff38ba4cdd97 /]# cat /etc/*release
CentOS release 6.10 (Final)
CentOS release 6.10 (Final)
CentOS release 6.10 (Final)
```

*Problem areas in the code:*

In `distro.Identify`, we aren’t looking in the right files for `centos:6` (for newer versions, starting with centos7,  there appears to be an os-release file, so we should be fine there). Perhaps we should add an option for one of the release files that DO exist in the centos:6 image, or look somewhere else for the version. This link suggests there are a few other ways to check as well: https://linuxconfig.org/how-to-check-centos-version, but may require some more work besides just checking the release file.

Also in the parsing of the actual release file, we probably need to be able to interpret the one-line answer for one of the release files that exist there. (Or, if we use a different method to check, we need to be able to parse that data, see distro.parseOsRelease).

**Comment by wagoodman** [comment]
Good catch folks, I think the next best fallback is to check the `/etc/system-release-cpe` file:

```bash
$ cat /etc/system-release-cpe
cpe:/o:centos:linux:6:GA
```

which is available on centos 6, however, not on centos 5 (I realize not mentioned here but wanted to point it out for completeness). We can always fall back on more specific-case parsing for earlier versions of centos and still use the `/etc/redhat-release` file.
