### ISSUE TITLE
Only "top level" lock files should be inspected for NPM packages

### ISSUE THREAD

**Issue by luhring** [anchore/syft#431]
Preface: This is on the border of "enhancement" and "bug", depending on how you look at it.

---

Today, when looking for NPM-related lock files (`package-lock.json` and `yarn.lock)`, Syft finds files with these names at any location in the file tree, and then it parses each found file for a list of packages and their versions.

According to the [`package-lock.json` docs](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#package-lockjson-vs-npm-shrinkwrapjson) and the [`yarn.lock` docs](https://classic.yarnpkg.com/en/docs/yarn-lock/#toc-current-package-only), lock files found for a project's dependencies (i.e. not for the project itself) **should be ignored entirely**. In other words, only a project's **_top-level_ lock file** will ever be used by the tooling, and, of particular importance for Syft, during installations and builds for that project.

Today these lock files are used during directory scans and not during image scans. This fact may change in the future, but still, it's worth considering a possible relationship between the implementation of _this issue_ and the implementation of configurable cataloging methods.

Lock files are used for directory scans because the primary use case for directory scans is to scan a software project, typically from the root of a repository.

With this in mind, it could easily be considered **more correct** to surface only the top-level lock files' contents, both for SBOM generation and for downstream vulnerability matching. That is, a project's dependencies — even in the exhaustive sense — **would not** include packages found in lower-level lock files but not found in the top-level lock file. This is important when it comes to creating an SBOM (answering "what software ships with this project?") and identifying vulnerabilities (answering "what vulnerabilities would be present when this code is packaged up and published?").

**IMPORTANT:** While various implementations are possible, implementers should strongly consider the potential for their solution to cause Syft not to find valid packages. The intent of this bug is to reduce false positives, but it would be easily possible to produce a solution that introduces false negatives, which should be avoided if possible.

**Comment by kzantow** [comment]
I would suggest the "correct" way to handle this is to exclude any of these lock files found in the `node_modules` directory trees, specifically. The user might have multiple projects in the same repository, etc..

**Comment by luhring** [comment]
See this [thread from our community Slack](https://anchorecommunity.slack.com/archives/C027JE5M345/p1629292882017100) for specific user pain caused by this. (from 2021-08-18)

**Comment by wagoodman** [comment]
Assuming that the fix is not to process any javascript lock files (packages-lock.json and yarn.lock) that are anywhere within a `node_modules` directory, a possible fix for this would be to return no packages from these parsers ([yarn lock parser](https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/javascript/parse_yarn_lock.go#L37) and [package lock parser](https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/javascript/parse_package_lock.go#L31)) if the given path (the first argument to these functions) contains `node_modules/` at all.

**Comment by kzantow** [comment]
NOTE: we'll want to release a new version to get grype updated so the actual [end-user reported issue is fixed](https://github.com/anchore/grype/issues/385)
