### ISSUE TITLE
Make read directly from a path on disk work as good as container

### ISSUE THREAD

**Issue by yudong** [anchore/syft#440]
**What would you like to be added**:
syft can pick up RPM packages from /var/lib/rpm/Packages correctly when scanning a container image.

But syft package dir:/var/lib/rpm -o json on a host server would report 0 packages

**Why is this needed**:
Create SBOM for host server in addition to SBOM for containers.

**Additional context**:
syft is amazing for containers. It would be great to reuse its existing capabilities on host server scan. So that user can have a single tool to meet both host and container SBOM need.

**Comment by bureado** [comment]
Looks like #442 made it to `master` earlier, I was able to generate SBOMs for RPM-based distros using `dir:` with that branch.
