### ISSUE TITLE
Temp data not cleaned up upon SIGINT

### ISSUE THREAD

**Issue by luhring** [anchore/syft#450]
Throughout Syft's execution, it writes and reads temporary data on disk. When Syft receives the signal SIGINT, it should gracefully exit, which includes removing any temp data that it had written, but Syft doesn't do this.

**Comment by wagoodman** [comment]
PR https://github.com/anchore/syft/pull/448 will address this problem at a bare minimum by using `stereoscope.Cleanup` once an interrupt is received. 

Ideally the workers should have a coordinated shutdown by passing context to indicate a cancellation intent and allowing the happy path to drive temp dir/file cleanup (and happy path cleanup should not use global state for tracking temp files).

I'm leaving these closed PRs here for reference, they may or may not be part of a solution to solve this later:
- https://github.com/anchore/stereoscope/pull/71
- https://github.com/anchore/syft/pull/449

**Comment by wagoodman** [comment]
As of right now I'm not seeing evidence of syft leaving temp files on disk when SIGINT is received (something that is partially handled in `anchore/clio` and the other part in syft itself. We are passing context through many levels, but not all levels, to help coordinate shutdown.
