### ISSUE TITLE
Some package licenses are not being reported in the SPDX format

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#460]
**What happened**:
`syft ubuntu:latest -o json` reports that the adduser package has a license of `GPL-2` , but with the SPDX format the license is listed as NOASSERTION.

**What you expected to happen**:
The SPDX output should have reported the correct SPDX identifier (`GPL-2.0`).

**Comment by spiffcs** [comment]
PR here https://github.com/anchore/syft/pull/509
