### ISSUE TITLE
Remove go and rust catalogers from image cataloger set

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#464]
Today catalogers used on images attempt to discover installed packages, where as the separate set of catalogers used for directories don't have this requirement. The Go and Rust catalogers are against manifest files that are used in source repos and are not present when installing build artifacts to a target system. This implies that these catalogers should be removed from the list of catalogers used for container images (but still remain on the list for directory scans).

**Comment by zhill** [comment]
I'd like to see these as optional (off by default) so that for use cases where it does make sense they are available.

**Comment by luhring** [comment]
> I'd like to see these as optional (off by default) so that for use cases where it does make sense they are available.

@zhill For the scope of this issue, let's simply remove them. I like the idea of catalogers being optional, and that functionality is described in a separate issue (https://github.com/anchore/syft/issues/465). 👍

**Comment by spiffcs** [comment]
> #465

Cool, I'll follow up with the configuration aspect right after. @kzantow does that work with you?
