### ISSUE TITLE
Support newer versions of 'rpm' that use Sqlite for the db instead of BerkeleyDB

### ISSUE THREAD

**Issue by zhill** [anchore/syft#469]
**What would you like to be added**:
Cataloger support for RPM dbs using sqllite instead of just berkelydb. This would enable support for recent Fedora releases among others.

**Why is this needed**:
To correctly create SBoMs from containers using newer versions (4.16+) of the rpm package.

**Additional context**:

This can be identified in the image by 'rpmdb.sqlite' file being present in /var/lib/rpm/ or /usr/sysimage/rpm/

**Comment by luhring** [comment]
Just a note: We're seeing this cause Syft not to show any RPM packages in `fedora:33` and later.

**Comment by sli720** [comment]
Any idea when this feature will be implemented?

**Comment by luhring** [comment]
@sli720 We don't have an expected date for this to land yet. We do accept PRs from the community, and we'd happily fields questions from anyone who wants to take a shot at this! 😃

**Comment by westonsteimel** [comment]
We are currently using a fork of https://github.com/knqyf263/go-rpmdb; however, upstream now supports these new formats.  I spoke some with @wagoodman regarding this and his idea was to work on getting our enhancements submitted upstream and then remove our fork

**Comment by tofay** [comment]
@westonsteimel I've created https://github.com/tofay/go-rpmdb/commits/upstream-plus-anchore-changes which adds the anchore customizations to the latest upstream commit and gets the tests passing. I've also verified that syft can use this to scan images with sqlite RPM dbs.

I've made two commits - one for the extra file information added in various PRs to the fork, and one for the change to make the epoch optional.
This should be a useful basis for anchore to submit the changes upstream? Note the commits didn't apply cleanly, so would need review/author fix-up as necessary.
Could syft also use that alongside upstreaming to resolve this issue? (perhaps by moving that branch into anchore/go-rpmdb)

**Comment by tofay** [comment]
Can I submit a PR to anchore/go-rpmdb and leave upstreaming to your team please? You can better speak to the changes and their use case in syft/grype.
I think that requires you creating a branch of anchore/rpm-db, matching the latest upstream, that I can push my changes to?

**Comment by knqyf263** [comment]
Hi, I'm a maintainer of `go-rpmdb`. I'm welcome any contribution😄

**Comment by tofay** [comment]
Anchore's changes to go-rpmdb have been upstreamed now, and I've raised https://github.com/anchore/syft/pull/1018 which removes the use of anchore's fork.
