### ISSUE TITLE
Syft tries to access the Internet

### ISSUE THREAD

**Issue by obfischer** [anchore/syft#480]
**What happened**: Docker image of syft tries to phone home and to download  something from https://toolbox-data.anchore.io/syft/releases/latest/VERSION

**What you expected to happen**: syft shouldn't download anything during runtime

**How to reproduce it (as minimally and precisely as possible)**: Run syft in an enterprise environment with high security requiremtns

**Anything else we need to know?**: I tried to evaluate today syft for an CI/CD setup in an international enterprise, but failed, as the nodes does not have access to the Internet

**Environment**:
- Output of `syft version`: n/a
- OS (e.g: `cat /etc/os-release` or similar): n/a

**Comment by kzantow** [comment]
Hi @obfischer -- this is Syft checking for new versions. It can be disabled via a [configuration file](https://github.com/anchore/syft#configuration) using the `check-for-app-update: false` option, or via an environment variable `SYFT_CHECK_FOR_APP_UPDATE=false`

**Comment by obfischer** [comment]
Setting the mentioned environment variable solved the problem.
