### ISSUE TITLE
Missing/incorrect SPDX fields: DocumentName, DocumentNamespace

### ISSUE THREAD

**Issue by kzantow** [anchore/syft#495]
**What happened**:
The SPDX spec [requires the DocumentName field](https://spdx.github.io/spdx-spec/document-creation-information/#64-document-name-field), which is not present.

Related: the namespace is the _same_ for all documents (e.g. `https://anchore.com/syft/image/`), which currently [goes against the spec indicating it should be uniquely identifiable](https://spdx.github.io/spdx-spec/document-creation-information/#65-spdx-document-namespace-field). Presumably the DocumentName would also be used as part of the DocumentNamespace.

NOTE: this is important in order to properly cross-reference SPDX files using the [relationship](https://spdx.github.io/spdx-spec/relationships-between-SPDX-elements/) field.

ALSO NOTE: this happens when using a _directory_ scan but this information is included if scanning a container image, however I do not believe the DocumentNamespace is correct, it does not have a UUID.

**What you expected to happen**:
A unique DocumentNamespace is generated and somehow a DocumentName is included or allowed to be specified from the command line.

**How to reproduce it (as minimally and precisely as possible)**:
`syft packages dir:. -o spdx`

**Anything else we need to know?**:
Pertinent directory scan output snippet:
```
SPDXVersion: SPDX-2.2
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentNamespace: https://anchore.com/syft/image/
LicenseListVersion: 3.14
Creator: Organization: Anchore, Inc
Creator: Tool: syft-0.21.0
Created: 2021-09-08T01:45:39Z

##### Package: chownr
...
```

Image scan output snippet:
```
SPDXVersion: SPDX-2.2
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: alpine:latest
DocumentNamespace: https://anchore.com/syft/image/alpine:latest
LicenseListVersion: 3.14
Creator: Organization: Anchore, Inc
Creator: Tool: syft-0.21.0
Created: 2021-09-08T16:40:41Z

##### Package: alpine-baselayout
...
```

**Environment**:
- Output of `syft version`: 0.21.0
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by spiffcs** [comment]
@kzantow regarding `DocumentName` see their specification examples [here](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXJSONExample-v2.2.spdx.json).

While the link you provided doesn't work anymore I think I understand the confusion. Here is an issue that references the [disparity](https://github.com/spdx/spdx-spec/issues/538). It looks like we're ok to not include this field until they get the field names a bit closer.

For `documentNamespace` you're correct. I'll add a PR that tacks a UUID to the end of the string.

**Comment by kzantow** [comment]
@spiffcs I think the `name` field in JSON is equivalent to the RDF `DocumentName` field: https://github.com/spdx/spdx-spec/blob/development/v2.2.2/schemas/spdx-schema.json#L106 and according to the RDF DocumentName is required. We could probably defer this until it becomes a problem or the spec issue is resolved. (The problem in the issue you linked to is discrepancy in the naming between `name` and `DocumentName` where many of the RDF `DocumentX` fields are `documentX` in JSON: https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXJSONExample-v2.2.spdx.json#L59)

**Comment by spiffcs** [comment]
Is there a case where `name` is not populated? Right now it takes the value of the image scanned.

There is an issue with our dir input. If I use the path `./` then `name: "./"`
```
{
 "SPDXID": "SPDXRef-DOCUMENT",
 "name": "anchore/syft:latest",
 "spdxVersion": "SPDX-2.2",
 "creationInfo": {
  "created": "2021-10-05T13:17:38.718246Z",
  "creators": [
   "Organization: Anchore, Inc",
   "Tool: syft-[not provided]"
  ],
  "licenseListVersion": "3.14"
 },
 "dataLicense": "CC0-1.0",
 "documentNamespace": "https://anchore.com/syft/image/68bdce12-02a7-45cf-aa18-43dac2ab8cfd",
 "packages": []
}
```
