### ISSUE TITLE
SPDX output is not consistently sorted

### ISSUE THREAD

**Issue by kzantow** [anchore/syft#497]
**What happened**:
`syft -o spdx ...` and `syft -o spdx-json ...` produce differently sorted output across different runs.

**What you expected to happen**:
The output is sorted consistently.

**How to reproduce it (as minimally and precisely as possible)**:
Run `syft -o spdx` multiple times and `diff` the results, these should not show lines that are in different order.

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: 0.21.0
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by spiffcs** [comment]
Just an update here - it's not the sorting that is the issue:

`diff -u /tmp/alpine.json:2 /tmp/alpine.json:latest` where both of those documents are the same run shows inconsistencies in CPE generation.

Specifically, sometimes a cpe will use `_` while in other runs it will use `_`.

After this is fixed I'll double check the sorting portion to be sure the output is consistently sorted, but the primary source of the `diff` pain comes from this weird flip of character between `-` and `_`

json-document
![Screen Shot 2021-09-30 at 11 47 39 AM](https://user-images.githubusercontent.com/32073428/135488884-ae64a338-ae99-4c39-bd66-24a245757f1c.png)

spdx
![Screen Shot 2021-09-30 at 11 36 24 AM](https://user-images.githubusercontent.com/32073428/135488914-41e9a4e8-5426-4d71-891f-8103dd492443.png)

**Comment by seabass-labrax** [comment]
This is great :grinning: Reproducible builds with Syft-generated SPDX documents coming soon, in CI pipelines near you!

**Comment by spiffcs** [comment]
Just adding a regression test in a separate PR to make sure we keep it that way!

**Comment by spiffcs** [comment]
Opening until we close the issue with the regression test.
