### ISSUE TITLE
Allow syft to populate distro data for all types

### ISSUE THREAD

**Issue by spiffcs** [anchore/syft#499]
**What would you like to be added**:
If syft does not find a known type within the `Type` enum for a supplied distobution, it should still populate the distro json with the information contained within the `os-release` so that the generated SBOMB has the most complete information.

**Why is this needed**:
Syft should not discriminate based on distro Type to generate the sbomb.

**Additional context**:
Related to issue #342

**Comment by luhring** [comment]
Closed by #496
