### ISSUE TITLE
Support 'ndb' rpm database format used in rpmdb 4.15+

### ISSUE THREAD

**Issue by zhill** [anchore/syft#504]
**What would you like to be added**:
Cataloger support for 'ndb' format

**Why is this needed**:
Inspect images with rpmdb version > 4.15 that use this by default (e.g. SUSE tumbleweed)

**Additional context**:

Identify this case by the files:
```
Index.db
Packages.db
```

found in: `/usr/lib/sysimage/rpm/` or `/var/lib/rpm/`

The format is defined in: https://github.com/rpm-software-management/rpm/tree/master/lib/backend/ndb

**Comment by JamieMagee** [comment]
It looks like this should now be possible? Support was added to `knqyf263/go-rpmdb`[^1] a few months ago. I know that anchore maintains a fork of `go-rpmdb`[^2], but it has diverged a bit, and has a lot of conflicts with upstream.

[^1]: https://github.com/knqyf263/go-rpmdb/commit/1369b2ee40b762e48586531810d5b2564e2c1063
[^2]: https://github.com/anchore/go-rpmdb

**Comment by tofay** [comment]
This will have the same resolution as https://github.com/anchore/syft/issues/469. Per https://github.com/anchore/syft/issues/469#issuecomment-1082736063 I've put the anchore customizations on top of the latest `knqyf263/go-rpmdb` at https://github.com/tofay/go-rpmdb/commits/upstream-plus-anchore-changes.
