### ISSUE TITLE
Support configurable scratch-directory other than /tmp

### ISSUE THREAD

**Issue by zhill** [anchore/syft#552]
**What would you like to be added**: Allow configuration to determine the path used for temporary data storage during unpacking and analysis. This is useful for very large image analysis where things like /tmp may be memfs or similar that are not good candidates for very large data volumes.

**Why is this needed**: Config value to define where the tool should write temporary data.

**Additional context**:

**Comment by luhring** [comment]
Closing this for now. We can re-open if we come across a need for more granular control of scratch disk space than can be accomplished with the builtin `TMPDIR` mechanism.
