### ISSUE TITLE
Promote cataloging task pattern

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#554]
Today the package command is a single task that is responsible for invoking all of the package catalogers and returning a presenter capable of encoding an SBOM in a particular format.

At the same time, the power-user command can enable and disable different catalogers and format the SBOM document more dynamically. Internally the power-user command is made of a set of tasks that is dynamic based on the configuration. Additionally, all tasks write to a single result document instance, encapsulating all possible things that can be cataloged. 

There are elements of the internal power-user command approach that would be ideal to promote forward as patterns we want to see on the package command ([or any command that will do cataloging in the future](https://github.com/anchore/syft/issues/516)).

Goals:
1. Have a singular analysis result document to encapsulate all things discovered. Possibly a new `sbom` package with a struct called `Document`. (tracked in https://github.com/anchore/syft/issues/555)
2. Move towards a task-based approach for separating work and attaching the result to the analysis document

These goals focus on how the work of cataloging is completed and persisting in a programmatic way that is useful to others.

**Comment by spiffcs** [comment]
Dependent on review of #606. When that is in then we can start building tasks around the package command that talk to this new document.

**Comment by spiffcs** [comment]
Grabbing this while waiting for review on our new media type.
