### ISSUE TITLE
Homebrew is showing warnings for syft installation

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#588]
**What happened**:
When running `brew upgrade <package>` the following warnings appeared:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the anchore/syft tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/anchore/homebrew-syft/syft.rb:9

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the anchore/grype tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/anchore/homebrew-grype/grype.rb:9
```

**What you expected to happen**:
There shouldn't be warnings for our homebrew formulas on any brew command.

**Comment by kkovaletp** [comment]
This issue was fixed some time ago, but returned back. Just letting you know...

**Comment by tightly-clutched** [comment]
This is still happening.

> % brew info syft
> Warning: Calling bottle :unneeded is deprecated! There is no replacement.
> Please report this issue to the anchore/syft tap (not Homebrew/brew or Homebrew/core):
>   /usr/local/Homebrew/Library/Taps/anchore/homebrew-syft/syft.rb:9
> 
> anchore/syft/syft: stable 0.33.0
> A tool that generates a Software Bill Of Materials (SBOM) from container images and filesystems
> https://github.com/anchore/syft
> /usr/local/Cellar/syft/0.33.0 (3 files, 21.1MB) *
>   Built from source on 2021-12-22 at 10:06:16
> From: https://github.com/anchore/homebrew-syft/blob/HEAD/syft.rb

**Comment by spiffcs** [comment]
This issue should now be fixed as we have moved to the latest upstream goreleaser. If found again or if we desync from the new brew release strategy comments can be made here and we will reopen the issue.
