### ISSUE TITLE
Add Pacman Analyzer

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#6]
Should:
- be able to parse a flatfile from `/var/lib/pacman/local` within the image scope
- populate results via the `CatalogWriter`
- implement the `Analyzers` interface (see the [design outline](https://github.com/anchore/project-toolbox/blob/master/alex/imgbom.md))

Test against:
- `archlinux:20191105` - `archlinux:20200505`

**Comment by Foxboron** [comment]
Fixed with https://github.com/anchore/syft/issues/241
