### ISSUE TITLE
Go.mod reports incorrect path

### ISSUE THREAD

**Issue by jeason81** [anchore/syft#601]
**What happened**:
When using Syft to analyze folders that ultimately contain one or more `go.mod` files in the directory structure, Syft reports the RealPath as simply `go.mod`. This causes confusion when trying to research findings as it is unknown which `go.mod` file the finding was discovered for.

**What you expected to happen**:
The expectation is that RealPath contains the full path to the `go.mod` file, for example `/User/blah/go/src/github.com/username/applicationname/go.mod`.

**How to reproduce it (as minimally and precisely as possible)**:
Scan any folders that has one or more `go.mod` files and save output to JSON. Additionally, confirmed by using the Syft library and parsing the data structure for `Package.Locations[].RealPath`.

**Anything else we need to know?**:
It appears that the `RealPath` is populated with `path` instead of `mod` on this line:
https://github.com/anchore/syft/blob/3286a4d4cc88e02e81db4f07d21a9fc6edac2a01/syft/pkg/cataloger/golang/parse_go_bin.go#L52
Changing this variable to `mod` appears would populate RealPath with the full location.

**Environment**:
- Output of `syft version`: 27.0
- OS (e.g: `cat /etc/os-release` or similar): Mac OS X Monterey. Additionally confirmed when executed within a running UBI8 container and analyzing a filesystem with `go.mod` files.

**Comment by luhring** [comment]
@wagoodman Do you think it makes sense to adjust the directory resolver to provide full paths to catalogers?

**Comment by spiffcs** [comment]
@jeason81 we followed up on this issue recently and ran a test on syft itself.

I copied the `go.mod` file and placed it under `test/go.mod` the resulting SBOM had some duplicate packages where one would have the `RealPath` sourced from `go.mod` while the other would be sourced from `test/go.mod`.

If this is still incorrect and you would like other behavior let me know and I can reopen this issue.
