### ISSUE TITLE
Syft indexing should ignore non-regular files

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#615]
_(I'm extracting this from a conversation from https://anchorecommunity.slack.com/archives/C019BUXV7R6/p1635509628025900?thread_ts=1635430847.021800&cid=C019BUXV7R6)_

Syft is hanging when attempting to index paths that are non-regular files (such as FIFO):
```
  File: '/run/dmeventd-client'
  Size: 0         	Blocks: 0          IO Block: 4096   fifo
Device: 14h/20d	Inode: 12419       Links: 1
Access: (0600/prw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-04-06 08:33:27.368000000 +0000
Modify: 2021-04-06 08:33:27.368000000 +0000
Change: 2021-04-06 08:33:27.368000000 +0000
 Birth: -
```

Indexing should skip theses files instead of hard coding ignore paths such as `/run` since these can occur anywhere in the filesystem.

**Comment by spiffcs** [comment]
@debuglevel thanks for the additional feedback.

We have another PR about to land surrounding this issue:
https://github.com/anchore/syft/pull/667

Linking the closed issue with the PR so we can make sure we have coverage for `/run/initctl`

A new version of syft will be released to address these hangs.

**Comment by debuglevel** [comment]
Thanks a lot! (Awesome tool by the way. I could not thank enough to have something like this tool during log4shell.)
