### ISSUE TITLE
Go module with AllLayers only giving RealPath information

### ISSUE THREAD

**Issue by jwstric2** [anchore/syft#619]
**What happened**:

Missing layer awareness for go-modules

**What you expected to happen**:

Expected layer information added when AllLayers is given for go modules

**How to reproduce it (as minimally and precisely as possible)**:

```
git clone https://github.com/olliefr/docker-gs-ping
docker build -t docker-gs-ping .
syft docker-gs-ping -o json -s AllLayers > output_alllayers_golang.json

Look in the output for github.com/dgrijalva/jwt-go, the location is File only.
```
[output_0.25.0_alllayers_golang.zip](https://github.com/anchore/syft/files/7487935/output_0.25.0_alllayers_golang.zip)

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: 

Started in syft 0.25; using latest version

```
$ /tmp/syft-0.29/syft version
Application:   syft
Version:       0.29.0
BuildDate:     2021-10-31T15:22:19Z
GitCommit:     a2882ee810edcbf4db3230e982c316b261eb17cd
GitTreeState:  clean
Platform:      linux/amd64
GoVersion:     go1.16.9
Compiler:      gc
```

- OS (e.g: `cat /etc/os-release` or similar):

```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

**Comment by spiffcs** [comment]
Hey @jwstric2. Here is the output I was able to reproduce:
```
  {
   "id": "18d0f5ea-d02f-44ba-9554-c4f94b27845a",
   "name": "github.com/dgrijalva/jwt-go",
   "version": "v3.2.0+incompatible",
   "type": "go-module",
   "foundBy": "",
   "locations": [
    {
     "path": "/docker-gs-ping"
    }
   ],
   "licenses": [],
   "language": "go",
   "cpes": [
    "cpe:2.3:a:dgrijalva:jwt-go:v3.2.0+incompatible:*:*:*:*:*:*:*",
    "cpe:2.3:a:dgrijalva:jwt_go:v3.2.0+incompatible:*:*:*:*:*:*:*"
   ],
   "purl": "pkg:golang/github.com/dgrijalva/jwt-go@v3.2.0+incompatible",
   "metadataType": "GolangBinMetadata",
   "metadata": {
    "GoCompiledVersion": "go1.16.10",
    "H1Digest": "h1:7qlOGliEKZXTDg6OTjfoBKDXWrumCAMpl/TFQ4/5kLM="
   }
```

Specifically, are you expecting a `LayerID` to accompany the path?

In this screenshot inspecting my local image `/docker-gs-ping` is located at layer Id `6545a175154bf81fbf192ca1e21df00af86915b7c9a326a6f6dd35184459aebe`

Is this the value you expect as a sibling to the Path information?

![Screen Shot 2021-11-05 at 2 10 10 PM](https://user-images.githubusercontent.com/32073428/140558455-3911d700-6dc1-4d84-91d6-80c82271820e.png)

**Comment by jwstric2** [comment]
@spiffcs Yes, I was expecting LayerId to be part of the output.  I was fixing to look through the code base in a bit; attempting to familiarize myself with the structure before further debugging.  I was pondering it perhaps it was intentionally designed to give only a real path location?

**Comment by jwstric2** [comment]
Looks like location is using RealPath only:  https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/golang/parse_go_bin.go#L50

**Comment by jwstric2** [comment]
so just to follow-up on this, is there a reason some catalogers may/may not be passed image / layer information.  I'd have to spend more than my 15 minutes looking through the code to really get into the depths of the architecture.

**Comment by spiffcs** [comment]
I don't think so, but let me sync with @wagoodman and we can get a plan going forward for some consistency. Just for some clarifying information, the callers for the file you linked can be found here:

https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/golang/bin_cataloger.go

The main struct `Cataloger` has the method `Catalog` and `Name` - It fulfills the interface located below.
https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/cataloger.go

`layerID` Comes from the struct `Location` which can be found here:
https://github.com/anchore/syft/blob/2f99a35f51dde8c84443ce038b71a748439cf83b/syft/source/location.go

I'll check the list of locations [here](https://github.com/anchore/syft/blob/bb0f35bac4e2e610e61be55b27b3810099794479/syft/pkg/cataloger/golang/bin_cataloger.go#L40-L58) and see if `FilesByMIMEType` return a populated `layerID` then it would just be a matter of adding it into the struct construction for the pkg.

**Comment by wagoodman** [comment]
Indeed the layer information should have been there (as it is with all existing catalogers) --this was an oversight when adding in fetching files by MIMETypes. Thanks for digging @spiffcs !

**Comment by jwstric2** [comment]
@wagoodman and @spiffcs thank you for looking at this.
