### ISSUE TITLE
Switch to latest released version of CycloneDX format

### ISSUE THREAD

**Issue by kkovaletp** [anchore/syft#629]
**What would you like to be added**: it would be great if Syft uses latest released version of CycloneDX XML format for SBOM generation, utilizing new improvements, introduced there.

**Why is this needed**: New versions of CycloneDX XML provide some new enhancements and improvements and it is always good to utilize them and use, providing those benefits to end users

**Additional context**:

As of this ticket creation, CycloneDX XML format version 1.3 is available for a while, however Syft is still generates SBOM XML in 1.2 version

**Comment by robdimsdale** [comment]
The [README](https://github.com/anchore/syft#output-formats) states that the supported version of CycloneDX is 1.3 - and this is consistent with our observations of consuming `syft` as a library where see:

```
...
"bomFormat": "CycloneDX",
"specVersion": "1.3",
...
```

Therefore, can we mark this issue as resolved?

**Comment by hectorj2f** [comment]
Yes, it looks like it could get closed in my opinion. cc @luhring

**Comment by spiffcs** [comment]
Closed - README was bumped with correct links to latest specification

**Comment by kkovaletp** [comment]
Hi Rob,

 

Sure, I think, this issue is fixed some time ago.

 

Best regards

Konstantin

 

From: Rob Dimsdale-Zucker ***@***.***>
Reply-To: anchore/syft ***@***.***>
Date: Tuesday, 14 December 2021, 19:41
To: anchore/syft ***@***.***>
Cc: Konstantine Koval ***@***.***>, Author ***@***.***>
Subject: Re: [anchore/syft] Switch to latest released version of CycloneDX format (Issue #629)

 

The README states that the supported version of CycloneDX is 1.3 - and this is consistent with our observations of consuming syft as a library where see:
...
"bomFormat": "CycloneDX",
"specVersion": "1.3",
...
Therefore, can we mark this issue as resolved?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
