### ISSUE TITLE
Add an output type for CycloneDX JSON format

### ISSUE THREAD

**Issue by dmikusa-pivotal** [anchore/syft#631]
**What would you like to be added**:

Presently you can `syft packages -o cyclonedx dir:.` and you'll get a CycloneDX report in XML. There are tools to convert it to JSON, but it's an extra step.

It would be helpful there was a `cyclonedx-json` (or something like that) output format that would directly output CycloneDX JSON.

**Why is this needed**:

It would make using `syft` more convenient for use cases that require CycloneDX JSON output. No additional tools or libraries would be required to convert from XML to JSON.

**Additional context**:

The [Buildpacks specification](https://github.com/buildpacks/rfcs/blob/main/text/0095-sbom.md) has been standardized around using JSON output. Many of the buildpacks we are developing are generating SBoMs using `syft`, which leaves us needing to convert from CycloneDX XML to JSON. Having an option for direct output would make our integrations easier.

Thanks!

**Comment by sophiewigmore** [comment]
I am also interested in this request!
