### ISSUE TITLE
Go Library Support

### ISSUE THREAD

**Issue by sophiewigmore** [anchore/syft#646]
**What happened**:

Hi! 👋  I am leveraging the Syft Go library in my project to generate SBOMs. I'm wondering if there are any support expectations from maintainers around the library? Can I expect that this API will be around a while for use?
It appears that the CLI tool is well documented, but the library is not (that I could find). Is this for a reason? I'm worried that if I use the library, it might not be fully supported in the future. I'm essentially looking to see if the library is intended for use, and that it will be continued to be supported. 

**What you expected to happen**:
I would have expected more documentation and/or examples of the Go Library in action.

~~**How to reproduce it (as minimally and precisely as possible)**:~~

**Anything else we need to know?**:
As a user, I would be happy to contribute some kind of documentation for the library, if the plan is to keep it around and make it more useable.

**Comment by wagoodman** [comment]
@sophiewigmore there are some thoughts on the next evolution of the API tracked in a previously opened issue: https://github.com/anchore/syft/issues/558 . Feel free to take a look -- feedback is more than welcome!
