### ISSUE TITLE
Syft verbose log version

### ISSUE THREAD

**Issue by jonasagx** [anchore/syft#664]
**What would you like to be added**:
Verbose logs expose Syft's version

**Why is this needed**:
Whenever a problem happens it is important to have context to reproduce it and knowing the running version is the first step. CI platforms require extra steps to reproduce fails, and environments can change between executions. A log line with version makes it clear

**Additional context**:

**Comment by wagoodman** [comment]
Yeah, I'm surprised we don't have this. A couple of notes/opinions:
- Add the simple version status as an `info` log line
- Add more detailed version info as `debug` log line
- Make certain we log when there is an update available (we are already doing that check based on app config behavior)

We should get this into grype and grype-db-builder too 👍
