### ISSUE TITLE
Syft hangs when encounting symlink (in /run/udev/) to a character device (in /dev/)

### ISSUE THREAD

**Issue by cameronkerrnz** [anchore/syft#665]
**What happened**:

Given a desire to scan a host
When it reaches a symlink that point to a character special device that would block on read
It hangs

**What you expected to happen**:

Given a desire to scan a host
When it reaches a symlink that point to a character special device (OR a socket) [that could block on read]
It should skip it as unreadable and continue to completion.

**How to reproduce it (as minimally and precisely as possible)**:

On a machine with a sound driver (I couldn't think of other characters that would be likely to block on read for a CI/CD environment).

```
syft packages dir:/run/
```

Hangs when Indexing file:/run/udev/static_node-tags/uaccess/snd\x2fseq

/run/udev/static_node-tags/uaccess/snd\x2fseq is a symlink to /dev/snd/seq, which is a character device

strace shows syft doing the following

![image](https://user-images.githubusercontent.com/938702/145707085-ec05d8f0-2767-46b9-8fd7-d5d25977102d.png)

It would appear that syft is correctly detecting the symlink, but then not doing the check (that it would normally do if I run syft against file:/dev/snd/seq) in detecting it as  character special device.

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: Version 0.32.0

Downloaded today from GitHub release using install.sh script from this repository.

![image](https://user-images.githubusercontent.com/938702/145707186-6ffe9473-b36b-410a-9a2e-0c5b87ee3086.png)

- OS (e.g: `cat /etc/os-release` or similar):

Red Hat Enterprise Linux release 8.4 (Ootpa)   --- running as a graphical workstation with sound capability.

**Comment by cameronkerrnz** [comment]
There seems that the only path filtering function installed is isUnixSystemRuntimePath

https://github.com/anchore/syft/blob/21d1738b273f85d93e0957d72181ba73e3f8f939/syft/source/directory_resolver.go#L61-L63

There should be another filter that returns false for character-special, socket, fifo.

... and probably block specials too.

... autofs mount-points?

**Comment by jonasagx** [comment]
Thank you for describing this bug, all the details were helpful (I should use strace more often). I was able to reproduce the indexing of `/dev/snd/seq`, although not the hanging (maybe I need something playing?) but that is minor: Syft shouldn't index symLink if they resolve to a non-regular target.

To list the indexed files, which will then be scanned later, simply add `-vv` for verbose logs. 
```sh
jonas@zoo:/run/udev/static_node-tags/uaccess$ syft packages dir:. -vv
[0000] DEBUG no new syft update available
[0000]  INFO indexing filesystem path="."
[0000]  INFO indexing filesystem path="/dev/snd/seq"
[0000]  INFO indexing filesystem path="/dev/snd/timer"
```

We have checks for files that are not regular, as socket, fifo, etc. However the check is not smart enough for symLinks:

https://github.com/anchore/syft/blob/21d1738b273f85d93e0957d72181ba73e3f8f939/syft/source/directory_resolver.go#L163
https://github.com/anchore/syft/blob/21d1738b273f85d93e0957d72181ba73e3f8f939/syft/source/directory_resolver.go#L169-L184

It should validate a symLink as well as its target. It's a simple change, I can work on it soon, or if you would like feel free to submit a pull request and I will review it.

**Comment by cameronkerrnz** [comment]
I should add that in my case this was running in a VirtualBox VM, and I'm not entirely sure if sound was working; at least I don't normally have anything playing on it.

I'm kinda busy with log4j stuff at the moment.... otherwise I would consider trying to patch it.

**Comment by luhring** [comment]
( Related / duplicate of #615 )
