### ISSUE TITLE
An option to limit to a single filesystem (like -xdev)

### ISSUE THREAD

**Issue by richlv** [anchore/syft#674]
**What would you like to be added**:
An option to limit to a single filesystem would be great. To borrow from find's manpage:

    -xdev  Don't descend directories on other filesystems.

**Why is this needed**:
Scanning a directory like / ends up in /proc/, /dev/ and other places.
Sometimes that leads to a hang, like in #665.

**Comment by spiffcs** [comment]
Nice! Thanks for the request @richlv. 

We're actively working on a fix so we don't hit these paths and hang as reported. We'll also see if we can add specific options for inclusion vs exclusion in the future.

See https://github.com/anchore/syft/pull/667 for PR progress on the hang fixes.

**Comment by stefan123t** [comment]
+1 for an `-x<exclude_path>` option.
I have Syft running through my /home/.ecryptfs/ folder which will do no harm, but does not yield any tangible results either.
`syft packages dir:/ --scope all-layers -o table | grep log4j`

**Comment by richlv** [comment]
One filesystem option and excludes are a bit different features - should they be split out as different feature requests?

**Comment by richlv** [comment]
Thank you, `--exclude` looks great.
To clarify, this issue is not about excluding a filesystem, but about limiting to the filesystem, on which the scanning start point is - pretty much the same as for `find`.

While `--exclude` could be used for this by explicitly listing all other filesystems below the starting point, that's not flexible (depends on the target system) and less convenient.

**Comment by ajvpot** [comment]
I opened a draft pull request in #816 that implements something similar to this.

**Comment by spiffcs** [comment]
Hey everyone! With https://github.com/anchore/syft/pull/667 merged and the base ability to ignore proc/dev as well as the configuration options here https://github.com/anchore/syft/issues/221 for specific files we're going to consider this issue closed for now. If anyone has other ideas or features tag me and I can look at the PR or reopen this issue. Thanks!

**Comment by richlv** [comment]
Hi, still very much interested in this feature - should I create a new issue?
