### ISSUE TITLE
Misleading error message when oci-archive scheme used on non-OCI archives

### ISSUE THREAD

**Issue by wurstbrot** [anchore/syft#701]
**What happened**:
I get "no such file or directory" for an existing oci:archive

**What you expected to happen**:
The oci archive is picked.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ ls -la image.tar 
-rw-r--r-- 1 docker docker 1400545280 Dec 17 12:30 /tmp/test/image.tar
$ docker run -v $(pwd):/x anchore/syft packages oci-archive:/x/image.tar
1 error occurred:
	* failed to determine image source: could not fetch image '/x/image.tar': unable to open OCI tarball: open oci-archive:/x/image.tar: no such file or directory
```
Same with local installation and absolute or relative paths.

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
0.33.0

- OS (e.g: `cat /etc/os-release` or similar):
Linux, Docker

**Comment by luhring** [comment]
Yikes! I can reproduce this on my machine. I'll start looking at this. 👀 

Thanks for reporting this, @wurstbrot!

**Comment by luhring** [comment]
Actually, I was wrong! I'm **not** able to reproduce this for an _OCI archive_. But I am able to reproduce it for other `.tar` representations of images (i.e. not OCI archives).

I think, at minimum, there's a misleading error message being displayed here.

@wurstbrot Would you mind running `tar -tf /tmp/test/image.tar` and sharing the output here?

**Comment by wurstbrot** [comment]
@luhring thank you, looks like I am doing it wrong.

```
tpagel@wurstbrot-desktop:/tmp$ cd /tmp/
tpagel@wurstbrot-desktop:/tmp$  mkdir image-target
mkdir: cannot create directory ‘image-target’: File exists
tpagel@wurstbrot-desktop:/tmp$ image_copy_dir=image-target
tpagel@wurstbrot-desktop:/tmp$ IMAGE_BY_HASH=quay.io/sdase/cluster-image-scanner-scan-distroless:2
tpagel@wurstbrot-desktop:/tmp$ skopeo copy "docker://${IMAGE_BY_HASH}" "dir:${image_copy_dir}/"
Getting image source signatures
Copying blob c154b1288f5a done  
Copying blob c840b57f2fa1 done  
Copying config 764d6c14e7 done  
Writing manifest to image destination
Storing signatures
tpagel@wurstbrot-desktop:/tmp$ tar -cf ./oci-image.tar ${image_copy_dir}/*
tpagel@wurstbrot-desktop:/tmp$  docker run -v $(pwd):/x anchore/syft packages oci-archive:/x/oci-image.tar
1 error occurred:
	* failed to determine image source: could not fetch image '/x/oci-image.tar': unable to open OCI tarball: open oci-archive:/x/oci-image.tar: no such file or directory


tpagel@wurstbrot-desktop:/tmp$ tar -tf oci-image.tar 
image-target/764d6c14e753efc5cfbb8329ee9e2444cabafe9553bf642fa3cec011e0297551
image-target/c154b1288f5adcb7fd585988cbf7849ed063e379e58b0720a7c6982d644a1962
image-target/c840b57f2fa1d081b9b3697cea0f45e4984f354a8b0bc9dff66a037a058748bb
image-target/manifest.json
image-target/version
```
From what I understood from [the OCI image spec](https://github.com/opencontainers/image-spec/blob/main/spec.md) this is not an OCI archive. So I think it is my fault and I recommend:
- to differentiate in the error between the given file is there and the specification/structure is not matched
- an update of the documentation how to create an oci tar file with skopeo

**Comment by luhring** [comment]
Thanks for confirming! I'll get a PR opened for handling the error better.
