### ISSUE TITLE
Syft can generate invalid CPEs for debs and rpms with epochs

### ISSUE THREAD

**Issue by samj1912** [anchore/syft#712]
**What happened**:

Currently debs and rpms may have a `:` in their version to indicate epochs. Syft currently passes these directly to the CPE generator, generating CPEs with an extra colon which violate the CPE spec

**What you expected to happen**:

Syft should generate valid CPEs

**How to reproduce it (as minimally and precisely as possible)**:
Eg -

```
$ syft centos:7 -o json | grep cpe | grep vim-minimal
 ✔ Loaded image
 ✔ Parsed image
 ✔ Cataloged packages      [159 packages]
    "cpe:2.3:a:vim-minimal:vim-minimal:2:7.4.629-7.el7:*:*:*:*:*:*:*",
    "cpe:2.3:a:vim-minimal:vim_minimal:2:7.4.629-7.el7:*:*:*:*:*:*:*",
    "cpe:2.3:a:vim_minimal:vim-minimal:2:7.4.629-7.el7:*:*:*:*:*:*:*",
    "cpe:2.3:a:centos:vim-minimal:2:7.4.629-7.el7:*:*:*:*:*:*:*",
    "cpe:2.3:a:vim:vim-minimal:2:7.4.629-7.el7:*:*:*:*:*:*:*",

```

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
```
syft version
Application:   syft
Version:       0.33.0
BuildDate:     2021-12-16T14:16:33Z
GitCommit:     a27907659d6c43f5bef2f76a9e381f2bf697a64f
GitTreeState:  clean
Platform:      darwin/amd64
GoVersion:     go1.16.12
Compiler:      gc
```
- OS (e.g: `cat /etc/os-release` or similar): macOS

**Comment by kzantow** [comment]
FWIW, I think these characters should be percent-encoded based on section **6.1.2.1.2** in the CPE 2.3 spec: https://nvlpubs.nist.gov/nistpubs/Legacy/IR/nistir7695.pdf

**Comment by samj1912** [comment]
Looking at the cpe db - https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&orderBy=CPEURI&keyword=cpe%3A2.3%3A*%3A*%3Atar%3A1*%3A*%3A*%3A*%3A*%3A*%3A*%3A*&status=FINAL%2CDEPRECATED&startIndex=0

I think it might make sense to remove the epoch entirely and use the original version here.

**Comment by samj1912** [comment]
Looks like apart from epoch - there are also other characters in the version that cause syft to create an invalid cpe - will look further as to how to solve it.

**Comment by samj1912** [comment]
And... it's not just versions - looks like we can generate invalid CPEs when the name contains characters like `+` for eg libstdc++6

**Comment by wagoodman** [comment]
Just to link this: this is heavily related to #426
