### ISSUE TITLE
Support more java artifact extensions

### ISSUE THREAD

**Issue by westonsteimel** [anchore/syft#728]
**What would you like to be added**:

See the twitter thread at https://twitter.com/pyotam2/status/1475840905659695113 for some more scenarios we may want to consider for the java ecosystem.  In particular, it seems it would be quite simple to add support for `.par` as it is just adding another glob pattern at https://github.com/anchore/syft/blob/7168dc74730564d8ccdd9c51d07592d5e1729f4b/syft/pkg/cataloger/java/archive_parser.go#L19f

Note: the table has a mistake as noted in https://twitter.com/pyotam2/status/1476890400950468633, so grype does detect several more scenarios than currently shown.

**Why is this needed**:

Better support for various java artifacts

**Comment by westonsteimel** [comment]
I have also been looking through some of the the other tools which are specifically created for log4j, and I saw that [jfrog/log4j-tools](https://github.com/jfrog/log4j-tools) also supports .sar from https://github.com/jfrog/log4j-tools/commit/e88c8a6bb3545f02063f2f36df1837156c28d070

**Comment by westonsteimel** [comment]
I have no idea how common these formats are, but if it's as easy as just adding the glob pattern then does it make sense?  Anyways, I have a PR open for adding support for `.par` if it makes sense.

**Comment by spiffcs** [comment]
Thanks for the PR @westonsteimel! Let me spin up a test image and give it a run.

**Comment by westonsteimel** [comment]
Also, info about .sar is here: https://docs.oracle.com/cd/E19355-01/820-3007/ggnjx/index.html.  It looks like SIP aps can be packaged as either .war or .sar, so should we also add that since we already have .war?

**Comment by wagoodman** [comment]
>  It looks like SIP apps can be packaged as either .war or .sar, so should we also add that since we already have .war?

Makes sense to me!
