### ISSUE TITLE
Missing checksums for other than Linux in 0.35.0 release

### ISSUE THREAD

**Issue by marcinbojko** [anchore/syft#739]
**What happened**:
Missing checksums for windows in 0.35.0 release
```
091d89fff91eac8c6437b291b6a35dde692231ba92c8b44a47f648113d3aec38  syft_0.35.0_linux_amd64.rpm
583433c8d31ae8b78b033f2907686ca3c67b9c2e8687fe2401e17a1b28d6bea6  syft_0.35.0_linux_arm64.deb
5912abf7a5b8bfa30f1bd00ec4f8715734adbab10f413c7bbef9b1cea47e55d0  syft_0.35.0_linux_arm64.tar.gz
5eddcf20dc3d19dd2a23ec5fd1c29dd74a9589dd3a799708a881b9cd6205fccc  syft_0.35.0_linux_amd64.tar.gz
9b921e8de17d1413c508ae8cead80c11e892af19bb3c430c1024e9da6b5bbc06  syft_0.35.0_linux_amd64.deb
f14d16df7554c97199450ec7c0f49313a6932551065619afd1c6d1c67f34abab  syft_0.35.0_linux_arm64.rpm  
```

**What you expected to happen**:
```
052915bde04071ec5e60ad20181ff74f9c72d474a857164560a3c7b40dd4a832  syft_0.34.0_darwin_amd64.zip
0efee88a90e46f86be62f45cdeb416d2e0734dcfebc6f4fec6b41bcbbd2645fa  syft_0.34.0_linux_amd64.tar.gz
12466317791a760038484e6e8ae5789672b00a5b9960e32ee30cf214ca05310b  syft_0.34.0_linux_amd64.rpm
7f38731850caea76fab26809743ab18ddcdc23d2e88c4448bcbfb4f90bbebc43  syft_0.34.0_linux_arm64.deb
84dd287cebba6c0278a883dbb233c0ae38b0c9c1d272e01a4c7046bba46a9c07  syft_0.34.0_darwin_arm64.zip
8eb6ef0305f371b7567b709947944ea5eeb5f342bcf40723f43f861661a18c51  syft_0.34.0_linux_arm64.rpm
d733efcef8bc0316478b80fe97a01216f5be4a2c4fa749dc78a2510783f5bbd2  syft_0.34.0_linux_amd64.deb
fc8e2cee22cc82a69a1919fa0b559f750fa7fca44bc8b576709bc5f2bcab481c  syft_0.34.0_linux_arm64.tar.gz
ffbaffa938dbb8c3510c59ae0b96bda2d5f90c4ad7af9077d6480fac1ac6efaa  syft_0.34.0_windows_amd64.zip 
```

**How to reproduce it (as minimally and precisely as possible)**:
```
cat syft_0.35.0_cheksums.txt 
```
**Anything else we need to know?**:
Nope
**Environment**:
- Output of `syft version`:
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by spiffcs** [comment]
Thanks @marcinbojko! I'll check the go-releaser config and see where we went wrong here. Just added windows builds recently so really appreciate the issue report!

**Comment by marcinbojko** [comment]
Thanks @spiffcs, I've created syft chocolatey package, and before I'll upgrade it to use AU I wanted to play with the manual approach first.
Thanks for the excellent software

**Comment by spiffcs** [comment]
#740 should round this out and fix it for future releases. Thanks for the quick heads up!

**Comment by spiffcs** [comment]
These will be included in either the v0.35.2 release or the v0.36.0 release. We release fairly often so expect it to show up soon. Apologies for cutting v0.35.1 which had vulnerability remediation without this PR being merged.

**Comment by marcinbojko** [comment]
Unfortunately, release 0.36.0 is also missing checksums

**Comment by spiffcs** [comment]
Apologies @marcinbojko:

It looks like the release was cut before https://github.com/anchore/syft/commit/c350bd55f61d64786f05463f952be55c512c553c was merged. We had tested our changes locally and found the checksums to be generating, but this part was not caught before we approved the release. I'll follow up again on the our next release to be sure this change is effective for our new process.
