### ISSUE TITLE
Disable check for update at runtime with env var or at build time via ldflags

### ISSUE THREAD

**Issue by 06kellyjac** [anchore/syft#747]
**What would you like to be added**:

I'd like to be able to disable check for update with an env var or maybe turn it off by default via ldflags.
I could understand you preferring people get notice for updates when using the program so I'd go with the env var option

**Why is this needed**:

When building syft in a nix sandbox there is no networking access.
You have to run `syft completion X` to generate completions.
You get error logs that it can't connect to the servers, which thankfully don't crash the program so it's just visual noise.

I currently write a temp config file with `check-for-app-update: false` just for during the build but it's not great

**Additional context**:

![image](https://user-images.githubusercontent.com/9866621/149536057-50dfbafd-d1ca-4e0c-a241-a58e4b18af65.png)

**Comment by luhring** [comment]
Most of Syft's config can also be set via env vars, actually — and that includes this setting.

If you prefix your Syft command with:

```
SYFT_CHECK_FOR_APP_UPDATE=false ...
```

Syft won't check for an update. Can you try that and let us know if that solves your issue?

**Comment by 06kellyjac** [comment]
Yeah `export SYFT_CHECK_FOR_APP_UPDATE=false` covered it. Thanks
