### ISSUE TITLE
Cyclonedx export with CPE

### ISSUE THREAD

**Issue by wurstbrot** [anchore/syft#749]
**What would you like to be added**:
Cyclonedx report  with CPE
**Why is this needed**:
The cyclone schema supports CPE and it will give a more precise output.
Some tools rely on CPE and do not consider pURL.

**Additional context**:
While SPDX export includes CPE, it is not included in the cycledx export.

Proof:
```
$ docker run anchore/syft centos:8 --output spdx-json | grep cpe | wc -l
1904
$ docker run anchore/syft centos:8 --output cyclonedx-json | grep cpe | wc -l
0
```
An issue might be that there are multiple CPEs for one component:
```
PackageName: python3-dnf
SPDXID: SPDXRef-Package-rpm-python3-dnf
PackageVersion: 4.4.2-11.el8
PackageDownloadLocation: NOASSERTION
FilesAnalyzed: false
PackageLicenseConcluded: NONE
PackageLicenseDeclared: NONE
PackageCopyrightText: NOASSERTION
ExternalRef: SECURITY cpe23Type cpe:2.3:a:python3-dnf:python3-dnf:4.4.2-11.el8:*:*:*:*:*:*:*
ExternalRef: SECURITY cpe23Type cpe:2.3:a:python3-dnf:python3_dnf:4.4.2-11.el8:*:*:*:*:*:*:*
ExternalRef: SECURITY cpe23Type cpe:2.3:a:python3_dnf:python3-dnf:4.4.2-11.el8:*:*:*:*:*:*:*
ExternalRef: SECURITY cpe23Type cpe:2.3:a:python3_dnf:python3_dnf:4.4.2-11.el8:*:*:*:*:*:*:*
ExternalRef: SECURITY cpe23Type cpe:2.3:a:python3:python3-dnf:4.4.2-11.el8:*:*:*:*:*:*:*
ExternalRef: SECURITY cpe23Type cpe:2.3:a:python3:python3_dnf:4.4.2-11.el8:*:*:*:*:*:*:*
ExternalRef: SECURITY cpe23Type cpe:2.3:a:centos:python3-dnf:4.4.2-11.el8:*:*:*:*:*:*:*
ExternalRef: SECURITY cpe23Type cpe:2.3:a:centos:python3_dnf:4.4.2-11.el8:*:*:*:*:*:*:*
ExternalRef: PACKAGE_MANAGER purl pkg:rpm/centos/python3-dnf@4.4.2-11.el8?arch=noarch
```

**Comment by wagoodman** [comment]
I heavy agree with your suggestion of allowing for multiple CPEs, however, the cyclonedx spec [does not allow for multiple CPEs]( https://github.com/anchore/syft/blob/main/schema/cyclonedx/cyclonedx.xsd#L297-L304):
```
            <xs:element name="cpe" type="bom:cpe" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        DEPRECATED - DO NOT USE. This will be removed in a future version.
                        Specifies a well-formed CPE name. See https://nvd.nist.gov/products/cpe
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
```
_(from the cyclonedx XML schema... though in some good news is that the CPE deprecation has recently been removed from the cyclone dx spec: https://github.com/CycloneDX/specification/issues/105 )_

With regard to including CPEs in cyclonedx-json (and cyclonedx-xml) --we definitely should! The fact that we don't is for certain an oversight, thanks for reporting 👍

**Comment by samj1912** [comment]
Fixed in #710 according to https://github.com/anchore/syft/issues/268#issuecomment-897816180

**Comment by luhring** [comment]
Is it okay to close this now?

**Comment by samj1912** [comment]
We do populate all the cpe information in CycloneDX as best as we can with what the spec allows.
