### ISSUE TITLE
Python package Name and pURL have errors in CycloneDX output

### ISSUE THREAD

**Issue by 37b** [anchore/syft#780]
When generating a bom.xml in CycloneDX format the following entries were created

 ``` <components>
    <component type="library">
      <name></name>
      <version></version>
      <cpe>cpe:2.3:a:python-:python-:*:*:*:*:*:*:*:*</cpe>
      <purl>pkg:pypi/</purl>
      <properties>
        <property name="foundBy">python-package-cataloger</property>
        <property name="language">python</property>
        <property name="type">python</property>
        <property name="metadataType">PythonPackageMetadata</property>
        <property name="path">/usr/lib/python3/dist-packages/.wh.setuptools-52.0.0.egg-info</property>
        <property name="layerID">sha256:501fee28c6e4a55d3b43d4194b23128b14dee7b16025e629f601ff562ee98c18</property>
      </properties>
    </component>
    <component type="library">
      <name></name>
      <version></version>
      <cpe>cpe:2.3:a:python-:python-:*:*:*:*:*:*:*:*</cpe>
      <purl>pkg:pypi/</purl>
      <properties>
        <property name="foundBy">python-package-cataloger</property>
        <property name="language">python</property>
        <property name="type">python</property>
        <property name="metadataType">PythonPackageMetadata</property>
        <property name="path">/usr/lib/python3/dist-packages/.wh.wheel-0.34.2.egg-info</property>
        <property name="layerID">sha256:501fee28c6e4a55d3b43d4194b23128b14dee7b16025e629f601ff562ee98c18</property>
      </properties>
    </component>
```

Here it is in JSON

```
   {
      "type": "library",
      "name": "",
      "version": "",
      "cpe": "cpe:2.3:a:python-:python-:*:*:*:*:*:*:*:*",
      "purl": "pkg:pypi/",
      "properties": [
        {
          "name": "foundBy",
          "value": "python-package-cataloger"
        },
        {
          "name": "language",
          "value": "python"
        },
        {
          "name": "type",
          "value": "python"
        },
        {
          "name": "metadataType",
          "value": "PythonPackageMetadata"
        },
        {
          "name": "path",
          "value": "/usr/lib/python3/dist-packages/.wh.setuptools-52.0.0.egg-info"
        },
        {
          "name": "layerID",
          "value": "sha256:501fee28c6e4a55d3b43d4194b23128b14dee7b16025e629f601ff562ee98c18"
        }
      ]
    },
    {
      "type": "library",
      "name": "",
      "version": "",
      "cpe": "cpe:2.3:a:python-:python-:*:*:*:*:*:*:*:*",
      "purl": "pkg:pypi/",
      "properties": [
        {
          "name": "foundBy",
          "value": "python-package-cataloger"
        },
        {
          "name": "language",
          "value": "python"
        },
        {
          "name": "type",
          "value": "python"
        },
        {
          "name": "metadataType",
          "value": "PythonPackageMetadata"
        },
        {
          "name": "path",
          "value": "/usr/lib/python3/dist-packages/.wh.wheel-0.34.2.egg-info"
        },
        {
          "name": "layerID",
          "value": "sha256:501fee28c6e4a55d3b43d4194b23128b14dee7b16025e629f601ff562ee98c18"
        }
      ]
    }
```

The Name node is empty and the pURL node is incomplete. This is causing errors when importing to our analysis tool (Dependency Track).

Other package managers seem to be OK.

**Comment by jonasagx** [comment]
I can look at this.

**Comment by jonasagx** [comment]
Hi @37b thank you for filing the bug report.

I suspect the following files (they might also be [directories](https://setuptools.pypa.io/en/latest/deprecated/python_eggs.html)) are either empty or protected by file-system permissions. Could you please provide a sample of their content?:
* `/usr/lib/python3/dist-packages/.wh.setuptools-52.0.0.egg-info`
* `/usr/lib/python3/dist-packages/.wh.wheel-0.34.2.egg-info`

Without those files `Name`, `pURL`, and CPEs are either empty or incorrect.  For example: `"cpe:2.3:a:python-:python-:*:*:*:*:*:*:*:*"`  — notice the dash to nothing `python-`-- should be `"cpe:2.3:a:python-wheel:python-wheel:0.34.2:*:*:*:*:*:*:*"`

Syft should be explicit about such situations and warn users when there is not enough data to describe a package.

**Comment by samj1912** [comment]
@jonasagx those directory names look very peculiar. If I had to take a guess, I'm guessing that the above bom file was created using layer level analysis. The `.wh.` prefix is a convention used in OCI to mark whiteout paths, i.e. paths that were removed in a subsequent layer. I believe this should be handled properly if the bom was generated for the complete image or if stereoscope properly handled whiteout files when providing a path iterator when inspecting individual container layers.

**Comment by samj1912** [comment]
See https://github.com/opencontainers/image-spec/blob/main/layer.md#whiteouts for more details

**Comment by jonasagx** [comment]
Thank you for pointing that out @samj1912 -- stereoscope drops whiteouts only when [union trees](https://github.com/anchore/stereoscope/blob/main/pkg/filetree/union_filetree.go#L38) squash file trees (the merge function handles it [here](https://github.com/anchore/stereoscope/blob/c97a3c6ffc679cbefcbfd769f4c6f804387006d7/pkg/filetree/filetree.go#L695L703))

Syft's directory resolver uses a filetree which doesn't address whiteouts or opaque files. I think we can filter them out by default in the directory resolver: https://github.com/anchore/syft/pull/1017/files#diff-19136c8def06d093f943fa32bd2a4dc4a83c7415400e3646d0899ea2e3de3e7dR83 I am addressing that on https://github.com/anchore/syft/pull/1017

**Comment by jonasagx** [comment]
Hey @luhring we meant to keep whiteouts? I can see Syft keeping to a minimum what resolvers filter out for the sake of transparency, and letting users decide exclusions via `--exclude` flag. 

By the way: with `syft [IMAGE] --exclude '**/.wh.*'` whiteout files are excluded from the final SBOM.

**Comment by luhring** [comment]
My take: the fact that these files are whiteout files is a good observation to make, but I think that's a red herring on this issue. Our parsers and catalogers in Syft should be able to handle reading empty files (such as whiteout files), and I think it's good that the non-squashed representation of image file trees retain whiteout files.

**Comment by jonasagx** [comment]
Thank you @luhring, this issue touches multiple design questions. I tried to list them with comments:

1. What is the minimum necessary number of fields to describe a [package](https://github.com/jonasagx/syft/blob/main/syft/pkg/package.go#L16)?2. 
I think `name` and `version` are the minimum.

2. Should we enforce these fields (from item 1)? 
Yes, in order to produce valid matchable package info (e.g. CPEs, pURLs). 
Users may want all files (empty or not) listed in an SBM, and that is ok.

3. Catalogers try to include all files matching a pattern, independent of their content, whether empty or not, is that ok?
I think so, but we need tighter requirements when accepting their output in the global list of packages.
