### ISSUE TITLE
Add syft image to ArtifactHub

### ISSUE THREAD

**Issue by developer-guy** [anchore/syft#783]
**What would you like to be added**:

**Why is this needed**:

ArtifactHub has a new feature called Container images repositories.

I would like to add Syft container image to ArtifactHub

https://artifacthub.io/docs/topics/repositories/#container-images-repositories

**Additional context**:

cc: @dirien @dentrax

**Comment by joshbressers** [comment]
@wagoodman Do you have the credentials for ArtifactHub?

**Comment by spiffcs** [comment]
This has been closed -- see https://artifacthub.io/packages/container/syft/syft
