### ISSUE TITLE
opaque error when scanning an image in github registry

### ISSUE THREAD

**Issue by der-ali** [anchore/syft#790]
**What happened**:
getting the following error when i try to scan in image from github registry:
```
failed to construct source from user input "docker.pkg.github.com/xxxxxx": could not fetch image 'docker.pkg.github.com/xxxxxxxxxx': could not read image: unable to populate layer cache dir="/tmp/stereoscope-cachexxxxxxxx.tar" : error verifying size; got 51700240, want 51700241
```
**What you expected to happen**:
successfully scan the image
**How to reproduce it (as minimally and precisely as possible)**:
scan an image located in github registry

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: 0.36.0
- OS (e.g: `cat /etc/os-release` or similar): ubuntu 20.04

**Comment by kzantow** [comment]
Hi @uocxp; do you happen to have any public repos that you could add to this issue to reproduce it?

**Comment by uocxp** [comment]
Hi @kzantow, i don't have any public one right now. I could create one later and update the issue.

**Comment by luhring** [comment]
Hi @der-ali, let us know if you're still seeing this issue. If you are, it'd be great to show how to reproduce the problem. And if not, no worries, we can close this issue for now.
