### ISSUE TITLE
No GH releases for recent tags

### ISSUE THREAD

**Issue by 06kellyjac** [anchore/syft#799]
**What happened**:

No GH releases for `v0.37.X`

**What you expected to happen**:

GH releases for `v0.37.X`

I just want to check these releases are good to package: https://github.com/NixOS/nixpkgs/pull/158440

**Comment by wagoodman** [comment]
@06kellyjac there are no releases for the 0.37.x tags, I hope today there will be a v0.37.x release out --I'll shout out here when there is 👍

**Comment by wagoodman** [comment]
Hey! v0.37.10 has been released (thanks for your patience on this!). I'll close this since it answers the immediate question, but if you have further questions feel free to post here or another issue 👍
