### ISSUE TITLE
Distro identification fails for dir: scheme when identityFiles not in scope.

### ISSUE THREAD

**Issue by psof** [anchore/syft#814]
**What happened**:
Distro identification in syft is completed through the `IdentifyRelease` function which attempts to read the contents of a predefined set of `identityFiles` from the `FileResolver`. If the initial scope did not include the paths to the `identityFiles` then these are not present in the FileResolver's Catalog. As a result distro identification will fail.

This creates a problematic situation when the produced sbom is used with grype in order to identify security vulnerabilities. Grype needs the distro information in order to provide accurate vulnerability reports. If the distro is not identified in the SBOM report, Grype does not match any vulnerabilities from the dpkgdb cataloger.  

For a debian based system if syft attempts to catalog `/var`, then it will catalog all packages under `/var/lib/dpkg/` through `dpkgdb-cataloger` and the distro attribute of the SBOM will remain empty because `/etc/os-release` is not present in the catalog. 

**What you expected to happen**:
Distro Identification should take place regardless of the scope.

**How to reproduce it (as minimally and precisely as possible)**:
```
./syft packages dir:/var -o json --file syft_output.json
./grype sbom:syft_output.json
```

**Anything else we need to know?**:
When this catalog is given as input to grype it wail fail to identify any vulnerabilites for the dpkg cataloged packages as it is missing distro information 

**Environment**: 
- Output of `syft version`:
```
Application:     syft
Version:         0.37.10
BuildDate:       2022-02-08T00:03:55Z
GitCommit:       0ed284212305c76d65687aad6eaabf91142e0ddc
GitDescription:  v0.37.10
Platform:        linux/amd64
GoVersion:       go1.16.13
Compiler:        gc
```
- OS (e.g: `cat /etc/os-release` or similar):
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by samj1912** [comment]
Related to https://github.com/anchore/syft/issues/724

**Comment by psof** [comment]
@luhring I most definitely share your concerns on user control over read files. However, besides feeding data to grype the distribution information is an important piece of information, at least most of the times. Additionally, moving the solution for this problem to manually feeding dist info to grype might also obstruct automation attempts between syft and grype. 

Taking the above under consideration, maybe a configuration option could be introduced that enforces the distro identification when enabled. This way, the user controls whether or not the `identityFiles` are accessed from syft and at the same time enables automation between the two tools.

**Comment by kzantow** [comment]
A brief discussion about this today: if you were able to specify the distro on the command line / environment variable / config file, something like `grype --distro debian:7 ...`, would that be an acceptable solution?

**Comment by jheck88** [comment]
> 

Yep, that'd be great.  Right now I'm trying to syft a directory and all i keep getting is:

`[0000]  INFO could not identify distro`

Identified on Rocky8, UBI8, and WSL2 Ubuntu 22.04

**Comment by spiffcs** [comment]
We pulled this issue forward into our backlog today and found that @kzantow had already added this enhancement into grype.

https://github.com/anchore/grype/pull/606

If anyone finds this was added incorrectly or otherwise is not doing the job described for adding the distro context to the SBOM scans tag me and I can reopen this issue and investigate
