### ISSUE TITLE
anchore/syft:v0.37.10 is weirdly formed

### ISSUE THREAD

**Issue by imjasonh** [anchore/syft#825]
**What happened**:

```
$ crane anchore/syft:v0.37.10
...6 image manifests; 2 unique manifests for arm64 and amd64, each repeated 3x
```

(seems to be the same behavior starting at `:v0.28.0`)

**What you expected to happen**:

```
$ crane anchore/syft:v0.37.10
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 944,
         "digest": "sha256:064b33dad8c376e4100d08354d92d39b90849bdfeea63cf25dac3c5172df7d2d",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 944,
         "digest": "sha256:5fd0367a9ffa0423fb19684f57e5426973ba11bb90056e914d4f937a4a0ebe12",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
    ]
}
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

As far as I know every(?) container runtime handles this just fine, so it's not a huge deal. It doesn't even introduce any kind of correctness bug or ambiguity concern since each manifest points to the same image digest, so there's no way to differently interpret the manifest.

I only discovered this because _someone_ (me) made Tekton's image entrypoint injection a little _too_ strict, as report in https://github.com/tektoncd/pipeline/issues/4566, fixed in https://github.com/tektoncd/pipeline/pull/4569

I just wanted to report it in case this was not expected behavior. I even wouldn't bother going back and fixing old releases.

**Environment**:

N/A

**Comment by imjasonh** [comment]
This seems to be coming from https://github.com/anchore/syft/pull/591 which assembles the manifest from the contents of these images in .goreleaser:

https://github.com/anchore/syft/blob/e1e9ccb401198a48345dbf3f12c5fb7efb7fe645/.goreleaser.yaml#L126-L132

...even though these are only two distinct image digests.

If I understand goreleaser (read: please don't believe me!) I think you could change this to:

```
    image_templates:
      - anchore/syft:v{{ .Major }}.{{ .Minor }}-amd64
      - anchore/syft:v{{ .Major }}.{{ .Minor }}-arm64v8
```

And get functionally the same output image, without duplicated manifests.

(Again, not a huge deal if you don't do anything, keep doing great work, you're great. 🎉 )

**Comment by spiffcs** [comment]
Removing these didn't totally reset it, but I'm looking at the goreleaser documentation now to see what a correct configuration will look like here.
