### ISSUE TITLE
Detect Java Namespaces/Group IDs by hash

### ISSUE THREAD

**Issue by kmoens** [anchore/syft#887]
**What would you like to be added**:
Extends the Java Cataloger with support to determine the group id, if not present in pom.xml/pom.properties, by querying the Maven Central using the SHA-1 hash of the JAR file.

**Why is this needed**:
Currently there is an extensive support by the Java ecosystem to determine the correct namespace. If pom.xml or pom.properties are present, it leads to good and correct results. If they are absent it more a "guess" work currently which leads to quite a lot of incorrect Package URLs for these artifacts.

Using the search by hash would improve the correctness of the results drastically.

**Additional context**:
A bash script which performs this logic is available here:
https://github.com/sjbotha/make-pom/blob/master/make-pom.sh

**Comment by luhring** [comment]
This is a great idea. Today, all of Syft's analysis is static, based only on data that's available locally. The theme of "enhancing a scan via remote lookups" has been emerging for a while now in various aspects of Syft's logic, so it seems inevitable that Syft will start doing this. We still need to work out the details.

**Comment by westonsteimel** [comment]
One thing @wagoodman and I had been discussing around this recently is at least capturing the hash for java artifacts in the metadata so it can at least be used to lookup the correct artifactid and groupid after the fact

**Comment by ChristianCiach** [comment]
Including the hash in the metadata may also help https://dependencytrack.org/ to match the components with the upstream maven artifacts to support vulnerability scanning.

I don't know how exactly "dependency track" currently matches the components to their corresponding maven artifacts. We are using Syft to create SBOMs for java projects on the local filesystem. A java project contains all its dependencies as jar-files inside a `libs/` subdirectory of the project. Syft currently cannot correctly determine the correct maven identifiers just by scanning the jar files. If "dependency track" can use the hashes to lookup the correct maven artifact, including the hashes in the SBOM solve our use case regarding vulnerability scanning.
