### ISSUE TITLE
White paper for Syft ?

### ISSUE THREAD

**Issue by sgirdhar** [anchore/syft#903]
**What would you like to be added**:
Hi,

I was wondering if there is any white paper that was published related to Syft? If there is, a link wold be really helpful. :)

**Why is this needed**:
I am a research student and world like to understand some technical details in more depth.

**Comment by luhring** [comment]
Hi @Shubham-Girdhar! We haven't published a whitepaper on Syft. What kind of details are you looking for?

**Comment by luhring** [comment]
Today Syft doesn't verify the integrity of installed software packages. We've talked about doing this in the future. There would be a few different approaches we could support — digest verification, PGP verification, Sigstore verification — none of which preclude the other.

Here are some related issues to this:

- #23 
- #451 

However, Syft **does** have the ability to compute digests for all detected regular files within the scan target (e.g. in a container image). For example, you could run this to have Syft's output include digests for every file inside `ubuntu:latest`. This could be used in downstream analysis to determine if file integrity met some expected conditions.

```console
$ SYFT_FILE_METADATA_CATALOGER_ENABLED=true syft ubuntu:latest -o json
```

**Comment by seabass-labrax** [comment]
Hello @Shubham-Girdhar! I'm a member of the SPDX Working Group; [SPDX](https://spdx.github.io/spdx-spec/) is the open standard for Software Bill of Materials, which Syft supports. Clearly, @luhring, being a Syft developer, is best placed to describe details about Syft itself, but I could share some papers on Software Bill of Materials in general if you would like :smiley:

**Comment by Shubham-Girdhar** [comment]
Hello @seabass-labrax, thanks for your reply.

Of course, I would really appreciate if you can share some papers about SBOM :)
It would be most helpful if these papers are about the SBOM for container images.

**Comment by seabass-labrax** [comment]
Sorry for the delay in getting back to you, @sgirdhar! I've collected a number of very informative resources that will hopefully help with your research :smiley:

- [MITRE Corporation: Standardizing SBOM within the SW Development Tooling Ecosystem](https://www.mitre.org/sites/default/files/publications/pr-19-01876-16-standardizing-sbom-within-the-sw-development-tooling-ecosystem.pdf) - this is an excellent white paper explaining the different use-cases for Software Bill of Materials. Syft fulfils the 'Usage Scenario 4' in the white paper, and can satisfy 'Usage Scenario 6' in combination with Anchore's Grype tool (also open source). The information collected by Syft can be outputted into an SPDX file, where it can be further enhanced for all of the other Usage Scenarios.
- [Chainguard: What an SBOM Can Do for You](https://blog.chainguard.dev/what-an-sbom-can-do-for-you/) - this is a short but accurate summary of the real-world situation with SBOMs, explaining the different aspects needed to use them in an automated way.
- [Microsoft: Generating Software Bills of Materials (SBOMs) with SPDX at Microsoft](https://devblogs.microsoft.com/engineering-at-microsoft/generating-software-bills-of-materials-sboms-with-spdx-at-microsoft/) - this is a blog post that explains SBOMs in a specific but important development: the USA's Executive Order 14028, which has led to lots of development of SBOM use in government settings. Other countries have published similar regulations that I could link you to if you're interested!

I also gave a talk at the FOSDEM 2022 conference entitled 'The Principles of Effective Software Bill of Materials'. If you'd like to see a recording of that, do let me know and I can get that sent to you!

Hope this helps :grinning:

**Comment by sgirdhar** [comment]
No worries @seabass-labrax, thank you so much for your valuable inputs :)

> Other countries have published similar regulations that I could link you to if you're interested!

> I also gave a talk at the FOSDEM 2022 conference entitled 'The Principles of Effective Software Bill of Materials'. If you'd like to see a recording of that, do let me know and I can get that sent to you!

I am interested to checkout both these resources

**Comment by luhring** [comment]
Thanks for the resources, @seabass-labrax!

**Comment by luhring** [comment]
I'm going to close this issue for now — but please feel free to continue adding links here for reference. 😃
