### ISSUE TITLE
Investigate a syft docker desktop extension 

### ISSUE THREAD

**Issue by samj1912** [anchore/syft#929]
**What would you like to be added**: Docker extensions for docker desktop were just announced. It would be nice if both syft and grype supported this. 

**Why is this needed**: Native integration into docker desktop. Better discovery for syft and grype. 

**Additional context**:

See https://www.docker.com/blog/docker-extensions-preview/

**Comment by samj1912** [comment]
I guess this can be closed in favor of https://www.docker.com/blog/announcing-docker-sbom-a-step-towards-more-visibility-into-docker-images/

**Comment by spiffcs** [comment]
@samj1912 it's even better! That release was in a partnership with syft.
"The functionality was developed as an [open source collaboration](https://github.com/docker/sbom-cli-plugin) with [Anchore](https://anchore.com/) using their [Syft](https://github.com/anchore/syft) project"

[sbom-plugin](https://github.com/docker/sbom-cli-plugin)
