### ISSUE TITLE
Singularity Image Format (SIF) support

### ISSUE THREAD

**Issue by tri-adam** [anchore/syft#937]
**What would you like to be added**:

Support for generating an SBOMs from containers packaged in the [Singularity Image Format (SIF) ](https://github.com/sylabs/sif):

```sh
syft packages sif:image.sif
```

**Why is this needed**:

Singularity users package their containers in SIF, and are increasingly interested in supply chain security. It'd be nice if they could use `syft` to generate SBOMs.

**Additional context**:

Sylabs has done some initial research on integrating SIF and Syft, and we'd be happy to open pull request(s) with that initial work if there's support for this feature being added to `syft`.

Related: https://github.com/sylabs/sif/issues/190

**Comment by luhring** [comment]
Sounds great! We'd love to help guide any PRs to the finish line here. Let us know what you need from us.
