### ISSUE TITLE
gemspecs going unreported

### ISSUE THREAD

**Issue by rgeissert** [anchore/syft#960]
**What happened**:
Trying out syft on the extracted content of the cinc-auditor deb package it looks like the gemspec cataloguer is missing plenty of gems.

```shell
$ syft cinc-auditor
 ✔ Indexed cinc-auditor    
 ✔ Cataloged packages      [6 packages]
NAME             VERSION  TYPE         
concurrent_ruby           java-archive  
diff-lcs         1.1.3    gem           
ed25519_jruby             java-archive  
power_assert     1.0.2    gem           
rake             0.9.6    gem           
test-unit        3.2.3    gem
```

So it found 4 gems out of:
```
$ find cinc-auditor/ -wholename '*/specifications/*.gemspec'|wc -l
302
```

**How to reproduce it (as minimally and precisely as possible)**:
```
$ wget https://downloads.cinc.sh/files/stable/cinc-auditor/5.12.2/debian/11/cinc-auditor_5.12.2-1_arm64.deb
$ dpkg -x cinc-auditor_5.12.2-1_arm64.deb cinc-auditor
$ syft cinc-auditor
```

**Environment**:

- Application:        syft
Version:            0.44.0
JsonSchemaVersion:  3.2.2
BuildDate:          2022-04-12T18:59:04Z
GitCommit:          b46d044d7e3afc2ee09fd5ff26635f783628126e
GitDescription:     v0.44.0
Platform:           linux/amd64
GoVersion:          go1.18
Compiler:           gc

**Comment by luhring** [comment]
Hi @rgeissert, thanks for the issue. Today Syft uses different strategies for finding software depending on whether the scan targets a filesystem or a container image. There's active discussion and work around making this more configurable (see #465) in order to better meet users' needs.

Can I ask, are you scanning some sort of server? This is the use case we've heard the most about, regarding Syft needing to shift its cataloging strategy.

**Comment by rgeissert** [comment]
I was just giving syft a try and nothing in the documentation gave me any hint that the outcome would be partial or any different than running it against a container image.
Other than that, yes, scanning a directory of a server (e.g. /opt) could be one of the use cases for syft that I can think of.

**Comment by luhring** [comment]
Understood, and that makes sense. Thanks for the feedback! I'm looking forward to getting #465 added and documented.

**Comment by diptanshumittal** [comment]
Is there any configuration to report dependencies from `*.gemspec` when using directory cataloguer ?
