### ISSUE TITLE
Broken shell completion - Bash

### ISSUE THREAD

**Issue by DanHam** [anchore/syft#962]
**What happened**:

I get an error when I attempt to source the generated Bash shell completions:

```bash
$ source <(syft completion bash)
complete: usage: complete [-abcdefgjksuv] [-pr] [-DEI] [-o option] [-A action] [-G globpat] [-W wordlist] [-F function] [-C command] [-X filterpat] [-P prefix] [-S suffix] [name ...]
```

**How to reproduce it (as minimally and precisely as possible)**:

```bash
$ source <(syft completion bash)
```

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: `syft 0.44.1`

This also occurs with `0.44.0` and `0.43.2`

- OS (e.g: `cat /etc/os-release` or similar):
```bash
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="35 (Cinnamon)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Cinnamon)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Cinnamon"
VARIANT_ID=cinnamon
```

**Comment by spiffcs** [comment]
@DanHam we recently merged a PR that addresses this bug. If you run from main (source <(go run cmd/syft/main.go completion bash) there should be no more error.
![Screen Shot 2022-04-27 at 5 47 45 PM](https://user-images.githubusercontent.com/32073428/165636747-15f4c008-a99e-471e-ab0c-2459b045a346.png)

**Comment by DanHam** [comment]
@spiffcs 

Did #965 make its way into v0.48.0 of syft? If so, I'm afraid the issue is still not fixed.

```bash
$ syft version
Application:        syft
Version:            0.45.0
JsonSchemaVersion:  3.2.2
BuildDate:          2022-04-29T15:47:45Z
GitCommit:          36973021fad57baf443ffa88181394b87ce109a0
GitDescription:     v0.45.0
Platform:           linux/amd64
GoVersion:          go1.18.1
Compiler:           gc

$ source <(syft completion bash)
complete: usage: complete [-abcdefgjksuv] [-pr] [-DEI] [-o option] [-A action] [-G globpat] [-W wordlist] [-F function] [-C command] [-X filterpat] [-P prefix] [-S suffix] [name ...]
```

While I'm sure the command you posted above works, it requires Go to be installed. The command then downloads may GB's of Go packages and takes many minutes to complete. As such, this is not really a practical solution for many (all?) end users. 

I'm assuming you meant this as a temporary work around until this is fixed?

**Comment by DanHam** [comment]
> I'm so sorry @DanHam for the miscommunication in my comment.

Not a problem. Thank you for taking the time to look into this for us.

> The completion file itself being generated does seem to have a few bugs atm and I'll take a look at that portion when I have some more time.

Great - hopefully we'll see a fix for this soon. 

Thanks again for all the time you've spent looking into this (and improving syft in general).

**Comment by julien-carsique-sonarsource** [comment]
The `complete` command is missing the `name`, even if it should be optional according to the documentation.
The bug is resolved by adding at the beginning
```shell
: ${PROG:=$(basename ${BASH_SOURCE})}
```
and editing the end with
```shell
if [[ $(type -t compopt) = "builtin" ]]; then
    complete -o default -F __start_ $PROG
else
    complete -o default -o nospace -F __start_ $PROG
fi
unset PROG
```

I don't know if it's a problem in github.com/spf13/cobra or with the called options.
Tested with GNU bash, version 5.0.17

**Comment by tgerla** [comment]
Hi @DanHam, sorry for the very long delay replying to this ticket. Did you happen to see @julien-carsique-sonarsource's comment above with a patch for the completion script? It sounds like the full fix may require a change to the upstream library (cobra) which creates the completion script. Thanks for any updates if you have them!

**Comment by DanHam** [comment]
Hi @tgerla,

I did see the comment and explanation from @julien-carsique-sonarsource - thanks Julien!

Rather than installing the completion script in e.g. `/usr/share/bash-completion/completions`, I normally just source the generated completion script in my `.bashrc`: `source <(syft completion bash)`

Following Julien's explanation of the root cause above, I was able to get completions working using the following in my `.bashrc`:

```
source <(syft completion bash | sed -e '/complete -o default/ {/"syft"/ !s/$/ syft/}')
```

The sed command just adds 'syft' to the end of the `complete` commands at the end of the completion script. Completion then works as expected

**Comment by tgerla** [comment]
Hi @DanHam, thank you for confirming. I think the best thing we can do in the short term is update the documentation with this workaround. We'll go ahead and put this issue in the backlog. Thanks again!

**Comment by DanHam** [comment]
@cschug is 100% right! While our workarounds 'work' they are definitely not the right fix.

After reading the comment above I did a bit of testing locally to try and fix this. Although I wouldn't consider myself a Go developer either, everything seemed to be fixed / working as expected so I took the plunge and opened a PR!
