### ISSUE TITLE
WARN golang cataloger: failed to read buildinfo

### ISSUE THREAD

**Issue by leizerbeam** [anchore/syft#978]
**What happened**:
In running an SPDX scan of some of my companies container images, it threw warnings. I am wanting to know if its a bug and if it means the SBOM is incomplete because of these WARNS

[0010] WARN golang cataloger: failed to read buildinfo (file="/usr/lib/python3.9/site-packages/orjson.libs/libgcc_s-eedded4b.so.1"): EOF
[0010] WARN golang cataloger: failed to read buildinfo (file="/usr/lib/python3.9/site-packages/orjson/orjson.cpython-39-x86_64-linux-musl.so"): EOF
[0023] WARN golang cataloger: failed to read buildinfo (file="/opt/google/chrome/nacl_helper_bootstrap"): EOF

**What you expected to happen**:
No WARNs

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Docker Desktop for Mac
2. Install grype
brew tap anchore/grype
brew install grope
3. Download k10 images using k10 offline to your local docker repo

docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
    gcr.io/kasten-images/k10offline:4.5.14 pull images

run syft through all packages

syft registry.access.redhat.com/ubi8/ubi-minimal:8.5-240.1648458092 -o spdx > ubi-minimal:8.5-240.1648458092-spdx.out
syft emissaryingress/emissary:2.2.2 -o spdx > emissary:2.2.2-spdx.out
syft grafana/grafana:8.1.8 -o spdx > grafana:8.1.8-spdx.out
syft jimmidyson/configmap-reload:v0.5.0 -o spdx > configmap-reload:0.5.0-spdx.out
syft quay.io/prometheus/prometheus:v2.26.0 -o spdx > prometheus:4.5.14-spdx.out
syft gcr.io/kasten-images/auth:4.5.14 -o spdx > auth-spdx:4.5.14.out
syft gcr.io/kasten-images/upgrade:4.5.14 -o spdx > upgrade:4.5.14-spdx.out
syft gcr.io/kasten-images/catalog:4.5.14 -o spdx > catalog:4.5.14-spdx.out
syft ghcr.io/kanisterio/kanister-tools:0.78.0 -o spdx > kanister-tools:0.78.0-spdx.out
syft gcr.io/kasten-images/crypto:4.5.14 -o spdx > crypto:4.5.14-spdx.out
syft gcr.io/kasten-images/bloblifecyclemanager:4.5.14 -o spdx > bloblifecyclemanager:4.5.14-spdx.out
syft gcr.io/kasten-images/events:4.5.14 -o spdx > events:4.5.14-spdx.out
syft gcr.io/kasten-images/dashboardbff:4.5.14 -o spdx > dashboardbff:4.5.14-spdx.out
syft gcr.io/kasten-images/executor:4.5.14 -o spdx > executor:4.5.14-spdx.out
syft gcr.io/kasten-images/cephtool:4.5.14 -o spdx > cephtool:4.5.14-spdx.out
syft gcr.io/kasten-images/upgrade:4.5.14 -o spdx > upgrade:4.5.14-spdx.out
syft gcr.io/kasten-images/jobs:4.5.14 -o spdx > jobs:4.5.14-spdx.out
syft gcr.io/kasten-images/logging:4.5.14 -o spdx > logging:4.5.14-spdx.out
syft gcr.io/kasten-images/metering:4.5.14 -o spdx > metering:4.5.14-spdx.out
syft gcr.io/kasten-images/state:4.5.14 -o spdx > state:4.5.14-spdx.out
syft gcr.io/kasten-images/admin:4.5.14 -o spdx > admin:4.5.14-spdx.out
syft gcr.io/kasten-images/aggregatedapis:4.5.14 -o spdx > aggregatedapis:4.5.14-spdx.out
syft gcr.io/kasten-images/config:4.5.14 -o spdx > config:4.5.14-spdx.out
syft gcr.io/kasten-images/frontend:4.5.14 -o spdx > frontend:4.5.14-spdx.out
syft gcr.io/kasten-images/kanister:4.5.14 -o spdx > kanister:4.5.14-spdx.out

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
- OS (e.g: `cat /etc/os-release` or similar):
joey.lei@c02fn5adml85 k10-imgs % syft version
Application:        syft
Version:            0.45.0
JsonSchemaVersion:  3.2.2
BuildDate:          2022-04-29T15:47:45Z
GitCommit:          36973021fad57baf443ffa88181394b87ce109a0
GitDescription:     v0.45.0
Platform:           darwin/amd64
GoVersion:          go1.18.1
Compiler:           gc

joey.lei@c02fn5adml85 k10-imgs % sw_vers 
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258

**Comment by luhring** [comment]
Hi @leizerbeam, good question. We've just merged an update for this, and it's out in the new release. The answer to your question is that this was not a real issue scanning Go binaries, the issue was that the Go binary "cataloger" was encountering issues parsing non-Go binaries, which is expected, so we've adjusted the log line to be `INFO` instead of `WARN`. Let me know if you have other questions!

**Comment by leizerbeam** [comment]
Thanks! my dev team also told me the same - but they said they are more concerned about EOF, basically the scanner stopping abruptly and failing to scan more packages or go libraries.

Any thoughts on the EOF messages? Our process to download the images to my local docker repo is the same process used to install our product in air-gap mode (no internet), so we're confident there is no problem there.

**Comment by luhring** [comment]
I want to make sure I understand the question — are you seeing information on Go modules be left out of the SBOM? If so, that's a valid bug. But I wouldn't expect that to be the case, at least without knowing more. The EOF errors were not specific to Go binaries.

**Comment by leizerbeam** [comment]
Here is one of the images that causes this WARN. As mentioned, its a pythons library so its not supported by the golang cataloger.  Whether or not its missing some more packages, I am not sure to be honest, emissary is one of the OSS envoy distributions we are using. Its a third party in this case.

joey.lei@c02fn5adml85 k10-imgs % syft emissaryingress/emissary:2.2.2 -o spdx > emissary:2.2.2-spdx.out | grep WARN
[0000]  INFO new version of syft is available: 0.45.1 (current version is 0.45.0)
 ✔ Loaded image            
 ✔ Parsed image            
 ✔ Cataloged packages      [212 packages]

[0011]  INFO identified distro: Alpine Linux v3.15
[0011]  INFO cataloging image
[0012]  WARN golang cataloger: failed to read buildinfo (file="/usr/lib/python3.9/site-packages/orjson.libs/libgcc_s-eedded4b.so.1"): EOF
[0012]  WARN golang cataloger: failed to read buildinfo (file="/usr/lib/python3.9/site-packages/orjson/orjson.cpython-39-x86_64-linux-musl.so"): EOF

**Comment by luhring** [comment]
The EOF is returned from the Go standard library when it tries to find Go metadata in the file. The file `/usr/lib/python3.9/site-packages/orjson.libs/libgcc_s-eedded4b.so.1` isn't a Go file, so it's expected that this call will return an error, which in this case is an EOF. I haven't looked into the Go standard lib code deep enough to understand why "EOF" in particular is the error returned. But Syft isn't missing any Go packages in this case. Syft doesn't have support for shared object files at this time.

Upgrading to the latest Syft should take care of this warning.
