### ISSUE TITLE
cannot run syft on untagged images

### ISSUE THREAD

**Issue by kajalNair** [anchore/syft#982]
**What happened**:
ran into this issue

```
1 error occurred:
        * failed to construct source from user input "<account_id>.dkr.ecr.ap-south-1.amazonaws.com/security": could not fetch image "<account_id>.dkr.ecr.ap-south-1.amazonaws.com/security": unable to use DockerDaemon source: pull failed: Error response from daemon: manifest for <account_id>.dkr.ecr.ap-south-1.amazonaws.com/security:latest not found: manifest unknown: Requested image not found

```

**What you expected to happen**:

run syft on untagged images

**How to reproduce it (as minimally and precisely as possible)**:

run syft on an image which doesn't have a tag assigned to it.

**Comment by tillepille** [comment]
This seems to work fine for me, at least with docker registry.
Don't have an ECR at hand atm..

```bash
syft --scope all-layers -o cyclonedx-json nginx
 ✔ Loaded image
 ✔ Parsed image
 ✔ Cataloged packages      [239 packages]
```

**Comment by luhring** [comment]
@kajalNair Are you able to provide a full set of steps to reproduce this issue (including the commands that need to be run)? I haven't been able to reproduce this issue yet. We'd need to be able to reproduce this in order to fix it.

**Comment by spiffcs** [comment]
@kajalNair I'm going to close this issue for now. I was unable to reproduce this issue with our current set of test images or common base images. If you can comment with steps to reproduce I'll reopen and we can continue discussion here.
