### ISSUE TITLE
json CycloneDX invalid format

### ISSUE THREAD

**Issue by WhyJee** [anchore/syft#995]
**What happened**:

CycloneDX CLI tool to merge 2 (or more) SBOMs generated with Syft fails to read the SBOMs.
```
Unhandled exception: System.Text.Json.JsonException: The JSON value could not be converted to CycloneDX.Models.Hash+HashAlgorithm. Path: $.components[0].externalReferences[0].hashes[0].alg | LineNumber: 35 | BytePositionInLine: 27.
   at CycloneDX.Json.Converters.HashAlgorithmConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
```

Analyzing the issue we do feel it is more on the Syft side which is generating invalid format.
```
      "externalReferences": [
        {
          "url": "",
          "hashes": [
            {
              "alg": "sha1",
              "content": "..."
            }
          ],
          "type": "build-meta"
        }
      ],
```

From the [CycloneDX Specifications](https://cyclonedx.org/docs/1.4/json/#externalReferences_items_hashes_items_alg) the "alg" must be an enum; and in that case the value shall be `SHA-1`. It can be checked that the generated SBOM is incorrect with CycloneDX tool (`validate` option)

```
$ cyclonedx validate --input-format json --input-version v1_4 --input-file bom.json 
Validating JSON BOM...
Validation failed: 
#
BOM is not valid.
```

Root cause of the issue is probably the conjunction of [encodeExternalReferences](https://github.com/anchore/syft/blob/main/internal/formats/common/cyclonedxhelpers/external_references.go#L59) :  `cyclonedx.HashAlgorithm` is in fact just a [String type](https://github.com/CycloneDX/cyclonedx-go/blob/master/cyclonedx.go#L315). Thus it is technically possible to have any string as value.

And the value comes from the function [CleanDigestAlgorithmName](https://github.com/anchore/syft/blob/main/syft/file/digest_cataloger.go#L124)
```
func CleanDigestAlgorithmName(name string) string {
	lower := strings.ToLower(name)
	return strings.ReplaceAll(lower, "-", "")
}
```
Thus if by chance we had initially `SHA-1` after this function we now have `sha1`.

**What you expected to happen**:

Syft generated SBOM compliant to CycloneDX format and be able to be ingested by CycloneDX tools.

Simplest solution is probably to not use `cyclonedx.HashAlgorithm(string)` but have a simple helper that would check the string and return the appropriate constant (in that case `cyclonedx.HashAlgoSHA1` or throw an error for an unknown Algo.

**How to reproduce it (as minimally and precisely as possible)**:

Generate the SBOM for a simple image generating external references (seems to occur with Java).
```
docker run \
   --rm -it \
   -v /var/run/docker.sock:/var/run/docker.sock \
   -v $PWD:/tmp/reports \
   anchore/syft:latest \
   packages \
   -s AllLayers \
   -o cyclonedx-json \
   --file /tmp/reports/bom.json \
   docker:"openjdk:11"
```

Check the generated `bom.json` file for external references.

Then the SBOM may be validated for its compliance:
```
cyclonedx validate --input-format json --input-version v1_4 --input-file bom.json
```

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: `0.45.1`
- OS (e.g: `cat /etc/os-release` or similar): N/A using docker image

**Comment by kzantow** [comment]
If I could summarize this issue in one sentence, would it be: change "sha1" to "SHA-1" for CycloneDX hash algorithm?

**Comment by WhyJee** [comment]
@kzantow at very high level view we may say "yes".

The point is that :
1. the identified package (at least Java) contains some Digest Algorithms with some value (algo name),
2. this value is transformed (lowercase, no "-")
3. this transformed value is use "as is" when generating Json whereas **it must be one of the supported value**

The issue is at step 3 when encoding the Algo. Thus I would write something like this (not Go expert):
```go
func algorithmFromName(name string) cyclonedx.HashAlgorithm {
	switch name {
	case "md5":
		return cyclonedx.HashAlgoMD5
	case "sha1":
		return cyclonedx.HashAlgoSHA1
	case "sha256":
		return cyclonedx.HashAlgoSHA256
	default:
		log.Fatal(errors.New("Unsupported Algo"))
		return ""
	}
}
```

**Comment by kzantow** [comment]
Right, yes; apologies for simplifying this a bit too much -- this looks like the right solution, I'll see if I can get something in for this soon unless you'd like to try your hand at a PR!

**Comment by spiffcs** [comment]
@WhyJee I'm adding a test that uses the official tooling against our test images for validation so we can catch these before they get into master. I'll fix this issue you highlighted along with other inconsistencies it might catch.

Branch here https://github.com/anchore/syft/tree/995-invalidcyclonedx

**Comment by spiffcs** [comment]
@WhyJee https://github.com/anchore/syft/pull/1000 has been merged. We'll try and cut a new version of syft today with some new features including this fix so be on the lookout!

Thanks again for bringing this to our attention.

**Comment by WhyJee** [comment]
@spiffcs thanks for the rapid fix 🙏 . We'll use it when delivered in new version and check it is ok for us.

**Comment by spiffcs** [comment]
@WhyJee 0.46.1 was released today
